"""
fencing.py

Subdivision Fences data layer (Scale of Permanence step 7). Two fencing
types get real computed geometry here:

  STREAM EXCLUSION FENCING -- streams (USGS NHD, hydrology_data.py) are
  real line geometry today, not a candidate/planning zone, so it's safe
  to buffer them directly. Each stream's centerline is buffered by a
  fixed livestock-exclusion distance, and the BOUNDARY of that buffer
  (the outline, not the filled area) is output as the fence-line
  geometry -- a fence is a line, not an area, so this deliberately
  outputs a LineString/MultiLineString, not the buffered polygon itself.

  PERIMETER FENCING -- the property boundary is already known (the user
  drew it). No buffering or derivation: the boundary line itself IS the
  fence line, wrapped directly in the schema. Geometry only -- no fence
  type/height/material guidance, which is explicitly out of scope (see
  report_generator.py's step 7 framing).

Everything else this step covers -- pond/water zone exclusion fencing,
tree crop/windbreak exclusion fencing, and subdivision/rotational
fencing -- is deliberately NOT computed here, and this module doesn't
attempt it. Those all key off CANDIDATE/planning geometry (a water
system candidate zone from water_candidate_zones.py, a proposed
windbreak, a production zone) rather than a real, already-sited feature
footprint. Buffering a candidate zone and presenting the result as fence
geometry would draw a specific-looking fence line around ground that
isn't a confirmed feature yet -- exactly the kind of misleading
precision this pipeline's confidence_notes convention exists to prevent
(see feature_schema.py). Those get narrative-only treatment instead,
reasoned by Claude at report time from structured context already
computed by earlier steps (water candidate zones, production zones,
valley/ridge delineation, road corridors, building placement) -- same
pattern report_generator.py already uses for tradeoff narration
elsewhere in the report. See report_generator.py's step 7 system-prompt
guidance for exactly how that narrative is framed.

find_stream_exclusion_fencing() is the pure geometric core (Step 1): no
network I/O, takes already-fetched stream features and a target UTM CRS
-- same "logic separable from fetching" split as
water_candidate_zones.find_candidate_zones(). perimeter_fencing_to_geojson()
needs no fetch or projection at all (Step 2) -- it just wraps the
boundary coordinates already in hand.
"""

from typing import Optional

from rasterio.warp import transform_geom
from shapely.geometry import mapping, shape

from feature_schema import CONFIDENCE_HIGH, CONFIDENCE_MEDIUM, make_feature, make_feature_collection
from hydrology_data import get_water_features_geojson

# Buffer distance (meters) used to turn a stream's real NHD centerline
# into a livestock-exclusion fence-line recommendation: the fence runs
# along the outline of this buffer, keeping livestock off the streambank
# and out of the immediate riparian corridor. 10.7m (~35ft) is a
# commonly-cited MINIMUM livestock-exclusion setback in NRCS conservation
# practice guidance (e.g. livestock exclusion / riparian buffer
# standards) -- narrower buffers focused specifically on water-quality/
# habitat benefit commonly go wider (up to 30m/100ft or more). This is a
# rule-of-thumb minimum, not a site-specific regulatory or cost-share
# program setback -- stated plainly since this environment has no live
# network access to verify a specific citation. Deliberately a SEPARATE
# constant from road_corridors.POND_ZONE_EXCLUSION_BUFFER_METERS, which
# serves an unrelated purpose (keeping OTHER infrastructure off a
# candidate pond/dam zone), not livestock exclusion from a real stream.
# CONFIGURABLE -- tune against your own property/program requirements.
STREAM_EXCLUSION_BUFFER_METERS = 10.7

STREAM_EXCLUSION_CONFIDENCE_NOTES_TEMPLATE = (
    "This is a SUGGESTED livestock-exclusion boundary, not a surveyed fence "
    "line: it's generated by buffering the mapped USGS NHD stream centerline "
    "by a fixed {buffer_meters}m ({buffer_feet}ft) distance and outputting the "
    "outline of that buffer. It inherits NHD's own scale/currency limitations "
    "(see hydrology_data.py's confidence_notes) -- actual streambank position, "
    "channel meander, and small/seasonal drainages not captured in NHD may not "
    "match what's on the ground. Walk this line and adjust before building "
    "fence on it."
)

PERIMETER_FENCING_CONFIDENCE_NOTES = (
    "This is the property boundary as drawn, wrapped directly as a fence-line "
    "feature -- no buffering or geometric derivation applied, so it's exactly "
    "as accurate (or inaccurate) as the boundary you drew. It carries no fence "
    "type, height, or material specification (out of scope), and no legal "
    "parcel/ownership-boundary or survey data backs it -- confirm the exact "
    "line against a real survey before building on it."
)

METERS_PER_FOOT = 0.3048


def _utm_epsg_for_lonlat(longitude: float, latitude: float) -> int:
    """
    Same formula as dem_data.py's private helper of the same name,
    duplicated here rather than imported: stream-exclusion buffering
    needs a projected meters-based CRS the same way DEM analysis does,
    but doesn't need (and shouldn't require) fetching an entire DEM
    raster just to get one EPSG code.
    """
    zone = int((longitude + 180) // 6) + 1
    return (32600 if latitude >= 0 else 32700) + zone


def _utm_crs_for_boundary(boundary_coordinates: list[tuple[float, float]]) -> str:
    lons = [pt[0] for pt in boundary_coordinates]
    lats = [pt[1] for pt in boundary_coordinates]
    center_lon = (min(lons) + max(lons)) / 2
    center_lat = (min(lats) + max(lats)) / 2
    return f"EPSG:{_utm_epsg_for_lonlat(center_lon, center_lat)}"


def find_stream_exclusion_fencing(
    stream_features: list[dict],
    utm_crs: str,
    buffer_meters: float = STREAM_EXCLUSION_BUFFER_METERS,
) -> list[dict]:
    """
    Pure geometric core (Step 1) -- no network I/O. Takes already-fetched
    NHD stream features (hydrology_data.get_water_features_geojson()'s
    "hydrology-streams" features -- real WGS84 line geometry, schema-
    wrapped) and a target UTM CRS, buffers each stream by buffer_meters,
    and returns the BOUNDARY of that buffer (a line, not a filled area)
    as fence-line geometry.

    Features with missing/empty geometry are skipped, not raised on --
    same tolerance-for-partial-data reasoning the rest of this pipeline
    uses (see e.g. road_corridors.py's per-source try/except fetches).

    Returns one entry per usable stream feature:
        {
            'source_feature_id': str,   # the input feature's own schema id
            'source_label': str,
            'geometry_wgs84': GeoJSON LineString/MultiLineString,
        }
    """
    results = []
    for feature in stream_features:
        geometry = feature.get("geometry")
        if not geometry or not geometry.get("coordinates"):
            continue

        geometry_utm = shape(transform_geom("EPSG:4326", utm_crs, geometry))
        buffered_polygon_utm = geometry_utm.buffer(buffer_meters)
        if buffered_polygon_utm.is_empty:
            continue

        fence_line_utm = buffered_polygon_utm.boundary
        geometry_wgs84 = transform_geom(utm_crs, "EPSG:4326", mapping(fence_line_utm))

        results.append(
            {
                "source_feature_id": feature["id"],
                "source_label": feature["properties"].get("label") or "Unnamed stream",
                "geometry_wgs84": geometry_wgs84,
            }
        )

    return results


def stream_exclusion_fencing_to_geojson(
    fencing_entries: list[dict], buffer_meters: float = STREAM_EXCLUSION_BUFFER_METERS
) -> dict:
    """Wraps find_stream_exclusion_fencing() output as schema-conformant
    Features on the "exclusion_fencing" layer."""
    confidence_notes = STREAM_EXCLUSION_CONFIDENCE_NOTES_TEMPLATE.format(
        buffer_meters=buffer_meters, buffer_feet=round(buffer_meters / METERS_PER_FOOT, 1)
    )

    features = [
        make_feature(
            feature_id=f"exclusion-fencing-stream-{entry['source_feature_id']}",
            geometry=entry["geometry_wgs84"],
            layer="exclusion_fencing",
            label=f"Stream exclusion fencing ({entry['source_label']})",
            confidence=CONFIDENCE_MEDIUM,
            confidence_notes=confidence_notes,
            extra_properties={
                "source_feature_id": entry["source_feature_id"],
                "exclusion_buffer_meters": buffer_meters,
            },
        )
        for entry in fencing_entries
    ]
    return make_feature_collection(features)


def perimeter_fencing_to_geojson(boundary_coordinates: list[tuple[float, float]]) -> dict:
    """
    Wraps the property boundary itself as the "perimeter_fencing" schema
    feature (Step 2) -- geometry only, no derivation: the boundary line
    already IS the fence line. Output as a closed LineString (a fence is
    a line, not an area) rather than a Polygon, so it renders/behaves
    like the other fence-line features in this module instead of like a
    filled zone.
    """
    coordinates = [tuple(pt) for pt in boundary_coordinates]
    if coordinates[0] != coordinates[-1]:
        coordinates = coordinates + [coordinates[0]]

    feature = make_feature(
        feature_id="perimeter-fencing",
        geometry={"type": "LineString", "coordinates": coordinates},
        layer="perimeter_fencing",
        label="Perimeter fencing (property boundary)",
        confidence=CONFIDENCE_HIGH,
        confidence_notes=PERIMETER_FENCING_CONFIDENCE_NOTES,
    )
    return make_feature_collection([feature])


def identify_fencing(
    boundary_coordinates: list[tuple[float, float]],
    water_features_geojson: Optional[dict] = None,
    stream_exclusion_buffer_meters: float = STREAM_EXCLUSION_BUFFER_METERS,
) -> dict:
    """
    Full pipeline entry point for Subdivision Fences' computed geometry
    (Step 1 + Step 2 only -- see module docstring for why everything else
    in that report step is narrative-only, not generated here).

    water_features_geojson is hydrology_data.get_water_features_geojson()'s
    output; fetched here if not already supplied (e.g. reused from a
    caller that already fetched it). Same independent-fetch pattern
    every other pipeline module in this codebase uses (each fetches what
    it needs rather than sharing state across pipeline stages) --
    generate_full_report.py's own hydrology fetch for the WATER SUPPLY
    section is untouched by this.

    Returns:
        {
            'fencing_geojson': FeatureCollection,   # "exclusion_fencing" (stream) + "perimeter_fencing" features -- the deliverable
        }
    """
    if water_features_geojson is None:
        water_features_geojson = get_water_features_geojson(boundary_coordinates)

    stream_features = [
        f for f in water_features_geojson["features"] if f["properties"]["layer"] == "hydrology-streams"
    ]

    utm_crs = _utm_crs_for_boundary(boundary_coordinates)
    stream_entries = find_stream_exclusion_fencing(stream_features, utm_crs, stream_exclusion_buffer_meters)

    features = (
        stream_exclusion_fencing_to_geojson(stream_entries, stream_exclusion_buffer_meters)["features"]
        + perimeter_fencing_to_geojson(boundary_coordinates)["features"]
    )

    return {"fencing_geojson": make_feature_collection(features)}


def summarize_fencing(result: dict) -> str:
    features = result["fencing_geojson"]["features"]
    stream_count = sum(1 for f in features if f["properties"]["layer"] == "exclusion_fencing")
    has_perimeter = any(f["properties"]["layer"] == "perimeter_fencing" for f in features)

    lines = [f"Computed fencing features: {stream_count} stream exclusion, perimeter: {'yes' if has_perimeter else 'no'}"]
    for feature in features:
        props = feature["properties"]
        if props["layer"] == "exclusion_fencing":
            lines.append(f"  - {props['label']} ({props['exclusion_buffer_meters']}m buffer)")
        else:
            lines.append(f"  - {props['label']}")
    return "\n".join(lines)


if __name__ == "__main__":
    # Test case: the user's own drawn property boundary.
    property_boundary = [
        (-79.9838154, 40.6458343),
        (-79.9836701, 40.6428581),
        (-79.9813665, 40.6440549),
        (-79.9804741, 40.6445667),
        (-79.9827466, 40.6458894),
        (-79.9838258, 40.6458343),
    ]

    print("Identifying computed fencing (stream exclusion + perimeter) for property boundary...\n")

    try:
        from feature_schema import validate_feature_collection

        result = identify_fencing(property_boundary)
        validate_feature_collection(result["fencing_geojson"])
        print(summarize_fencing(result))
        print("\nfencing_geojson is schema-valid.")
    except Exception as e:
        print(f"Request failed: {e}")
        print(
            "\nNote: this requires internet access to reach USGS's National "
            "Map ImageServer — not a fully sandboxed environment."
        )
