"""
road_corridors.py

Computes suggested road corridor geometry from the DEM, for properties
that lack existing farm road/access data — this REPLACES having Claude
infer a plausible-sounding corridor in prose during report generation
(report_generator.py's Farm Roads step used to do exactly that, with an
explicit "no dedicated access data" disclaimer). Same pattern as
water_candidate_zones.py and solar_suitability.py: the backend computes
real geometry, Claude narrates from the result.

Candidates are generated by routing a least-cost path (road_cost_path.py
— see that module for the cost-raster/Dijkstra core itself, imported and
used here, not reimplemented) across a per-cell traversal-cost grid built
from this property's own slope, exclusion, and production-zone data:

  SOURCE CELLS: the DEM's own row/col extent is split into a fixed
  ROAD_SOURCE_GRID_ROWS x ROAD_SOURCE_GRID_COLS grid of quadrants
  (_select_quadrant_source_cells()), and the single eligible cell nearest
  each quadrant's own center becomes that quadrant's source — up to 4
  independent routing attempts spread across the property, rather than
  one arbitrary starting point or an exhaustive search from everywhere
  eligible. A quadrant with no eligible ground at all is skipped, not
  forced to contribute a source from somewhere else.

  DESTINATION CELLS: a two-tier search (_select_destination_cells()) —
  eligible cells near real, existing road frontage first
  (ROAD_DESTINATION_SEARCH_METERS), falling back to eligible cells near
  the parcel boundary itself (ROAD_BOUNDARY_ADJACENT_METERS) whenever no
  road data is available, or nothing eligible falls within the first
  tier's search radius. Every destination candidate is passed into a
  single least_cost_path() call together — Dijkstra's own ascending-cost
  pop order already finds whichever one is cheapest, so this never needs
  to run once per destination candidate.

  ROUTING: one least_cost_path() call PER SOURCE CELL (not one combined
  multi-source call across all four) against every destination candidate
  at once — each quadrant's source produces its own independent
  candidate route, rather than every quadrant collapsing onto whichever
  single path happens to be cheapest overall. Up to 4 candidates result,
  one per quadrant that had eligible ground to start from.

  RANKING: candidates are ranked by ascending total_cost
  (least_cost_path()'s own Dijkstra path cost — the running sum of grade-
  and production-penalized edge weights along the route), not a separate
  weighted composite score. suitability_score is a simple normalization
  of that same total_cost against the most expensive candidate in this
  batch, kept only for continuity with existing report/render code that
  expects a 0-100 score to display.

Constraint stack, split cleanly into HARD exclusions (baked into
cost_raster as np.inf — a candidate genuinely cannot be routed through
these at all) and a SOFT cost preference (baked into cost_raster as a
finite penalty a route can still choose to pay):
  - HARD exclusions:
      - outside the single SELECTED water-system candidate zone
        (water_suitability.fetch_and_select_optimal_water_zone() — the
        one rank-1 zone this property's own water-suitability scoring
        actually picked, not every unscored candidate zone
        water_candidate_zones.py generates), buffered wider — routing on
        the uphill side of a pond/dam, not across its face or catchment
        inlet
      - outside floodplain/hydric ground, sourced from real NHD stream/
        water-body buffers + SSURGO hydric soil polygons (NOT inferred
        from DEM elevation alone) — falls back to a buffer around
        delineated valley lines only if neither NHD nor SSURGO data is
        reachable, and flags that fallback explicitly in confidence_notes
      - within a pinned maximum grade (MAX_ROAD_GRADE_PCT) — and, via
        road_cost_path.build_cost_raster()'s own quadratic grade penalty,
        a route that stays comfortably under that ceiling is preferred
        over one that merely clears it
  - SOFT cost preference:
      - production zones — a flat per-cell cost penalty
        (road_cost_path.PRODUCTION_CROSSING_COST_PENALTY), not an
        exclusion. A road is a thin linear feature, not a large permanent
        land claim the way a pond/dam site is, so crossing production
        land is a real, valid routing option (same reasoning as
        solar_suitability.py's own production-zone-proximity redesign)
        when the alternative is a meaningfully longer detour. This was a
        hard exclusion in an earlier version of this module; with
        production_area.py's own slope ceiling now at 20%, one large
        production zone can cover most of a property's gentle ground, and
        hard-excluding it left nowhere for a corridor to exist at all
        (confirmed live: zero corridor candidates with the exclusion,
        real candidates once it was removed).

Erosion-prone soil (SSURGO K-factor) is deliberately NOT part of this
module's constraint stack at all, hard or soft — this pipeline's own
KSOP (Keyline Scale of Permanence) ordering puts Soil at step 8, well
below Farm Roads at step 4; scoring a step-4 feature against step-8 data
inverted that ordering, so the erosion-avoidance preference this module
used to carry has been removed outright, not just softened further.

Corridor anchoring (connecting the near-boundary end of a generated
corridor to the property line) anchors to a real, NAMED mapped existing
road only (farm_roads_data.py, filtered here to drop its "Unnamed road"
fallback entries — an anonymous fetched segment, e.g. an unlabeled
driveway, is not a plausible frontage to claim by name) — the connector
snaps toward the nearest point on that real named road's own frontage,
and properties.anchor_road_name / anchor_status="connected_to_named_road"
report which one. When no named road is reachable nearby, this does NOT
fall back to an arbitrary boundary point — the candidate is kept as-is,
with no connector segment at all, and anchor_status is
"no_named_road_available".

find_candidate_road_corridors() is the pure geometric/scoring core — see
water_candidate_zones.py's and solar_suitability.py's docstrings for why
this split matters (independently testable against a synthetic DEM,
without any of the several real network fetches this feature depends on).
"""

import math
from typing import Literal, Optional

import numpy as np
import requests
from rasterio.warp import transform as warp_transform
from rasterio.warp import transform_geom
from shapely.geometry import LineString, Point, Polygon, shape
from shapely.ops import nearest_points, unary_union
from shapely.prepared import prep

from dem_data import get_dem_for_boundary
from farm_roads_data import get_farm_roads_for_boundary
from feature_schema import CONFIDENCE_LOW, make_feature, make_feature_collection
from hydrology_data import get_water_features_for_boundary
from production_area_ceiling import identify_optimized_production_areas
from raster_grid import pixel_center_xy
from road_cost_path import build_cost_raster, least_cost_path, path_cells_to_points_xyz
from soil_data import (
    coordinates_to_wkt_polygon,
    get_soil_data_for_polygon,
    get_soil_geometries_for_polygon,
    hydric_disqualifying_mukeys,
)
from terrain_metrics import compute_slope_and_aspect
from valley_delineation import delineate_valleys
from water_suitability import fetch_and_select_optimal_water_zone

METERS_PER_FOOT = 0.3048

# Maximum sustained grade for a suggested farm road corridor. Pinned, not
# left for Claude to pick contextually, per this feature's explicit
# requirement. 10% is a widely-cited practical ceiling for sustained grade
# on a low-volume gravel farm/ranch road in USDA NRCS and US Forest
# Service low-standard-road design guidance: below ~10% sustained, a
# gravel road is comfortably drivable/haulable and holds up to normal
# erosion/maintenance. Raised to 15%: short pitches up to ~12-15% are
# tolerated in the wild on low-volume farm/ranch roads (the same guidance
# that treats 10% as the comfortable ceiling also cites this range as
# where real engineering consideration -- surface material, drainage/
# culverts, water bars -- becomes necessary rather than optional, not
# where the road becomes unbuildable). This still excludes genuinely
# unworkable ground above that range. This is a commonly-cited
# rule-of-thumb figure, not a single pinned regulatory document — stated
# plainly since this environment has no live network access to verify a
# specific citation. CONFIGURABLE — replace with a site-specific/
# regulatory value if one applies to your property.
MAX_ROAD_GRADE_PCT = 15.0

# Above this average grade, a candidate corridor is steep enough that
# confidence_notes flags it as needing real engineering consideration
# (surface material, drainage/culverts, water bars) before construction --
# not just the blanket "topographic suggestion, not a surveyed alignment"
# caveat every candidate already carries. Set at the OLD 10% ceiling
# (rather than some fraction of the new 15% one): grade at or below what
# used to be the hard cutoff still reads as comfortably within normal
# gravel-road practice; anything above it is in the range this codebase's
# own MAX_ROAD_GRADE_PCT reasoning above already treats as "tolerated but
# needs real engineering attention," not a new/arbitrary line. CONFIGURABLE.
STEEP_GRADE_ENGINEERING_NOTE_THRESHOLD_PCT = 10.0

# Fixed quadrant grid the DEM's own row/col extent is split into for
# _select_quadrant_source_cells() -- 2x2 spreads routing attempts across
# the whole property (one per rough compass corner) without the cost of
# an exhaustive per-cell search. CONFIGURABLE — a finer grid gives more,
# more-localized candidates at the cost of more least_cost_path() calls;
# this is a deliberately unvalidated starting value pending a real
# diagnostic sweep, same caveat every other threshold in this pipeline
# carries.
ROAD_SOURCE_GRID_ROWS = 2
ROAD_SOURCE_GRID_COLS = 2

# Tier 1 destination search radius (see _select_destination_cells()):
# eligible cells within this distance of real, existing road frontage.
# CONFIGURABLE, deliberately unvalidated starting value.
ROAD_DESTINATION_SEARCH_METERS = 50.0

# Tier 2 destination search radius (fallback, used when no road data is
# available or Tier 1 comes back empty): eligible cells within this
# distance of the parcel boundary's own exterior ring. CONFIGURABLE,
# deliberately unvalidated starting value.
ROAD_BOUNDARY_ADJACENT_METERS = 15.0

# Buffer beyond a pond/water-system candidate zone's own footprint --
# wider than the production-zone buffer, since this needs to keep a
# corridor off a dam face or catchment inlet, not just the pond footprint
# itself. CONFIGURABLE.
POND_ZONE_EXCLUSION_BUFFER_METERS = 25.0

# Buffer applied to NHD streams/water bodies (and, in the elevation-only
# fallback case, to delineated valley lines) as the floodplain/riparian
# exclusion. 30m (~100ft) is a commonly-used minimal riparian buffer
# rule of thumb, not a site-specific regulatory setback. CONFIGURABLE.
FLOODPLAIN_STREAM_BUFFER_METERS = 30.0

# How far past the parcel boundary to still care about a fetched NHD
# stream/water-body's own geometry before it gets buffered into the
# floodplain exclusion union. REAL BUG, FOUND LIVE (fixed here):
# hydrology_data.py's NHD query (an ArcGIS `query` operation) returns
# each matching feature's FULL, un-clipped geometry for anything that
# merely intersects the query bounding box -- a long stream or a large
# waterbody that just touches that box can come back with geometry
# extending far past the property, which then got buffered (widening it
# further) and unioned into this exclusion mask WHOLESALE. Confirmed
# live: a 33.9-ACRE floodplain/hydric union on a 13.23-acre parcel,
# which alone was large enough to swallow every corridor candidate.
# Same root-cause CATEGORY (a fetch returning geometry far beyond the
# input boundary's actual relevant extent, not clipped to it) as the
# earlier soil_data.get_soil_geometries_for_polygon() bug -- that one's
# already fixed at the SSURGO query itself (real STIntersects +
# STIntersection clipping); NHD's ArcGIS `query` endpoint has no
# equivalent server-side clip parameter here, so this clips CLIENT-SIDE
# instead, against a generous context region around the parcel --
# comfortably larger than both dem_data.py's own ~100m DEM fetch buffer
# and FLOODPLAIN_STREAM_BUFFER_METERS itself, so clipping here can never
# cut off a stream segment that would otherwise matter to on-parcel
# corridor generation or its exclusion-margin scoring. CONFIGURABLE.
FLOODPLAIN_FETCH_CONTEXT_BUFFER_METERS = 200.0

# SECOND real bug, found live AFTER the fetch-context clip above landed:
# that clip is applied to each stream/water-body feature's RAW geometry
# BEFORE it gets buffered by FLOODPLAIN_STREAM_BUFFER_METERS -- nothing
# bounded the geometry AFTER buffering, so the buffer stroke itself (and,
# more significantly, however much of the stream's length survived the
# 200m fetch-context clip) could still produce a final exclusion piece
# extending well past any distance actually relevant to this parcel.
# Confirmed live and visually (plotted GeoJSON against the real property):
# an 11.2-acre union where only 0.077 acres (0.6% of the parcel) actually
# overlapped it -- the rest was a long buffered band running along Montour
# Run, entirely on the far side of N Montour Rd from the field, nowhere
# near the parcel. This constant bounds the FINAL unioned/buffered result
# (after FLOODPLAIN_STREAM_BUFFER_METERS is applied) to a region tied to
# the parcel itself, independent of how far the original fetched geometry
# or its buffer stroke reached. Deliberately meaningfully SMALLER than
# FLOODPLAIN_FETCH_CONTEXT_BUFFER_METERS (200m) -- that larger buffer's
# job is only to avoid losing a stream segment's geometry at fetch time;
# this one's job is to bound what actually counts as "close enough to this
# parcel to matter" for exclusion/scoring purposes. Still meaningfully
# LARGER than FLOODPLAIN_STREAM_BUFFER_METERS (30m) alone, so a stream
# running close to (but not quite touching) the parcel -- genuine
# near-parcel floodplain risk on a differently-shaped property -- doesn't
# get clipped away just because its own 30m buffer stroke doesn't quite
# reach the boundary. CONFIGURABLE.
FLOODPLAIN_FINAL_RELEVANCE_BUFFER_METERS = 75.0

# Drop candidates shorter than this -- not a meaningful road.
# CONFIGURABLE.
MIN_CORRIDOR_LENGTH_METERS = 30.0

# How many top-ranked candidates to return. Currently a NON-BINDING
# ceiling: quadrant-based source selection (_select_quadrant_source_cells())
# naturally produces at most ROAD_SOURCE_GRID_ROWS * ROAD_SOURCE_GRID_COLS
# candidates (4, by default) -- well under this cap. Kept as a defensive
# limit in case the sourcing strategy changes later (a finer quadrant
# grid, multiple sources per quadrant, etc.), not removed just because
# it doesn't currently bind. CONFIGURABLE.
MAX_CANDIDATES = 5

ROAD_CORRIDOR_CONFIDENCE_NOTES_TEMPLATE = (
    "This is a TOPOGRAPHIC SUGGESTION only, not a surveyed road alignment — "
    "generated from a DEM-based least-cost-path routing model (a grade + "
    "production-zone cost surface — see road_cost_path.py), not a civil "
    "engineering design. Production zones are NOT excluded here — a road is "
    "a thin linear feature, not a large permanent land claim the way a "
    "pond/dam site is, so crossing production land is a real, valid routing "
    "option when it's genuinely the cheaper route; it costs more per cell "
    "crossed rather than being disallowed outright (see "
    "properties.crosses_production_zone). {production_crossing_note}"
    "The single selected water-system candidate zone and floodplain/hydric "
    "ground ARE still hard-excluded. {connector_note}"
    "{steep_grade_note}{floodplain_note}Treat this as a starting point for a site "
    "visit and real survey, not a construction-ready alignment."
)

PRODUCTION_CROSSING_NOTE = (
    "This specific candidate DOES cross a production zone — that's intentional/expected under this "
    "model, not a caveat to apologize for; the least-cost-path routing found crossing it was still "
    "cheaper overall than detouring around it from this candidate's own starting point. "
)

# Additive caveat (see STEEP_GRADE_ENGINEERING_NOTE_THRESHOLD_PCT above) —
# appended only for candidates steep enough that routine grading isn't
# enough; the blanket "topographic suggestion" disclaimer above still
# applies to every candidate regardless of grade.
STEEP_GRADE_ENGINEERING_NOTE = (
    "This candidate's average grade ({avg_grade_pct}%) is steep enough for an unpaved farm road "
    "that real engineering consideration — surface material, drainage/culverts, water bars — is "
    "needed before construction, not just routine grading: erosion, traction, and washout risk all "
    "increase meaningfully above {threshold_pct:.0f}%, especially under heavy rainfall or "
    "freeze-thaw conditions. "
)


def _build_exclusion_cell_mask(dem: dict, excluded_prepared, boundary_prepared) -> np.ndarray:
    """Per-cell boolean mask (True = excluded), built once by testing
    every valid cell center against the (prepared, unioned) exclusion
    geometry AND against the real parcel boundary — reused across every
    contour band and ridge branch rather than re-testing point-in-polygon
    per band.

    A cell outside boundary_prepared is excluded here the same way an
    excluded-zone cell is — this is what keeps contour-band and ridge-top
    candidates from being generated out of the DEM's buffered area past
    the drawn boundary (dem_data.py fetches ~100m past the parcel on
    purpose; without this, a candidate could be built entirely from
    off-parcel cells). The only geometry that's still allowed to touch/
    reach the boundary line is the single connector segment
    _anchor_to_boundary() adds afterward, when a named road is available
    to anchor to — not something this mask should (or does) affect."""
    array = dem["array"]
    rows, cols = array.shape
    excluded = np.zeros((rows, cols), dtype=bool)

    valid = ~np.isnan(array)
    for r in range(rows):
        for c in range(cols):
            if not valid[r, c]:
                continue
            point = Point(pixel_center_xy(dem, r, c))
            if not boundary_prepared.contains(point):
                excluded[r, c] = True
            elif excluded_prepared is not None and excluded_prepared.contains(point):
                excluded[r, c] = True
    return excluded


def _build_production_cell_mask(dem: dict, production_prepared, boundary_prepared) -> np.ndarray:
    """Per-cell boolean mask (True = cell center falls inside the
    production-zone union) -- same iteration structure as
    _build_exclusion_cell_mask(), reused here as a COST-PENALTY input
    (build_cost_raster()'s production_mask) rather than a hard exclusion:
    crossing production land costs more, it isn't disallowed.

    production_prepared is the (prepared) union of production_areas' own
    render_fill_polygon_utm geometry (see find_candidate_road_corridors()),
    or None if this property has no production zones at all -- in which
    case every cell is simply False. A cell outside boundary_prepared is
    left False here too: off-parcel cells are already hard-excluded via
    excluded_mask/cost_raster regardless of this mask's value for them, so
    there's nothing meaningful to report about their production status."""
    array = dem["array"]
    rows, cols = array.shape
    production_mask = np.zeros((rows, cols), dtype=bool)

    if production_prepared is None:
        return production_mask

    valid = ~np.isnan(array)
    for r in range(rows):
        for c in range(cols):
            if not valid[r, c]:
                continue
            point = Point(pixel_center_xy(dem, r, c))
            if boundary_prepared.contains(point) and production_prepared.contains(point):
                production_mask[r, c] = True
    return production_mask


def _select_quadrant_source_cells(
    dem: dict,
    eligible_mask: np.ndarray,
    boundary_polygon_utm: Polygon,
) -> list[tuple[int, int]]:
    """
    Splits the DEM grid's own row/col extent into a fixed
    ROAD_SOURCE_GRID_ROWS x ROAD_SOURCE_GRID_COLS grid of quadrants and
    returns, for each quadrant that has ANY eligible cell at all, the
    single eligible cell nearest that quadrant's own center (plain row/col
    Euclidean distance -- cheap grid-index arithmetic, no shapely geometry
    needed for this part). A quadrant with zero eligible cells is skipped
    entirely, not forced to contribute a source from somewhere else --
    the same "an honest, possibly-shorter answer beats a forced one"
    pattern every other candidate-generation step in this pipeline
    follows.

    Returns up to ROAD_SOURCE_GRID_ROWS * ROAD_SOURCE_GRID_COLS cells
    (4, by default).

    boundary_polygon_utm is accepted for signature symmetry with
    _select_destination_cells() (which does need it, for its own Tier 2
    fallback) but isn't used here directly: eligible_mask itself already
    reflects the boundary (any off-parcel cell is hard-excluded upstream,
    in _build_exclusion_cell_mask()), so a second boundary check here
    would be redundant.
    """
    rows, cols = eligible_mask.shape
    eligible_rc = np.argwhere(eligible_mask)
    if eligible_rc.size == 0:
        return []

    row_edges = np.linspace(0, rows, ROAD_SOURCE_GRID_ROWS + 1)
    col_edges = np.linspace(0, cols, ROAD_SOURCE_GRID_COLS + 1)

    source_cells = []
    for qr in range(ROAD_SOURCE_GRID_ROWS):
        row_lo, row_hi = row_edges[qr], row_edges[qr + 1]
        center_row = (row_lo + row_hi) / 2.0
        row_in_quadrant = (eligible_rc[:, 0] >= row_lo) & (eligible_rc[:, 0] < row_hi)

        for qc in range(ROAD_SOURCE_GRID_COLS):
            col_lo, col_hi = col_edges[qc], col_edges[qc + 1]
            center_col = (col_lo + col_hi) / 2.0

            in_quadrant = row_in_quadrant & (eligible_rc[:, 1] >= col_lo) & (eligible_rc[:, 1] < col_hi)
            quadrant_cells = eligible_rc[in_quadrant]
            if quadrant_cells.size == 0:
                continue  # no eligible ground in this quadrant -- skip it, not forced

            distances_sq = (quadrant_cells[:, 0] - center_row) ** 2 + (quadrant_cells[:, 1] - center_col) ** 2
            nearest = quadrant_cells[np.argmin(distances_sq)]
            source_cells.append((int(nearest[0]), int(nearest[1])))

    return source_cells


def _select_destination_cells(
    dem: dict,
    eligible_mask: np.ndarray,
    boundary_polygon_utm: Polygon,
    road_union_utm,
) -> list[tuple[int, int]]:
    """
    Two-tier destination search, independent of _anchor_to_boundary()'s
    own (separate, later) anchoring step:

      Tier 1: if road_union_utm is not None, every eligible cell within
      ROAD_DESTINATION_SEARCH_METERS of it -- routing toward real,
      existing road frontage first.

      Tier 2 (fallback): every eligible cell within
      ROAD_BOUNDARY_ADJACENT_METERS of boundary_polygon_utm's own
      exterior ring -- used whenever road_union_utm is None, OR Tier 1
      comes back empty (a named road exists somewhere nearby, but nothing
      eligible actually falls within its search radius -- this falls
      through rather than silently returning zero destinations just
      because Tier 1 was attempted).

    Returns [] if both tiers come back empty (no eligible cell anywhere
    near either a real road or the parcel boundary) -- shouldn't happen on
    a property with any eligible ground reaching its own edge, but a real,
    defensive possibility worth returning honestly rather than raising;
    callers treat this the same way least_cost_path()'s own "no path
    found" None already is handled.
    """
    eligible_rc = np.argwhere(eligible_mask)
    if eligible_rc.size == 0:
        return []

    def _cells_within(target_geometry, distance_meters: float) -> list[tuple[int, int]]:
        search_region = prep(target_geometry.buffer(distance_meters))
        cells = []
        for r, c in eligible_rc:
            r, c = int(r), int(c)
            if search_region.contains(Point(pixel_center_xy(dem, r, c))):
                cells.append((r, c))
        return cells

    if road_union_utm is not None:
        tier1_cells = _cells_within(road_union_utm, ROAD_DESTINATION_SEARCH_METERS)
        if tier1_cells:
            return tier1_cells

    return _cells_within(boundary_polygon_utm.exterior, ROAD_BOUNDARY_ADJACENT_METERS)


AnchorStatus = Literal["connected_to_named_road", "no_named_road_available"]


def _anchor_to_boundary(
    points_xyz: list[tuple[float, float, float]],
    boundary_polygon_utm: Polygon,
    road_union_utm,
    road_features_utm: Optional[list[dict]] = None,
) -> tuple[list[tuple[float, float, float]], AnchorStatus, Optional[str], Optional[float]]:
    """Extends whichever end of the corridor is closer to the property
    boundary with one connecting vertex on the boundary line, snapped to
    the point nearest a real, NAMED mapped road — road_union_utm and
    road_features_utm are already filtered to named roads only by
    _fetch_existing_road_features_utm() before reaching here (see module
    docstring's "Corridor anchoring" section), so a non-None road_union_utm
    always means a genuine, nameable frontage candidate.

    When no named road is nearby (road_union_utm is None), this does NOT
    fall back to an arbitrary boundary point — it returns points_xyz
    completely unchanged, with no connector vertex appended at all. The
    candidate's own interior geometry is still real DEM-derived routing;
    it simply doesn't reach the boundary.

    road_features_utm (optional, each {'name': str, 'line_utm': LineString})
    is used ONLY to report WHICH real road the anchor snapped toward, when
    one is available — passing None still anchors correctly via
    road_union_utm, it just leaves the reported road name generic/absent.

    Returns (points, anchor_status, anchor_road_name, anchor_road_distance_m).
    The last two are None when anchor_status is "no_named_road_available".
    """
    if road_union_utm is None:
        return points_xyz, "no_named_road_available", None, None

    boundary_line = boundary_polygon_utm.boundary
    end_a = Point(points_xyz[0][0], points_xyz[0][1])
    end_b = Point(points_xyz[-1][0], points_xyz[-1][1])

    anchor_at_start = end_a.distance(boundary_line) <= end_b.distance(boundary_line)
    anchor_end = end_a if anchor_at_start else end_b

    nearest_road_point = nearest_points(anchor_end, road_union_utm)[1]
    boundary_anchor_point = nearest_points(nearest_road_point, boundary_line)[1]
    anchor_road_distance_m = float(anchor_end.distance(road_union_utm))
    anchor_road_name = None
    if road_features_utm:
        nearest_feature = min(road_features_utm, key=lambda f: f["line_utm"].distance(anchor_end))
        anchor_road_name = nearest_feature["name"]

    connector_elevation = points_xyz[0][2] if anchor_at_start else points_xyz[-1][2]
    connector = (float(boundary_anchor_point.x), float(boundary_anchor_point.y), connector_elevation)

    extended = [connector] + points_xyz if anchor_at_start else points_xyz + [connector]
    return extended, "connected_to_named_road", anchor_road_name, anchor_road_distance_m


def _grade_stats(points_xyz: list[tuple[float, float, float]]) -> tuple[float, float]:
    grades = []
    for (x1, y1, z1), (x2, y2, z2) in zip(points_xyz, points_xyz[1:]):
        distance = math.hypot(x2 - x1, y2 - y1)
        if distance > 0:
            grades.append(abs(z2 - z1) / distance * 100.0)
    if not grades:
        return 0.0, 0.0
    return float(np.mean(grades)), float(np.std(grades))


def find_candidate_road_corridors(
    dem: dict,
    production_areas: list[dict],
    selected_water_zone: Optional[dict],
    boundary_polygon_utm: Polygon,
    hydric_floodplain_union=None,
    road_union_utm=None,
    road_features_utm: Optional[list[dict]] = None,
    max_grade_pct: float = MAX_ROAD_GRADE_PCT,
    min_corridor_length_meters: float = MIN_CORRIDOR_LENGTH_METERS,
    max_candidates: int = MAX_CANDIDATES,
) -> list[dict]:
    """
    Pure geometric/scoring core — see module docstring for why this takes
    already-computed inputs (production areas, the single selected water
    zone, floodplain exclusion union, optional real-road data for
    anchoring) rather than fetching or delineating anything itself.

    selected_water_zone is water_suitability.fetch_and_select_optimal_
    water_zone()'s own single rank-1 answer (or None if no water zone was
    identified) -- each entry carrying 'render_fill_polygon_utm' (SAME
    optimized/final geometry production_areas below uses, not the raw
    'polygon_utm'), still HARD-excluded (buffered). production_areas is
    production_area_ceiling.identify_optimized_production_areas()'s own
    'scored_patches' -- the OPTIMIZED/final, ceiling-trimmed patch shape
    (each entry carrying 'render_fill_polygon_utm') -- but is NOT a hard
    exclusion here — see module docstring's "SOFT cost preference" section
    and build_cost_raster()'s PRODUCTION_CROSSING_COST_PENALTY.
    hydric_floodplain_union is a shapely geometry (or None to skip that
    exclusion) already in dem['crs'], still HARD-excluded.

    road_union_utm is a shapely geometry (or None) of existing real,
    NAMED roads only, used both for destination selection (see
    _select_destination_cells()) and for anchoring (see
    _anchor_to_boundary) — passing None doesn't disable anything here, it
    just means destination search falls straight to the boundary-adjacent
    tier and every candidate is returned with no connector segment at all
    (anchor_status="no_named_road_available") rather than reaching the
    boundary. road_features_utm (optional, each {'name': str, 'line_utm':
    LineString}) additionally lets an anchored candidate report WHICH real
    road it anchored to (properties.anchor_road_name); omitting it still
    anchors correctly via road_union_utm, it just leaves the road name
    generic.

    boundary_polygon_utm does double duty: it's both the anchoring target
    (_anchor_to_boundary) AND, via _build_exclusion_cell_mask(), the hard
    limit on which DEM cells routing can draw from at all — the DEM covers
    ~100m past the drawn boundary on purpose (dem_data.py), but a
    corridor's own candidate geometry must come from on-parcel cells only.
    The single connector segment _anchor_to_boundary() adds to reach the
    boundary line, when a named road is available to anchor to, is the one
    already-disclosed exception (see anchor_status and its confidence_notes
    caveat) — it's added AFTER this exclusion, not subject to it.

    Returns up to max_candidates entries, ranked by ascending total_cost
    (cheapest first):
        {
            'rank': int,
            'suitability_score': float,      # 0-100
            'avg_grade_pct': float,
            'length_m': float,
            'anchor_status': 'connected_to_named_road' | 'no_named_road_available',
            'anchor_road_name': Optional[str],       # None if no named road available
            'anchor_road_distance_m': Optional[float],  # None if no named road available
            'crosses_production_zone': bool,
            'points_xyz': [(x, y, elevation_m), ...],
            'geometry_wgs84': GeoJSON LineString,
        }
    """
    slope_pct, _aspect_deg = compute_slope_and_aspect(dem["array"], dem["resolution_meters"])

    # Production zones are NOT a hard exclusion here (see module
    # docstring) -- raw_production_union (unbuffered) feeds both
    # build_cost_raster()'s production_mask (a cost PENALTY, via
    # _build_production_cell_mask()) and the post-hoc
    # crosses_production_zone report below, never the exclusion mask that
    # HARD-limits where candidate geometry can be generated from. Scored
    # against render_fill_polygon_utm -- the OPTIMIZED/final production
    # geometry production_area_ceiling.py's own ceiling trim and
    # clustering already settled on for this property, not the raw
    # pre-optimization polygon_utm.
    raw_production_union = (
        unary_union([p["render_fill_polygon_utm"] for p in production_areas]) if production_areas else None
    )

    pond_union = (
        selected_water_zone["render_fill_polygon_utm"].buffer(POND_ZONE_EXCLUSION_BUFFER_METERS)
        if selected_water_zone is not None
        else None
    )

    exclusion_pieces = [
        u for u in (pond_union, hydric_floodplain_union)
        if u is not None and not u.is_empty
    ]
    combined_exclusion_union = unary_union(exclusion_pieces) if exclusion_pieces else None
    excluded_prepared = prep(combined_exclusion_union) if combined_exclusion_union is not None else None
    boundary_prepared = prep(boundary_polygon_utm)
    excluded_mask = _build_exclusion_cell_mask(dem, excluded_prepared, boundary_prepared)

    production_prepared = (
        prep(raw_production_union) if raw_production_union is not None and not raw_production_union.is_empty else None
    )
    production_mask = _build_production_cell_mask(dem, production_prepared, boundary_prepared)

    cost_raster = build_cost_raster(dem, slope_pct, excluded_mask, max_grade_pct, production_mask=production_mask)
    eligible_mask = np.isfinite(cost_raster)

    source_cells = _select_quadrant_source_cells(dem, eligible_mask, boundary_polygon_utm)
    destination_cells = _select_destination_cells(dem, eligible_mask, boundary_polygon_utm, road_union_utm)

    if not source_cells or not destination_cells:
        return []

    scored = []
    for source_cell in source_cells:
        # One call per source cell -- each quadrant gets its own
        # independent candidate route rather than every quadrant
        # collapsing onto a single combined cheapest-overall path. Every
        # destination candidate still goes into this one call together
        # (Dijkstra's own ascending-cost pop order finds the cheapest of
        # them without needing a separate call per destination).
        result = least_cost_path(dem, cost_raster, [source_cell], destination_cells)
        if result is None or len(result["cells"]) < 2:
            # A quadrant's source cell can itself already qualify as a
            # destination (e.g. a source near a corner that's also within
            # ROAD_BOUNDARY_ADJACENT_METERS of the boundary) -- a real,
            # valid least_cost_path() outcome, not an error, but a
            # single-cell path has no length/direction to form a
            # LineString from at all, so it's dropped here the same way
            # min_corridor_length_meters below drops any other "not a
            # meaningful road" candidate.
            continue

        points = path_cells_to_points_xyz(dem, result["cells"])
        anchored_points, anchor_status, anchor_road_name, anchor_road_distance_m = _anchor_to_boundary(
            points, boundary_polygon_utm, road_union_utm, road_features_utm
        )
        line = LineString([(p[0], p[1]) for p in anchored_points])

        length_m = line.length
        if length_m < min_corridor_length_meters:
            continue

        avg_grade_pct, _grade_stddev_pct = _grade_stats(anchored_points)
        crosses_production_zone = raw_production_union is not None and line.intersects(raw_production_union)

        scored.append(
            {
                "points_xyz": anchored_points,
                "line_utm": line,
                "total_cost": result["total_cost"],
                "length_m": length_m,
                "avg_grade_pct": avg_grade_pct,
                "crosses_production_zone": crosses_production_zone,
                "anchor_status": anchor_status,
                "anchor_road_name": anchor_road_name,
                "anchor_road_distance_m": anchor_road_distance_m,
            }
        )

    if not scored:
        return []

    scored.sort(key=lambda c: c["total_cost"])
    scored = scored[:max_candidates]

    max_total_cost = max(c["total_cost"] for c in scored)
    for candidate in scored:
        # 100 * (1 - total_cost / max_total_cost): the cheapest candidate
        # in THIS batch scores highest, the most expensive scores 0 --
        # a simple normalization for continuity with existing report/
        # render code that expects a 0-100 suitability_score, not a
        # separate weighted composite the way corridor ranking used to
        # work. Guaranteed in [0, 100] since total_cost <= max_total_cost
        # for every candidate by construction; clamped anyway as a
        # defensive floor/ceiling against floating-point edge cases.
        score = 100.0 * (1.0 - candidate["total_cost"] / max_total_cost) if max_total_cost > 0 else 100.0
        candidate["suitability_score"] = max(0.0, min(100.0, score))

    for rank, candidate in enumerate(scored, start=1):
        candidate["rank"] = rank
        xs = [p[0] for p in candidate["points_xyz"]]
        ys = [p[1] for p in candidate["points_xyz"]]
        lons, lats = warp_transform(dem["crs"], "EPSG:4326", xs, ys)
        candidate["geometry_wgs84"] = {"type": "LineString", "coordinates": list(zip(lons, lats))}

    return scored


def select_optimal_road_corridor(scored_candidates: list[dict]) -> Optional[dict]:
    """
    Explicit selection step on top of find_candidate_road_corridors()'s own
    ranking: returns the single candidate with rank == 1 (highest
    suitability_score) -- no logic beyond that. Same pattern as
    water_suitability.select_optimal_water_zone(); per product decision,
    this app targets small farms only, where one well-suited road corridor
    is sufficient -- no multi-candidate coexistence logic is needed here.

    Returns None if scored_candidates is empty -- a real, reportable "no
    candidates at all" outcome, not an error.
    """
    if not scored_candidates:
        return None
    return max(scored_candidates, key=lambda c: c["suitability_score"])


def _confidence_notes_for_candidate(
    anchor_status: AnchorStatus,
    anchor_road_name: Optional[str],
    floodplain_data_is_fallback: bool,
    avg_grade_pct: float,
    crosses_production_zone: bool,
) -> str:
    if anchor_status == "connected_to_named_road":
        if anchor_road_name:
            anchor_note = f"the point on the property boundary nearest {anchor_road_name} (a real, mapped existing road)"
        else:
            anchor_note = "the point on the property boundary nearest a real, mapped existing road"
        connector_note = (
            f"The final segment connecting the corridor to the property is a straight-line "
            f"approximation to {anchor_note}, and that connecting segment specifically is NOT "
            f"itself checked against the grade or exclusion constraints the rest of the corridor "
            f"is. "
        )
    else:
        connector_note = (
            "No connector segment was added to reach the property boundary: no real, named "
            "mapped road was found nearby to anchor to, and this candidate is NOT anchored to "
            "an arbitrary boundary point instead. The corridor's own interior geometry below is "
            "still real, DEM-derived routing — it simply doesn't reach the property line. "
        )

    production_crossing_note = PRODUCTION_CROSSING_NOTE if crosses_production_zone else ""

    steep_grade_note = (
        STEEP_GRADE_ENGINEERING_NOTE.format(
            avg_grade_pct=round(avg_grade_pct, 1), threshold_pct=STEEP_GRADE_ENGINEERING_NOTE_THRESHOLD_PCT
        )
        if avg_grade_pct > STEEP_GRADE_ENGINEERING_NOTE_THRESHOLD_PCT
        else ""
    )
    floodplain_note = (
        "Floodplain/wet-ground exclusion used a DEM-only fallback (buffered delineated valley "
        "lines), not real NHD/SSURGO data, because that data wasn't available for this run. "
        if floodplain_data_is_fallback
        else ""
    )
    return ROAD_CORRIDOR_CONFIDENCE_NOTES_TEMPLATE.format(
        connector_note=connector_note,
        production_crossing_note=production_crossing_note,
        steep_grade_note=steep_grade_note,
        floodplain_note=floodplain_note,
    )


def corridors_to_geojson(
    candidates: list[dict],
    floodplain_data_is_fallback: bool = False,
) -> dict:
    """Wraps find_candidate_road_corridors() output as the schema-
    conformant GeoJSON FeatureCollection this feature delivers
    (layer="suggested_road_corridor")."""
    features = []
    for candidate in candidates:
        constraints_satisfied = [
            "outside_pond_zone",
            f"avg_grade<={MAX_ROAD_GRADE_PCT:.0f}pct",
        ]
        if not floodplain_data_is_fallback:
            constraints_satisfied.append("floodplain_hydric_excluded_via_nhd_ssurgo")
        else:
            constraints_satisfied.append("floodplain_excluded_via_elevation_fallback")

        anchor_road_distance_ft = (
            round(candidate["anchor_road_distance_m"] / METERS_PER_FOOT, 1)
            if candidate.get("anchor_road_distance_m") is not None
            else None
        )

        features.append(
            make_feature(
                feature_id=f"road-corridor-{candidate['rank']}",
                geometry=candidate["geometry_wgs84"],
                layer="suggested_road_corridor",
                label=f"Suggested road corridor (rank {candidate['rank']})",
                confidence=CONFIDENCE_LOW,
                confidence_notes=_confidence_notes_for_candidate(
                    candidate["anchor_status"],
                    candidate.get("anchor_road_name"),
                    floodplain_data_is_fallback,
                    candidate["avg_grade_pct"],
                    candidate["crosses_production_zone"],
                ),
                extra_properties={
                    "rank": candidate["rank"],
                    "suitability_score": round(candidate["suitability_score"], 1),
                    "avg_grade_pct": round(candidate["avg_grade_pct"], 1),
                    "length_ft": round(candidate["length_m"] / METERS_PER_FOOT, 1),
                    "anchor_status": candidate["anchor_status"],
                    "anchor_road_name": candidate.get("anchor_road_name"),
                    "anchor_road_distance_ft": anchor_road_distance_ft,
                    "crosses_production_zone": candidate["crosses_production_zone"],
                    "constraints_satisfied": constraints_satisfied,
                },
            )
        )

    return make_feature_collection(features)


def _log_fetch_failure(label: str, exc: Exception) -> None:
    """
    Every real-data fetch in this module degrades gracefully on failure
    (see the module docstring), but "gracefully" shouldn't mean "silently
    identical whether the cause was a transient network timeout or a real
    bug in the query itself." A 4xx HTTP status means the server rejected
    the REQUEST as malformed (bad SQL, a column/table that doesn't exist)
    — that will fail exactly the same way on every future run, unlike a
    timeout or connection error, which might not. Anything that isn't
    even a requests error (a KeyError from an unexpected response shape,
    etc.) is just as clearly a real bug, not network flakiness. Print a
    distinct message for each case so this doesn't look like ordinary
    network unavailability in the logs — this is exactly how
    soil_data.get_erosion_factor_for_polygon()'s chorizon/component schema
    bug (from this module's now-removed erosion-avoidance preference) went
    unnoticed for a while: it degraded identically to "SDA is slow today."
    """
    if isinstance(exc, requests.exceptions.RequestException):
        status = getattr(getattr(exc, "response", None), "status_code", None)
        if status is not None and 400 <= status < 500:
            print(
                f"  {label}: request rejected by the server (HTTP {status}) — likely a real "
                f"query/schema bug, not transient network unavailability: {exc}"
            )
        else:
            print(f"  {label}: network request failed ({exc}), continuing without it.")
    else:
        print(f"  {label}: unexpected failure, not a network error ({type(exc).__name__}: {exc}).")


def _fetch_floodplain_hydric_union(
    boundary_coordinates, dem, valleys, boundary_polygon_utm
) -> tuple[Optional[object], bool]:
    """NHD stream/water-body buffers + SSURGO hydric soil polygons,
    unioned; falls back to buffering the already-computed delineated
    valley lines (an elevation-only proxy) only if BOTH real sources are
    unreachable. Returns (union_or_None, is_fallback).

    Each fetched NHD feature is clipped to a generous context region
    around boundary_polygon_utm (FLOODPLAIN_FETCH_CONTEXT_BUFFER_METERS)
    BEFORE being buffered into the union — see that constant's own
    comment for the real bug this fixes: NHD's query returns each
    matching feature's full, un-clipped geometry, so a stream or
    waterbody merely touching the (already-buffered) fetch bounding box
    could come back with geometry extending far past the property,
    ballooning the resulting exclusion union to many times the parcel's
    own size. The SSURGO hydric piece needs no equivalent clip here — it
    already comes back clipped to the parcel's own wkt_polygon from
    get_soil_geometries_for_polygon() itself (STIntersection), so it can
    never exceed the parcel's own area in the first place.

    A mukey only contributes its hydric geometry here if its SUMMED hydric
    component percentage meets soil_data.MIN_HYDRIC_COMPONENT_PCT_TO_EXCLUDE
    (soil_data.hydric_disqualifying_mukeys()) — a real, second bug found
    live alongside the NHD-clipping one above: a map unit that's 99%+
    well/moderately-well-drained but has a single 1%-of-composition hydric
    component was previously flagged the SAME as a map unit that's 85%+
    hydric, and its entire (much larger) mapped polygon got excluded right
    alongside genuinely wet ground. See that constant's own comment for the
    live numbers this fixes.

    Each fetched NHD feature's BUFFERED piece is additionally intersected
    against boundary_polygon_utm.buffer(FLOODPLAIN_FINAL_RELEVANCE_BUFFER_METERS)
    before being added to the union — see that constant's own comment for
    the THIRD bug this fixes: the fetch-context clip above bounds each raw
    stream feature before it's buffered, but nothing previously bounded
    the result AFTER buffering, so the buffer stroke (and however much
    stream length survived the looser fetch-context clip) could still
    produce a final piece extending well past any distance actually
    relevant to this parcel. Confirmed live: an 11.2-acre union of which
    only 0.077 acres (0.6%) actually overlapped the real parcel — a long
    buffered band along Montour Run, entirely on the far side of N Montour
    Rd from the field. This clip is scoped to the NHD stream/water-body
    piece only, same as the fetch-context clip above — the SSURGO hydric
    piece and the elevation-only valley fallback below are left untouched
    by it: the hydric piece is already bounded to the parcel's own
    wkt_polygon via STIntersection (get_soil_geometries_for_polygon()), a
    strict subset of any buffer around the parcel, so an additional clip
    there would be a redundant no-op in practice; the valley fallback is
    likewise much less exposed to this bug (the DEM itself only extends
    ~100m past the boundary to begin with) and isn't part of what this fix
    targets.
    """
    context_region = boundary_polygon_utm.buffer(FLOODPLAIN_FETCH_CONTEXT_BUFFER_METERS)
    final_relevance_region = boundary_polygon_utm.buffer(FLOODPLAIN_FINAL_RELEVANCE_BUFFER_METERS)
    pieces = []

    try:
        water_features = get_water_features_for_boundary(boundary_coordinates)
        for feature in water_features["streams"] + water_features["water_bodies"]:
            geometry = feature.get("geometry")
            if geometry is None:
                continue
            utm_geometry = shape(transform_geom("EPSG:4326", dem["crs"], geometry))
            clipped_geometry = utm_geometry.intersection(context_region)
            if clipped_geometry.is_empty:
                continue
            buffered_geometry = clipped_geometry.buffer(FLOODPLAIN_STREAM_BUFFER_METERS)
            relevant_geometry = buffered_geometry.intersection(final_relevance_region)
            if relevant_geometry.is_empty:
                continue
            pieces.append(relevant_geometry)
    except Exception as e:
        _log_fetch_failure("NHD stream/water-body fetch", e)

    try:
        wkt_polygon = coordinates_to_wkt_polygon(boundary_coordinates)
        soil_components = get_soil_data_for_polygon(wkt_polygon)
        hydric_mukeys = hydric_disqualifying_mukeys(soil_components)
        if hydric_mukeys:
            geometries_by_mukey = get_soil_geometries_for_polygon(wkt_polygon)
            for mukey in hydric_mukeys:
                geometry = geometries_by_mukey.get(mukey)
                if geometry is not None:
                    pieces.append(shape(transform_geom("EPSG:4326", dem["crs"], geometry)))
    except Exception as e:
        _log_fetch_failure("SSURGO hydric soil fetch", e)

    if pieces:
        return unary_union(pieces), False

    # Fallback: neither NHD nor SSURGO reachable -- use the valley network
    # already computed for pond-zone identification as a coarse,
    # elevation-only "probably wet ground follows drainage lines" proxy.
    fallback_pieces = []
    for valley in valleys:
        for branch in valley["branches_utm"]:
            line = LineString([(p[0], p[1]) for p in branch])
            fallback_pieces.append(line.buffer(FLOODPLAIN_STREAM_BUFFER_METERS))

    return (unary_union(fallback_pieces) if fallback_pieces else None), True


def _fetch_existing_road_features_utm(boundary_coordinates, dem) -> Optional[list[dict]]:
    """Real existing-road geometry WITH names (each {'name': str,
    'line_utm': LineString}), for anchor-road reporting (see
    _anchor_to_boundary's road_features_utm param and module docstring's
    "Corridor anchoring" section) — returns None on any failure, if
    nothing is nearby, or if nothing NAMED is nearby.

    Filters out entries whose name is exactly "Unnamed road" — the exact
    fallback label get_farm_roads_for_boundary() assigns when a fetched
    feature has no name/fullname field of its own (farm_roads_data.py,
    untouched — that fallback label is a real, deliberate default there for
    OTHER consumers, e.g. get_farm_roads_geojson()'s diagnostic layer; it's
    simply not a plausible thing to anchor a corridor connector to by name).
    A candidate is anchored to a NAMED real road or not anchored at all —
    see module docstring's "Corridor anchoring" section and
    _anchor_to_boundary(). Zero roads fetched and zero NAMED roads fetched
    both return None here, so downstream anchoring treats them identically."""
    try:
        roads = get_farm_roads_for_boundary(boundary_coordinates)
    except Exception as e:
        _log_fetch_failure("Existing road fetch", e)
        return None

    if not roads:
        return None

    named_roads = [road for road in roads if road["name"] != "Unnamed road"]
    if not named_roads:
        return None

    features = []
    for road in named_roads:
        geometry = road["geometry"]
        line_lists = geometry["coordinates"] if geometry["type"] == "MultiLineString" else [geometry["coordinates"]]
        for line in line_lists:
            xs, ys = warp_transform("EPSG:4326", dem["crs"], [p[0] for p in line], [p[1] for p in line])
            features.append({"name": road["name"], "line_utm": LineString(zip(xs, ys))})

    return features if features else None


def identify_road_corridor_candidates(
    boundary_coordinates: list[tuple[float, float]],
    dem: Optional[dict] = None,
    **corridor_kwargs,
) -> dict:
    """
    Full pipeline entry point: fetches/derives everything
    find_candidate_road_corridors() needs (optimized production areas,
    the single selected water zone, floodplain/hydric exclusion, existing
    roads for anchoring) and returns the "suggested_road_corridor"
    GeoJSON FeatureCollection. Every real-data fetch degrades
    independently and gracefully, same pattern as
    water_candidate_zones.py and solar_suitability.py.

    Returns:
        {
            'zones_geojson': dict,                       # every scored candidate, ranked
            'all_scored_candidates': list[dict],         # find_candidate_road_corridors()'s own
                                                            # raw scored list (carries line_utm)
            'selected_road_corridor': Optional[dict],    # select_optimal_road_corridor()'s single
                                                            # rank-1 answer, or None if no candidates exist
        }
    """
    if dem is None:
        dem = get_dem_for_boundary(boundary_coordinates)

    boundary_xs, boundary_ys = warp_transform(
        "EPSG:4326",
        dem["crs"],
        [pt[0] for pt in boundary_coordinates],
        [pt[1] for pt in boundary_coordinates],
    )
    boundary_polygon_utm = Polygon(zip(boundary_xs, boundary_ys))

    # Optimized/final production geometry (production_area_ceiling.py's
    # own ceiling-trimmed, clustered/gated result) -- NOT production_area.
    # identify_production_areas()'s raw pre-optimization patches. Each
    # patch is expected to carry 'render_fill_polygon_utm' (production_
    # area.py's own render-only convex-hull field), the same field
    # find_candidate_road_corridors() scores production avoidance against
    # below; fail loudly here rather than let a KeyError surface deep
    # inside that scoring code if this pipeline's own patch shape ever
    # changes.
    production_areas = identify_optimized_production_areas(boundary_coordinates, dem=dem)["scored_patches"]
    if production_areas and "render_fill_polygon_utm" not in production_areas[0]:
        raise RuntimeError(
            "identify_optimized_production_areas()'s scored_patches no longer carry "
            "'render_fill_polygon_utm' -- road_corridors.py's production-avoidance scoring "
            "depends on this field; update find_candidate_road_corridors() to match the new shape."
        )

    valleys = delineate_valleys(dem)  # reused for the floodplain fallback below

    # The single water zone this property's OWN water-suitability scoring
    # actually selected (rank 1), not every unscored candidate zone
    # water_candidate_zones.py generates -- see module docstring.
    selected_water_zone = fetch_and_select_optimal_water_zone(boundary_coordinates, dem=dem)

    hydric_floodplain_union, floodplain_data_is_fallback = _fetch_floodplain_hydric_union(
        boundary_coordinates, dem, valleys, boundary_polygon_utm
    )

    # One fetch (not two): _fetch_existing_road_features_utm() carries
    # both the per-feature list (for anchor_road_name reporting) and
    # everything needed to derive the plain union find_candidate_road_corridors()
    # actually anchors against -- deriving the union locally here avoids
    # a second, redundant get_farm_roads_for_boundary() call.
    road_features_utm = _fetch_existing_road_features_utm(boundary_coordinates, dem)
    road_union_utm = unary_union([f["line_utm"] for f in road_features_utm]) if road_features_utm else None

    candidates = find_candidate_road_corridors(
        dem,
        production_areas,
        selected_water_zone,
        boundary_polygon_utm,
        hydric_floodplain_union=hydric_floodplain_union,
        road_union_utm=road_union_utm,
        road_features_utm=road_features_utm,
        **corridor_kwargs,
    )

    return {
        "zones_geojson": corridors_to_geojson(
            candidates,
            floodplain_data_is_fallback=floodplain_data_is_fallback,
        ),
        "all_scored_candidates": candidates,
        "selected_road_corridor": select_optimal_road_corridor(candidates),
    }


def fetch_and_select_optimal_road_corridor(
    boundary_coordinates: list[tuple[float, float]],
    dem: Optional[dict] = None,
    **corridor_kwargs,
) -> Optional[dict]:
    """
    Convenience wrapper for callers (e.g. render_layout_map.py) that want
    a single best suggested road corridor rather than the full ranked
    FeatureCollection -- identify_road_corridor_candidates() already
    returns candidates rank-ordered best-first (feature 0 = rank 1), so
    this just returns that top GeoJSON Feature (or None if nothing
    cleared the constraint stack). Selects nothing new -- it picks the #1
    entry an existing, unchanged ranking already produced.
    """
    result = identify_road_corridor_candidates(boundary_coordinates, dem=dem, **corridor_kwargs)
    features = result["zones_geojson"]["features"]
    return features[0] if features else None


def summarize_road_corridor_candidates(result: dict) -> str:
    features = result["zones_geojson"]["features"]
    if not features:
        return "No suggested road corridor candidates identified (nothing cleared the constraint stack)."

    lines = [f"Suggested road corridor candidates: {len(features)}"]
    for feature in features:
        props = feature["properties"]
        if props.get("anchor_status") == "no_named_road_available":
            anchor = " [no named road nearby — no connector segment]"
        elif props.get("anchor_road_name"):
            anchor = f" [anchored to {props['anchor_road_name']}, {props.get('anchor_road_distance_ft')}ft]"
        else:
            anchor = " [anchored to a real road]"
        crossing = " [crosses production zone]" if props.get("crosses_production_zone") else ""
        lines.append(
            f"  - Rank {props['rank']}: score {props['suitability_score']}/100, "
            f"{props['avg_grade_pct']}% avg grade, {props['length_ft']}ft{anchor}{crossing}"
        )
    return "\n".join(lines)


if __name__ == "__main__":
    property_boundary = [
        (-79.9838154, 40.6458343),
        (-79.9836701, 40.6428581),
        (-79.9813665, 40.6440549),
        (-79.9804741, 40.6445667),
        (-79.9827466, 40.6458894),
        (-79.9838258, 40.6458343),
    ]

    print("Identifying suggested road corridor candidates for property boundary...\n")

    try:
        result = identify_road_corridor_candidates(property_boundary)
        print(summarize_road_corridor_candidates(result))
    except Exception as e:
        print(f"Request failed: {e}")
        print(
            "\nNote: this requires internet access to reach USGS's National "
            "Map services and USDA's Soil Data Access — not a fully "
            "sandboxed environment."
        )
