"""
road_corridors.py

Computes suggested road corridor geometry from the DEM, for properties
that lack existing farm road/access data — this REPLACES having Claude
infer a plausible-sounding corridor in prose during report generation
(report_generator.py's Farm Roads step used to do exactly that, with an
explicit "no dedicated access data" disclaimer). Same pattern as
water_candidate_zones.py and solar_suitability.py: the backend computes
real geometry, Claude narrates from the result.

Two corridor types, generated independently and ranked together (no
hardcoded type preference — see find_candidate_road_corridors()):

  CONTOUR-BAND: a road following a consistent elevation band along a
  slope, minimizing grade change. Generated by slicing the DEM's
  elevation range into narrow bands, keeping only low-slope/unexcluded
  cells within each band, and extracting a centerline through each
  resulting patch via PCA + binned-median thinning (a road doesn't need
  every eligible cell, just a clean path through the middle of them).

  RIDGE-TOP: a road following a ridge line. Ridges are extracted by
  reusing valley_delineation.py's own D8 flow-routing algorithm (fill ->
  flow direction -> flow accumulation -> threshold -> trace) against an
  INVERTED DEM — a standard GIS technique: a ridge in the real terrain is
  a valley in its negation. This deliberately reuses valley_delineation's
  public delineate_valleys() rather than reimplementing flow routing;
  see that module for the algorithm itself (untouched here).

Constraint stack (both corridor types, before scoring):
  - outside identified production zones (production_area.py, buffered)
  - outside pond/water-system candidate zones (water_candidate_zones.py,
    buffered wider — routing on the uphill side of a pond/dam, not across
    its face or catchment inlet)
  - outside floodplain/hydric ground, sourced from real NHD stream/water-
    body buffers + SSURGO hydric soil polygons (NOT inferred from DEM
    elevation alone) — falls back to a buffer around delineated valley
    lines only if neither NHD nor SSURGO data is reachable, and flags
    that fallback explicitly in confidence_notes
  - outside erosion-prone soil per SSURGO's K-factor (see
    soil_data.is_erosion_prone for the threshold and its caveats)
  - within a pinned maximum grade (MAX_ROAD_GRADE_PCT)

find_candidate_road_corridors() is the pure geometric/scoring core — see
water_candidate_zones.py's and solar_suitability.py's docstrings for why
this split matters (independently testable against a synthetic DEM,
without any of the several real network fetches this feature depends on).
"""

import math
from typing import Optional

import numpy as np
from rasterio.warp import transform as warp_transform
from rasterio.warp import transform_geom
from shapely.geometry import LineString, Point, Polygon, shape
from shapely.ops import nearest_points, unary_union
from shapely.prepared import prep

from dem_data import get_dem_for_boundary
from farm_roads_data import get_farm_roads_for_boundary
from feature_schema import CONFIDENCE_LOW, make_feature, make_feature_collection
from hydrology_data import get_water_features_for_boundary
from production_area import identify_production_areas
from raster_grid import connected_components, pixel_center_xy
from soil_data import (
    coordinates_to_wkt_polygon,
    get_erosion_factor_for_polygon,
    get_soil_data_for_polygon,
    get_soil_geometries_for_polygon,
    is_erosion_prone,
    is_hydric,
)
from terrain_metrics import compute_slope_and_aspect
from valley_delineation import delineate_valleys
from water_candidate_zones import find_candidate_zones as find_pond_zones

METERS_PER_FOOT = 0.3048

# Maximum sustained grade for a suggested farm road corridor. Pinned, not
# left for Claude to pick contextually, per this feature's explicit
# requirement. 10% is a widely-cited practical ceiling for sustained grade
# on a low-volume gravel farm/ranch road in USDA NRCS and US Forest
# Service low-standard-road design guidance: below ~10% sustained, a
# gravel road is comfortably drivable/haulable and holds up to normal
# erosion/maintenance; short pitches above that (sometimes cited up to
# ~12-15%) are tolerated in the wild but push into the range where
# erosion control and vehicle traction become real problems for a
# "suggested corridor" meant to be broadly usable, not a knife-edge case.
# This is a commonly-cited rule-of-thumb figure, not a single pinned
# regulatory document — stated plainly since this environment has no live
# network access to verify a specific citation. CONFIGURABLE — replace
# with a site-specific/regulatory value if one applies to your property.
MAX_ROAD_GRADE_PCT = 10.0

# Vertical window (meters) defining one contour-band candidate. Narrow
# enough that a band's own elevation range doesn't dominate its grade
# (the grade constraint below does the real filtering; this just keeps
# each candidate confined to a genuinely consistent elevation, which is
# the actual definition of a "contour-band" corridor as opposed to any
# low-slope area regardless of elevation spread). CONFIGURABLE.
CONTOUR_BAND_WIDTH_METERS = 3.0

# Minimum cluster size (grid cells) for a contour-band patch to attempt a
# centerline extraction from at all -- too few points make PCA/binning
# meaningless. CONFIGURABLE.
MIN_CONTOUR_BAND_CELLS = 6

# Same contributing-area thresholds valley_delineation.py uses, applied
# instead to an INVERTED DEM (so "contributing area" here means "ridge
# crest prominence," the inverted-terrain analog) -- smaller than
# valley_delineation's own defaults since a road-worthy ridge doesn't need
# to be a major landform feature the way a "primary valley" does.
# CONFIGURABLE.
RIDGE_MIN_AREA_ACRES = 0.5
RIDGE_MIN_PRIMARY_AREA_ACRES = 1.0

# Buffer beyond a production zone's own footprint that a corridor must
# stay clear of -- route around, not through. CONFIGURABLE.
PRODUCTION_ZONE_EXCLUSION_BUFFER_METERS = 15.0

# Buffer beyond a pond/water-system candidate zone's own footprint --
# wider than the production-zone buffer, since this needs to keep a
# corridor off a dam face or catchment inlet, not just the pond footprint
# itself. CONFIGURABLE.
POND_ZONE_EXCLUSION_BUFFER_METERS = 25.0

# Buffer applied to NHD streams/water bodies (and, in the elevation-only
# fallback case, to delineated valley lines) as the floodplain/riparian
# exclusion. 30m (~100ft) is a commonly-used minimal riparian buffer
# rule of thumb, not a site-specific regulatory setback. CONFIGURABLE.
FLOODPLAIN_STREAM_BUFFER_METERS = 30.0

# Drop candidates shorter than this -- not a meaningful road.
# CONFIGURABLE.
MIN_CORRIDOR_LENGTH_METERS = 30.0

# Scoring weights (must sum to 1.0), in the priority order this feature's
# spec lists: grade consistency first, exclusion-zone avoidance second,
# length third ("shorter generally preferable, all else equal" -- the
# lightest weight of the three). CONFIGURABLE.
GRADE_SCORE_WEIGHT = 0.5
EXCLUSION_MARGIN_WEIGHT = 0.3
LENGTH_SCORE_WEIGHT = 0.2

# Clearance beyond the mandatory exclusion buffers at which extra margin
# stops adding more score -- avoids the length/margin score being
# dominated by one enormous outlier candidate. CONFIGURABLE.
EXCLUSION_MARGIN_REFERENCE_METERS = 50.0

# How many top-ranked candidates (both types combined) to return.
# CONFIGURABLE.
MAX_CANDIDATES = 5

ROAD_CORRIDOR_CONFIDENCE_NOTES_TEMPLATE = (
    "This is a TOPOGRAPHIC SUGGESTION only, not a surveyed road alignment — "
    "generated from DEM slope/ridge analysis (contour-band or ridge-top), "
    "not a civil engineering design. The final segment connecting the "
    "corridor to the property is a straight-line approximation to {anchor_note}, "
    "and that connecting segment specifically is NOT itself checked against "
    "the grade or exclusion constraints the rest of the corridor is. "
    "{floodplain_note}{erosion_note}Treat this as a starting point for a site "
    "visit and real survey, not a construction-ready alignment."
)


def _invert_dem(dem: dict) -> dict:
    return {**dem, "array": -dem["array"]}


def _build_exclusion_cell_mask(dem: dict, excluded_prepared) -> np.ndarray:
    """Per-cell boolean mask (True = excluded), built once by testing
    every valid cell center against the (prepared, unioned) exclusion
    geometry — reused across every contour band and ridge branch rather
    than re-testing point-in-polygon per band."""
    array = dem["array"]
    rows, cols = array.shape
    excluded = np.zeros((rows, cols), dtype=bool)
    if excluded_prepared is None:
        return excluded

    valid = ~np.isnan(array)
    for r in range(rows):
        for c in range(cols):
            if valid[r, c] and excluded_prepared.contains(Point(pixel_center_xy(dem, r, c))):
                excluded[r, c] = True
    return excluded


def _generate_contour_band_cell_groups(
    dem: dict,
    slope_pct: np.ndarray,
    excluded_mask: np.ndarray,
    max_grade_pct: float,
    band_width_meters: float,
    min_cells: int,
) -> list[list[tuple[int, int]]]:
    """Slices the DEM's elevation range into non-overlapping bands and
    returns every sufficiently-large connected, unexcluded, low-slope
    patch within each band as a raw cell list. A single band can
    legitimately produce more than one patch (e.g. terrain wrapping
    around a hill at the same elevation on two sides)."""
    array = dem["array"]
    valid = ~np.isnan(array)
    low_slope = (~np.isnan(slope_pct)) & (slope_pct <= max_grade_pct)
    eligible_base = valid & low_slope & (~excluded_mask)

    if not np.any(eligible_base):
        return []

    elevations = array[valid]
    min_elev, max_elev = float(np.min(elevations)), float(np.max(elevations))

    groups = []
    band_start = min_elev
    while band_start < max_elev:
        band_end = band_start + band_width_meters
        band_mask = eligible_base & (array >= band_start) & (array < band_end)
        if np.any(band_mask):
            labels, num_components = connected_components(band_mask)
            for component_id in range(num_components):
                cells = [(int(r), int(c)) for r, c in np.argwhere(labels == component_id)]
                if len(cells) >= min_cells:
                    groups.append(cells)
        band_start = band_end

    return groups


def _pca_centerline(
    cells: list[tuple[int, int]], dem: dict, target_point_spacing_m: Optional[float] = None
) -> Optional[list[tuple[float, float, float]]]:
    """Reduces an unordered blob of grid cells to an ordered centerline —
    the direction of greatest spatial variance (PCA on cell centers) is
    treated as the corridor's long axis, cells are binned along that
    axis, and each bin's median perpendicular position becomes one
    ordered path vertex. Returns None for a blob too small or too
    round/compact to represent a linear corridor at all."""
    if len(cells) < 3:
        return None

    array = dem["array"]
    px, py = dem["resolution_meters"]
    if target_point_spacing_m is None:
        target_point_spacing_m = max(px, py) * 2

    utm_xy = np.array([pixel_center_xy(dem, r, c) for r, c in cells])
    elevations = np.array([float(array[r, c]) for r, c in cells])

    centroid = utm_xy.mean(axis=0)
    centered = utm_xy - centroid

    cov = np.cov(centered.T)
    eigvals, eigvecs = np.linalg.eigh(cov)
    principal_axis = eigvecs[:, int(np.argmax(eigvals))]
    perpendicular_axis = np.array([-principal_axis[1], principal_axis[0]])

    projections = centered @ principal_axis
    perp = centered @ perpendicular_axis

    span = float(projections.max() - projections.min())
    if span < target_point_spacing_m:
        return None  # too compact along its own long axis to be a corridor

    num_bins = max(3, int(span / target_point_spacing_m))
    bin_edges = np.linspace(projections.min(), projections.max(), num_bins + 1)
    bin_indices = np.clip(np.digitize(projections, bin_edges[1:-1]), 0, num_bins - 1)

    points = []
    for b in range(num_bins):
        mask = bin_indices == b
        if not np.any(mask):
            continue
        median_perp = float(np.median(perp[mask]))
        median_proj = float(np.median(projections[mask]))
        xy = centroid + median_proj * principal_axis + median_perp * perpendicular_axis
        elevation = float(np.mean(elevations[mask]))
        points.append((float(xy[0]), float(xy[1]), elevation))

    return points if len(points) >= 2 else None


def _contiguous_valid_runs(
    branch_rowcol: list[tuple[int, int]],
    branch_utm_inverted: list[tuple[float, float, float]],
    slope_pct: np.ndarray,
    excluded_mask: np.ndarray,
    max_grade_pct: float,
) -> list[list[tuple[float, float, float]]]:
    """Same contiguous-run pattern as water_candidate_zones.py's
    _runs_of_qualifying_points: walks an already-ordered ridge branch and
    breaks it wherever a point fails the grade or exclusion check,
    keeping runs of at least 2 points. branch_utm_inverted carries the
    INVERTED-DEM elevation (see delineate_valleys() on the negated DEM in
    _generate_ridge_candidates); this negates it back to real elevation
    for the returned points."""
    runs = []
    current: list[tuple[float, float, float]] = []

    for (r, c), (x, y, inverted_elevation) in zip(branch_rowcol, branch_utm_inverted):
        ok = (
            not excluded_mask[r, c]
            and not np.isnan(slope_pct[r, c])
            and slope_pct[r, c] <= max_grade_pct
        )
        if ok:
            current.append((x, y, -inverted_elevation))
        else:
            if len(current) >= 2:
                runs.append(current)
            current = []

    if len(current) >= 2:
        runs.append(current)

    return runs


def _generate_ridge_candidate_runs(
    dem: dict,
    slope_pct: np.ndarray,
    excluded_mask: np.ndarray,
    max_grade_pct: float,
    min_area_acres: float,
    min_primary_area_acres: float,
) -> list[list[tuple[float, float, float]]]:
    """Ridge lines via valley_delineation.delineate_valleys() against an
    inverted DEM (see module docstring), trimmed to grade/exclusion-
    passing contiguous runs."""
    ridges = delineate_valleys(
        _invert_dem(dem),
        min_stream_area_acres=min_area_acres,
        min_primary_valley_area_acres=min_primary_area_acres,
    )

    runs = []
    for ridge in ridges:
        for branch_rowcol, branch_utm in zip(ridge["branches_rowcol"], ridge["branches_utm"]):
            runs.extend(
                _contiguous_valid_runs(branch_rowcol, branch_utm, slope_pct, excluded_mask, max_grade_pct)
            )
    return runs


def _anchor_to_boundary(
    points_xyz: list[tuple[float, float, float]],
    boundary_polygon_utm: Polygon,
    road_union_utm,
) -> tuple[list[tuple[float, float, float]], bool]:
    """Extends whichever end of the corridor is closer to the property
    boundary with one connecting vertex on the boundary line — snapped to
    the point nearest a real mapped road if road_union_utm is available
    (a genuine plausible frontage point), otherwise just the nearest
    boundary point (arbitrary, flagged via the returned bool)."""
    boundary_line = boundary_polygon_utm.boundary
    end_a = Point(points_xyz[0][0], points_xyz[0][1])
    end_b = Point(points_xyz[-1][0], points_xyz[-1][1])

    anchor_at_start = end_a.distance(boundary_line) <= end_b.distance(boundary_line)
    anchor_end = end_a if anchor_at_start else end_b

    if road_union_utm is not None:
        nearest_road_point = nearest_points(anchor_end, road_union_utm)[1]
        boundary_anchor_point = nearest_points(nearest_road_point, boundary_line)[1]
        is_arbitrary = False
    else:
        boundary_anchor_point = nearest_points(anchor_end, boundary_line)[1]
        is_arbitrary = True

    connector_elevation = points_xyz[0][2] if anchor_at_start else points_xyz[-1][2]
    connector = (float(boundary_anchor_point.x), float(boundary_anchor_point.y), connector_elevation)

    extended = [connector] + points_xyz if anchor_at_start else points_xyz + [connector]
    return extended, is_arbitrary


def _grade_stats(points_xyz: list[tuple[float, float, float]]) -> tuple[float, float]:
    grades = []
    for (x1, y1, z1), (x2, y2, z2) in zip(points_xyz, points_xyz[1:]):
        distance = math.hypot(x2 - x1, y2 - y1)
        if distance > 0:
            grades.append(abs(z2 - z1) / distance * 100.0)
    if not grades:
        return 0.0, 0.0
    return float(np.mean(grades)), float(np.std(grades))


def _corridor_score(
    avg_grade_pct: float,
    grade_stddev_pct: float,
    margin_m: float,
    length_m: float,
    longest_length_m: float,
    max_grade_pct: float,
) -> float:
    grade_score = max(0.0, 1.0 - avg_grade_pct / max_grade_pct)
    consistency_score = max(0.0, 1.0 - grade_stddev_pct / max_grade_pct)
    grade_consistency_score = 0.5 * grade_score + 0.5 * consistency_score

    margin_score = min(1.0, margin_m / EXCLUSION_MARGIN_REFERENCE_METERS)
    length_score = 1.0 - (length_m / longest_length_m) if longest_length_m > 0 else 1.0

    return (
        GRADE_SCORE_WEIGHT * grade_consistency_score
        + EXCLUSION_MARGIN_WEIGHT * margin_score
        + LENGTH_SCORE_WEIGHT * length_score
    )


def find_candidate_road_corridors(
    dem: dict,
    production_areas: list[dict],
    pond_zones: list[dict],
    boundary_polygon_utm: Polygon,
    hydric_floodplain_union=None,
    erosion_prone_union=None,
    road_union_utm=None,
    max_grade_pct: float = MAX_ROAD_GRADE_PCT,
    min_corridor_length_meters: float = MIN_CORRIDOR_LENGTH_METERS,
    max_candidates: int = MAX_CANDIDATES,
) -> list[dict]:
    """
    Pure geometric/scoring core — see module docstring for why this takes
    already-computed inputs (production/pond zones, floodplain/erosion
    exclusion unions, optional real-road union for anchoring) rather than
    fetching or delineating anything itself.

    pond_zones is water_candidate_zones.find_candidate_zones()'s own
    output shape (each entry carrying 'polygon_utm').
    hydric_floodplain_union/erosion_prone_union are shapely
    geometries (or None to skip that exclusion) already in dem['crs'].
    road_union_utm is a shapely geometry (or None) of existing real roads,
    used ONLY for anchoring (see _anchor_to_boundary) — passing None
    doesn't disable anything here, it just makes every candidate's
    boundary connection point arbitrary rather than road-frontage-based.

    Returns up to max_candidates entries, both corridor types ranked
    together, best-first:
        {
            'rank': int,
            'corridor_type': 'contour' | 'ridge',
            'suitability_score': float,      # 0-1
            'avg_grade_pct': float,
            'length_m': float,
            'connection_point_is_arbitrary': bool,
            'points_xyz': [(x, y, elevation_m), ...],
            'geometry_wgs84': GeoJSON LineString,
        }
    """
    slope_pct, _aspect_deg = compute_slope_and_aspect(dem["array"], dem["resolution_meters"])

    production_union = (
        unary_union([p["polygon_utm"].buffer(PRODUCTION_ZONE_EXCLUSION_BUFFER_METERS) for p in production_areas])
        if production_areas
        else None
    )
    pond_union = (
        unary_union([z["polygon_utm"].buffer(POND_ZONE_EXCLUSION_BUFFER_METERS) for z in pond_zones])
        if pond_zones
        else None
    )

    exclusion_pieces = [
        u for u in (production_union, pond_union, hydric_floodplain_union, erosion_prone_union)
        if u is not None and not u.is_empty
    ]
    combined_exclusion_union = unary_union(exclusion_pieces) if exclusion_pieces else None
    excluded_prepared = prep(combined_exclusion_union) if combined_exclusion_union is not None else None
    excluded_mask = _build_exclusion_cell_mask(dem, excluded_prepared)

    raw_candidates: list[tuple[list[tuple[float, float, float]], str]] = []

    for cells in _generate_contour_band_cell_groups(
        dem, slope_pct, excluded_mask, max_grade_pct, CONTOUR_BAND_WIDTH_METERS, MIN_CONTOUR_BAND_CELLS
    ):
        centerline = _pca_centerline(cells, dem)
        if centerline:
            raw_candidates.append((centerline, "contour"))

    for run in _generate_ridge_candidate_runs(
        dem, slope_pct, excluded_mask, max_grade_pct, RIDGE_MIN_AREA_ACRES, RIDGE_MIN_PRIMARY_AREA_ACRES
    ):
        raw_candidates.append((run, "ridge"))

    scored = []
    for points, corridor_type in raw_candidates:
        anchored_points, is_arbitrary = _anchor_to_boundary(points, boundary_polygon_utm, road_union_utm)
        line = LineString([(p[0], p[1]) for p in anchored_points])

        length_m = line.length
        if length_m < min_corridor_length_meters:
            continue

        avg_grade_pct, grade_stddev_pct = _grade_stats(anchored_points)
        margin_m = (
            line.distance(combined_exclusion_union)
            if combined_exclusion_union is not None
            else EXCLUSION_MARGIN_REFERENCE_METERS
        )

        scored.append(
            {
                "corridor_type": corridor_type,
                "points_xyz": anchored_points,
                "line_utm": line,
                "length_m": length_m,
                "avg_grade_pct": avg_grade_pct,
                "grade_stddev_pct": grade_stddev_pct,
                "margin_m": margin_m,
                "connection_point_is_arbitrary": is_arbitrary,
            }
        )

    if not scored:
        return []

    longest_length_m = max(c["length_m"] for c in scored)
    for candidate in scored:
        candidate["suitability_score"] = _corridor_score(
            candidate["avg_grade_pct"],
            candidate["grade_stddev_pct"],
            candidate["margin_m"],
            candidate["length_m"],
            longest_length_m,
            max_grade_pct,
        )

    scored.sort(key=lambda c: -c["suitability_score"])
    scored = scored[:max_candidates]

    for rank, candidate in enumerate(scored, start=1):
        candidate["rank"] = rank
        xs = [p[0] for p in candidate["points_xyz"]]
        ys = [p[1] for p in candidate["points_xyz"]]
        lons, lats = warp_transform(dem["crs"], "EPSG:4326", xs, ys)
        candidate["geometry_wgs84"] = {"type": "LineString", "coordinates": list(zip(lons, lats))}

    return scored


def _confidence_notes_for_candidate(
    is_arbitrary_anchor: bool, floodplain_data_is_fallback: bool, erosion_data_unavailable: bool
) -> str:
    anchor_note = (
        "an arbitrarily-chosen nearest point on the property boundary "
        "(no real road-frontage/access data was available to anchor to)"
        if is_arbitrary_anchor
        else "the point on the property boundary nearest a real, mapped existing road"
    )
    floodplain_note = (
        "Floodplain/wet-ground exclusion used a DEM-only fallback (buffered delineated valley "
        "lines), not real NHD/SSURGO data, because that data wasn't available for this run. "
        if floodplain_data_is_fallback
        else ""
    )
    erosion_note = (
        "Erosion-prone soil data (SSURGO K-factor) was not available for this run, so that "
        "exclusion was not applied. "
        if erosion_data_unavailable
        else ""
    )
    return ROAD_CORRIDOR_CONFIDENCE_NOTES_TEMPLATE.format(
        anchor_note=anchor_note, floodplain_note=floodplain_note, erosion_note=erosion_note
    )


def corridors_to_geojson(
    candidates: list[dict],
    floodplain_data_is_fallback: bool = False,
    erosion_data_unavailable: bool = False,
) -> dict:
    """Wraps find_candidate_road_corridors() output as the schema-
    conformant GeoJSON FeatureCollection this feature delivers
    (layer="suggested_road_corridor")."""
    features = []
    for candidate in candidates:
        constraints_satisfied = [
            "outside_production_zone",
            "outside_pond_zone",
            f"avg_grade<={MAX_ROAD_GRADE_PCT:.0f}pct",
        ]
        if not erosion_data_unavailable:
            constraints_satisfied.append("erosion_prone_soil_excluded")
        if not floodplain_data_is_fallback:
            constraints_satisfied.append("floodplain_hydric_excluded_via_nhd_ssurgo")
        else:
            constraints_satisfied.append("floodplain_excluded_via_elevation_fallback")

        features.append(
            make_feature(
                feature_id=f"road-corridor-{candidate['corridor_type']}-{candidate['rank']}",
                geometry=candidate["geometry_wgs84"],
                layer="suggested_road_corridor",
                label=f"Suggested {candidate['corridor_type']} road corridor (rank {candidate['rank']})",
                confidence=CONFIDENCE_LOW,
                confidence_notes=_confidence_notes_for_candidate(
                    candidate["connection_point_is_arbitrary"], floodplain_data_is_fallback, erosion_data_unavailable
                ),
                extra_properties={
                    "rank": candidate["rank"],
                    "suitability_score": round(candidate["suitability_score"] * 100, 1),
                    "corridor_type": candidate["corridor_type"],
                    "avg_grade_pct": round(candidate["avg_grade_pct"], 1),
                    "length_ft": round(candidate["length_m"] / METERS_PER_FOOT, 1),
                    "connection_point_is_arbitrary": candidate["connection_point_is_arbitrary"],
                    "constraints_satisfied": constraints_satisfied,
                },
            )
        )

    return make_feature_collection(features)


def _fetch_floodplain_hydric_union(boundary_coordinates, dem, valleys) -> tuple[Optional[object], bool]:
    """NHD stream/water-body buffers + SSURGO hydric soil polygons,
    unioned; falls back to buffering the already-computed delineated
    valley lines (an elevation-only proxy) only if BOTH real sources are
    unreachable. Returns (union_or_None, is_fallback)."""
    pieces = []

    try:
        water_features = get_water_features_for_boundary(boundary_coordinates)
        for feature in water_features["streams"] + water_features["water_bodies"]:
            geometry = feature.get("geometry")
            if geometry is None:
                continue
            utm_geometry = shape(transform_geom("EPSG:4326", dem["crs"], geometry))
            pieces.append(utm_geometry.buffer(FLOODPLAIN_STREAM_BUFFER_METERS))
    except Exception:
        pass

    try:
        wkt_polygon = coordinates_to_wkt_polygon(boundary_coordinates)
        soil_components = get_soil_data_for_polygon(wkt_polygon)
        hydric_mukeys = {c["mukey"] for c in soil_components if is_hydric(c.get("hydricrating"))}
        if hydric_mukeys:
            geometries_by_mukey = get_soil_geometries_for_polygon(wkt_polygon)
            for mukey in hydric_mukeys:
                geometry = geometries_by_mukey.get(mukey)
                if geometry is not None:
                    pieces.append(shape(transform_geom("EPSG:4326", dem["crs"], geometry)))
    except Exception:
        pass

    if pieces:
        return unary_union(pieces), False

    # Fallback: neither NHD nor SSURGO reachable -- use the valley network
    # already computed for pond-zone identification as a coarse,
    # elevation-only "probably wet ground follows drainage lines" proxy.
    fallback_pieces = []
    for valley in valleys:
        for branch in valley["branches_utm"]:
            line = LineString([(p[0], p[1]) for p in branch])
            fallback_pieces.append(line.buffer(FLOODPLAIN_STREAM_BUFFER_METERS))

    return (unary_union(fallback_pieces) if fallback_pieces else None), True


def _fetch_erosion_prone_union(boundary_coordinates, dem) -> tuple[Optional[object], bool]:
    """SSURGO K-factor-based erosion-prone soil union. Returns
    (union_or_None, data_unavailable) — data_unavailable is True only if
    the fetch itself failed, not if it succeeded and simply found no
    erosion-prone soil in the area."""
    try:
        wkt_polygon = coordinates_to_wkt_polygon(boundary_coordinates)
        erosion_rows = get_erosion_factor_for_polygon(wkt_polygon)
        erosion_prone_mukeys = {row["mukey"] for row in erosion_rows if is_erosion_prone(row.get("kwfact"))}
        if not erosion_prone_mukeys:
            return None, False

        geometries_by_mukey = get_soil_geometries_for_polygon(wkt_polygon)
        pieces = [
            shape(transform_geom("EPSG:4326", dem["crs"], geometries_by_mukey[mukey]))
            for mukey in erosion_prone_mukeys
            if mukey in geometries_by_mukey
        ]
        return (unary_union(pieces) if pieces else None), False
    except Exception:
        return None, True


def _fetch_existing_road_union(boundary_coordinates, dem):
    """Real existing-road geometry, for anchoring only (see
    _anchor_to_boundary) — returns None on any failure or if nothing is
    nearby, which just makes anchoring fall back to an arbitrary boundary
    point rather than raising."""
    try:
        roads = get_farm_roads_for_boundary(boundary_coordinates)
    except Exception:
        return None

    if not roads:
        return None

    pieces = []
    for road in roads:
        geometry = road["geometry"]
        line_lists = geometry["coordinates"] if geometry["type"] == "MultiLineString" else [geometry["coordinates"]]
        for line in line_lists:
            xs, ys = warp_transform("EPSG:4326", dem["crs"], [p[0] for p in line], [p[1] for p in line])
            pieces.append(LineString(zip(xs, ys)))

    return unary_union(pieces) if pieces else None


def identify_road_corridor_candidates(
    boundary_coordinates: list[tuple[float, float]],
    dem: Optional[dict] = None,
    **corridor_kwargs,
) -> dict:
    """
    Full pipeline entry point: fetches/derives everything
    find_candidate_road_corridors() needs (production zones, pond zones,
    floodplain/hydric exclusion, erosion-prone soil exclusion, existing
    roads for anchoring) and returns the "suggested_road_corridor"
    GeoJSON FeatureCollection. Every real-data fetch degrades
    independently and gracefully, same pattern as
    water_candidate_zones.py and solar_suitability.py.
    """
    if dem is None:
        dem = get_dem_for_boundary(boundary_coordinates)

    production_areas = identify_production_areas(dem)
    valleys = delineate_valleys(dem)  # reused for pond zones AND the floodplain fallback below

    boundary_xs, boundary_ys = warp_transform(
        "EPSG:4326",
        dem["crs"],
        [pt[0] for pt in boundary_coordinates],
        [pt[1] for pt in boundary_coordinates],
    )
    boundary_polygon_utm = Polygon(zip(boundary_xs, boundary_ys))

    pond_zones = find_pond_zones(valleys, production_areas, boundary_polygon_utm, dem["crs"])

    hydric_floodplain_union, floodplain_data_is_fallback = _fetch_floodplain_hydric_union(
        boundary_coordinates, dem, valleys
    )
    erosion_prone_union, erosion_data_unavailable = _fetch_erosion_prone_union(boundary_coordinates, dem)
    road_union_utm = _fetch_existing_road_union(boundary_coordinates, dem)

    candidates = find_candidate_road_corridors(
        dem,
        production_areas,
        pond_zones,
        boundary_polygon_utm,
        hydric_floodplain_union=hydric_floodplain_union,
        erosion_prone_union=erosion_prone_union,
        road_union_utm=road_union_utm,
        **corridor_kwargs,
    )

    return {
        "zones_geojson": corridors_to_geojson(
            candidates,
            floodplain_data_is_fallback=floodplain_data_is_fallback,
            erosion_data_unavailable=erosion_data_unavailable,
        )
    }


def summarize_road_corridor_candidates(result: dict) -> str:
    features = result["zones_geojson"]["features"]
    if not features:
        return "No suggested road corridor candidates identified (nothing cleared the constraint stack)."

    lines = [f"Suggested road corridor candidates: {len(features)}"]
    for feature in features:
        props = feature["properties"]
        anchor = " [arbitrary boundary anchor]" if props["connection_point_is_arbitrary"] else ""
        lines.append(
            f"  - Rank {props['rank']} ({props['corridor_type']}): score {props['suitability_score']}/100, "
            f"{props['avg_grade_pct']}% avg grade, {props['length_ft']}ft{anchor}"
        )
    return "\n".join(lines)


if __name__ == "__main__":
    property_boundary = [
        (-79.9838154, 40.6458343),
        (-79.9836701, 40.6428581),
        (-79.9813665, 40.6440549),
        (-79.9804741, 40.6445667),
        (-79.9827466, 40.6458894),
        (-79.9838258, 40.6458343),
    ]

    print("Identifying suggested road corridor candidates for property boundary...\n")

    try:
        result = identify_road_corridor_candidates(property_boundary)
        print(summarize_road_corridor_candidates(result))
    except Exception as e:
        print(f"Request failed: {e}")
        print(
            "\nNote: this requires internet access to reach USGS's National "
            "Map services and USDA's Soil Data Access — not a fully "
            "sandboxed environment."
        )
