"""
road_corridors.py

Computes suggested road route geometry from the DEM, for properties that
lack existing farm road/access data — this REPLACES having Claude infer a
plausible-sounding corridor in prose during report generation
(report_generator.py's Farm Roads step used to do exactly that, with an
explicit "no dedicated access data" disclaimer). Same pattern as
water_candidate_zones.py and solar_suitability.py: the backend computes
real geometry, Claude narrates from the result.

A route is generated by routing a least-cost path (road_cost_path.py —
see that module for the cost-raster/Dijkstra/k-shortest-paths core
itself, imported and used here, not reimplemented) from a single given
ANCHOR POINT (a real, chosen access point on or near the property — where
the property would actually connect to the outside world, e.g. a gate or
driveway location) to the farthest eligible point on the property:

  SOURCE: the anchor point (anchor_lon_lat), snapped to the nearest
  eligible cell (_snap_anchor_to_eligible_cell()) — the anchor itself
  might land on hard-excluded or off-parcel ground, so routing starts
  from wherever eligible ground is actually closest to it.

  DESTINATIONS: up to three candidate destinations, one per compass-ish
  "fan" direction radiating from the anchor (_select_fan_destination_
  cells()) — the primary axis toward boundary_polygon_utm's own centroid,
  plus that same axis rotated ±22.5°. Each direction casts a ray from the
  anchor far past the property's own extent and takes where it exits
  boundary_polygon_utm's exterior ring, snapped to the nearest eligible
  cell. This deliberately spreads candidate destinations across different
  REGIONS of the property (not just "the single farthest point," an
  earlier version of this module's approach, which only ever explores one
  direction) — a narrow/sliver-shaped parcel can still legitimately
  collapse two or three fan rays onto the same real destination, or drop
  a ray entirely if it produces no usable boundary crossing; this returns
  whatever survives, never fewer than genuinely exist and never padded.

  ROUTING: one road_cost_path.least_cost_path() call per fan destination
  (not a single k_shortest_paths() call the way an earlier version of
  this module worked) — each fan direction gets its own independent
  route. road_cost_path.k_shortest_paths() stays available in this
  codebase for a later prompt to layer route ALTERNATES within a single
  direction on top of this; it isn't called here at all right now.

  RANKING: routes are ranked by ascending total_cost (least_cost_path()'s
  own Dijkstra path cost — the running sum of grade- and floodplain-
  penalized edge weights along the route), not a separate weighted
  composite score. suitability_score is a simple normalization of that
  same total_cost against the most expensive route in this batch (100.0
  outright when only one route survives at all — there's no "most
  expensive route" to normalize against then), kept only for continuity
  with existing report/render code that expects a 0-100 score to display.

Constraint stack, current design — HARD exclusions (baked into
cost_raster as np.inf, a route genuinely cannot be generated through
these at all) vs. a SOFT cost preference (baked into cost_raster as a
finite penalty a route can still choose to pay):
  - HARD exclusions:
      - outside the single SELECTED water-system candidate zone
        (water_suitability.fetch_and_select_optimal_water_zone() — the
        one rank-1 zone this property's own water-suitability scoring
        actually picked, not every unscored candidate zone
        water_candidate_zones.py generates), buffered wider — routing on
        the uphill side of a pond/dam, not across its face or catchment
        inlet
      - production zone(s) (production_area_ceiling.py's own optimized/
        final geometry) — a road is no longer allowed to cross production
        land at all under the current design (see
        _build_production_cell_mask(), whose own output now gets folded
        into excluded_mask as a HARD exclusion, not a soft cost term the
        way an earlier version of this module used it)
  - SOFT cost preference:
      - floodplain/hydric ground, sourced from real NHD stream/water-body
        buffers + SSURGO hydric soil polygons (NOT inferred from DEM
        elevation alone) — falls back to a buffer around delineated
        valley lines only if neither NHD nor SSURGO data is reachable,
        and flags that fallback explicitly in confidence_notes. A route
        may still cross it when the alternative is a costly enough detour
        (road_cost_path.FLOODPLAIN_CROSSING_COST_PENALTY) — this was a
        HARD exclusion in an earlier version of this module.
      - grade — UNBOUNDED, via road_cost_path.build_cost_raster()'s own
        quadratic grade penalty; there is no pinned maximum-grade ceiling
        in this design at all anymore (an earlier version of this module
        hard-capped at MAX_ROAD_GRADE_PCT). A route can still climb an
        arbitrarily steep slope if the alternative is expensive enough,
        it just costs more per cell the steeper it gets.

Erosion-prone soil (SSURGO K-factor) is deliberately NOT part of this
module's constraint stack at all, hard or soft — this pipeline's own
KSOP (Keyline Scale of Permanence) ordering puts Soil at step 8, well
below Farm Roads at step 4; scoring a step-4 feature against step-8 data
inverted that ordering, so the erosion-avoidance preference this module
used to carry has been removed outright, not just softened further.

No named-road anchoring/connector search happens in this flow at all
(an earlier version of this module snapped the near-boundary end of a
generated corridor to the nearest real, named mapped road) — routing now
starts FROM a given real anchor point and ends at the farthest eligible
point, full stop; there's no separate "reach the boundary" step to
connect afterward. Severing a route at a structure site (once one has
been sited) is out of scope here too — a future follow-up once real
routes exist to sever.

find_road_routes() is the pure geometric/scoring core — see
water_candidate_zones.py's and solar_suitability.py's docstrings for why
this split matters (independently testable against a synthetic DEM,
without any of the several real network fetches this feature depends on).
"""

import math
from typing import Literal, Optional

import numpy as np
from rasterio.warp import transform as warp_transform
from rasterio.warp import transform_geom
from shapely.geometry import LineString, Point, Polygon, shape
from shapely.ops import unary_union
from shapely.prepared import prep
import requests

from dem_data import get_dem_for_boundary
from feature_schema import CONFIDENCE_LOW, make_feature, make_feature_collection
from hydrology_data import get_water_features_for_boundary
from production_area_ceiling import identify_optimized_production_areas
from raster_grid import pixel_center_xy
from road_cost_path import build_cost_raster, least_cost_path, path_cells_to_points_xyz
from soil_data import (
    coordinates_to_wkt_polygon,
    get_soil_data_for_polygon,
    get_soil_geometries_for_polygon,
    hydric_disqualifying_mukeys,
)
from terrain_metrics import compute_slope_and_aspect
from valley_delineation import delineate_valleys
from water_suitability import fetch_and_select_optimal_water_zone

METERS_PER_FOOT = 0.3048

# Historical reference figure only now, NOT an enforced hard ceiling
# anymore (see module docstring -- grade is an unbounded soft cost penalty
# under the current design, road_cost_path.build_cost_raster()'s own job).
# Kept purely as the documented "widely-cited practical ceiling" context
# STEEP_GRADE_ENGINEERING_NOTE_THRESHOLD_PCT's own reasoning below is
# expressed relative to. 10% is a widely-cited practical ceiling for
# sustained grade on a low-volume gravel farm/ranch road in USDA NRCS and
# US Forest Service low-standard-road design guidance; 15% reflects that
# short pitches up to ~12-15% are tolerated in the wild on low-volume
# farm/ranch roads. Not a single pinned regulatory document — stated
# plainly since this environment has no live network access to verify a
# specific citation.
MAX_ROAD_GRADE_PCT = 15.0

# Above this average grade, a route is steep enough that confidence_notes
# flags it as needing real engineering consideration (surface material,
# drainage/culverts, water bars) before construction -- not just the
# blanket "topographic suggestion, not a surveyed alignment" caveat every
# route already carries. Set at the OLD 10% ceiling (rather than some
# fraction of the 15% reference figure above): grade at or below what
# used to be the hard cutoff still reads as comfortably within normal
# gravel-road practice; anything above it is in the range this codebase's
# own MAX_ROAD_GRADE_PCT reasoning above already treats as "tolerated but
# needs real engineering attention," not a new/arbitrary line. CONFIGURABLE.
STEEP_GRADE_ENGINEERING_NOTE_THRESHOLD_PCT = 10.0

# Buffer beyond a pond/water-system candidate zone's own footprint -- this
# needs to keep a route off a dam face or catchment inlet, not just the
# pond footprint itself. CONFIGURABLE.
POND_ZONE_EXCLUSION_BUFFER_METERS = 25.0

# Buffer applied to NHD streams/water bodies (and, in the elevation-only
# fallback case, to delineated valley lines) as the floodplain/riparian
# cost-penalty region. 30m (~100ft) is a commonly-used minimal riparian
# buffer rule of thumb, not a site-specific regulatory setback.
# CONFIGURABLE.
FLOODPLAIN_STREAM_BUFFER_METERS = 30.0

# How far past the parcel boundary to still care about a fetched NHD
# stream/water-body's own geometry before it gets buffered into the
# floodplain cost-penalty union. REAL BUG, FOUND LIVE (fixed here):
# hydrology_data.py's NHD query (an ArcGIS `query` operation) returns
# each matching feature's FULL, un-clipped geometry for anything that
# merely intersects the query bounding box -- a long stream or a large
# waterbody that just touches that box can come back with geometry
# extending far past the property, which then got buffered (widening it
# further) and unioned into this mask WHOLESALE. Confirmed live: a
# 33.9-ACRE floodplain/hydric union on a 13.23-acre parcel. Same
# root-cause CATEGORY (a fetch returning geometry far beyond the input
# boundary's actual relevant extent, not clipped to it) as the earlier
# soil_data.get_soil_geometries_for_polygon() bug -- that one's already
# fixed at the SSURGO query itself (real STIntersects + STIntersection
# clipping); NHD's ArcGIS `query` endpoint has no equivalent server-side
# clip parameter here, so this clips CLIENT-SIDE instead, against a
# generous context region around the parcel -- comfortably larger than
# both dem_data.py's own ~100m DEM fetch buffer and
# FLOODPLAIN_STREAM_BUFFER_METERS itself, so clipping here can never cut
# off a stream segment that would otherwise matter to on-parcel routing.
# CONFIGURABLE.
FLOODPLAIN_FETCH_CONTEXT_BUFFER_METERS = 200.0

# SECOND real bug, found live AFTER the fetch-context clip above landed:
# that clip is applied to each stream/water-body feature's RAW geometry
# BEFORE it gets buffered by FLOODPLAIN_STREAM_BUFFER_METERS -- nothing
# bounded the geometry AFTER buffering, so the buffer stroke itself (and,
# more significantly, however much of the stream's length survived the
# 200m fetch-context clip) could still produce a final piece extending
# well past any distance actually relevant to this parcel. Confirmed live
# and visually (plotted GeoJSON against the real property): an 11.2-acre
# union where only 0.077 acres (0.6% of the parcel) actually overlapped
# it -- the rest was a long buffered band running along Montour Run,
# entirely on the far side of N Montour Rd from the field, nowhere near
# the parcel. This constant bounds the FINAL unioned/buffered result
# (after FLOODPLAIN_STREAM_BUFFER_METERS is applied) to a region tied to
# the parcel itself, independent of how far the original fetched geometry
# or its buffer stroke reached. Deliberately meaningfully SMALLER than
# FLOODPLAIN_FETCH_CONTEXT_BUFFER_METERS (200m) -- that larger buffer's
# job is only to avoid losing a stream segment's geometry at fetch time;
# this one's job is to bound what actually counts as "close enough to this
# parcel to matter." Still meaningfully LARGER than
# FLOODPLAIN_STREAM_BUFFER_METERS (30m) alone, so a stream running close
# to (but not quite touching) the parcel -- genuine near-parcel floodplain
# risk on a differently-shaped property -- doesn't get clipped away just
# because its own 30m buffer stroke doesn't quite reach the boundary.
# CONFIGURABLE.
FLOODPLAIN_FINAL_RELEVANCE_BUFFER_METERS = 75.0

# Drop routes shorter than this -- not a meaningful road. CONFIGURABLE.
MIN_CORRIDOR_LENGTH_METERS = 30.0

# Angular offset (degrees) of the two off-axis fan rays
# _select_fan_destination_cells() casts from the anchor, on either side
# of the primary anchor-to-centroid axis. A fixed spread, not (yet)
# informed by parcel shape/size. CONFIGURABLE, deliberately unvalidated
# starting value.
FAN_RAY_ANGLE_DEG = 22.5

# Multiplier applied to boundary_polygon_utm's own bounding-box diagonal
# to build each fan ray's length in _select_fan_destination_cells() --
# long enough that a ray cast from anywhere at or near the parcel
# (including a raster-snapped anchor sitting fractionally outside the
# true boundary polygon) is practically guaranteed to cross its exterior
# ring at least once, regardless of parcel shape or anchor placement.
# Not really a tuning knob the way the CONFIGURABLE constants above are --
# larger only costs a cheap extra bit of ray-geometry math, never changes
# behavior for a ray that already reaches the boundary.
FAN_RAY_LENGTH_DIAGONAL_MULTIPLIER = 3.0

FanDirection = Literal["primary", "left", "right"]

ROAD_CORRIDOR_CONFIDENCE_NOTES_TEMPLATE = (
    "This is a TOPOGRAPHIC SUGGESTION only, not a surveyed road alignment — "
    "generated from a DEM-based least-cost-path routing model (an unbounded "
    "grade penalty plus a floodplain cost surface — see road_cost_path.py), "
    "not a civil engineering design, routed from a single given anchor point "
    "to the farthest eligible point on the property. The single selected "
    "water-system candidate zone and production zone(s) are HARD-excluded — "
    "a route cannot be generated through either at all. Floodplain/hydric "
    "ground is a SOFT cost preference instead — a route may still cross it "
    "when the alternative is a costly enough detour (see "
    "properties.crosses_floodplain). {floodplain_crossing_note}"
    "{steep_grade_note}{floodplain_fallback_note}Treat this as a starting "
    "point for a site visit and real survey, not a construction-ready "
    "alignment."
)

FLOODPLAIN_CROSSING_NOTE = (
    "This specific route DOES cross floodplain/hydric ground — that's intentional/expected under "
    "this model, not a caveat to apologize for; the least-cost-path routing found crossing it was "
    "still cheaper overall than detouring around it. "
)

# Additive caveat (see STEEP_GRADE_ENGINEERING_NOTE_THRESHOLD_PCT above) —
# appended only for routes steep enough that routine grading isn't
# enough; the blanket "topographic suggestion" disclaimer above still
# applies to every route regardless of grade.
STEEP_GRADE_ENGINEERING_NOTE = (
    "This route's average grade ({avg_grade_pct}%) is steep enough for an unpaved farm road that "
    "real engineering consideration — surface material, drainage/culverts, water bars — is needed "
    "before construction, not just routine grading: erosion, traction, and washout risk all "
    "increase meaningfully above {threshold_pct:.0f}%, especially under heavy rainfall or "
    "freeze-thaw conditions. "
)


def _build_exclusion_cell_mask(dem: dict, excluded_prepared, boundary_prepared) -> np.ndarray:
    """Per-cell boolean mask (True = excluded), built once by testing
    every valid cell center against the (prepared, unioned) exclusion
    geometry AND against the real parcel boundary — reused once for the
    whole property rather than re-testing point-in-polygon per candidate
    route.

    A cell outside boundary_prepared is excluded here the same way an
    excluded-zone cell is — this is what keeps generated routes from
    being built out of the DEM's buffered area past the drawn boundary
    (dem_data.py fetches ~100m past the parcel on purpose; without this,
    a route could be built entirely from off-parcel cells)."""
    array = dem["array"]
    rows, cols = array.shape
    excluded = np.zeros((rows, cols), dtype=bool)

    valid = ~np.isnan(array)
    for r in range(rows):
        for c in range(cols):
            if not valid[r, c]:
                continue
            point = Point(pixel_center_xy(dem, r, c))
            if not boundary_prepared.contains(point):
                excluded[r, c] = True
            elif excluded_prepared is not None and excluded_prepared.contains(point):
                excluded[r, c] = True
    return excluded


def _build_production_cell_mask(dem: dict, production_prepared, boundary_prepared) -> np.ndarray:
    """Per-cell boolean mask (True = cell center falls inside the given
    prepared geometry AND on-parcel) -- same iteration structure as
    _build_exclusion_cell_mask(), different (and simpler) boundary
    handling: True only when BOTH conditions hold, rather than "excluded
    if either."

    Despite the name (this function's own logic is unchanged from when it
    was first added purely for production-zone masking), find_road_routes()
    now reuses it for TWO different geometries: production_areas' own
    render_fill_polygon_utm union (its original purpose, now folded into
    excluded_mask as a HARD exclusion under the current design, not a
    separate soft cost term) AND, separately, the floodplain/hydric union
    (a SOFT cost penalty instead) -- the underlying "is this on-parcel
    cell inside that prepared geometry" test is identical either way, so
    there's no reason to duplicate it under a second name.

    production_prepared may be None (no production zones at all, or --
    when reused for floodplain -- no floodplain data at all), in which
    case every cell is simply False."""
    array = dem["array"]
    rows, cols = array.shape
    production_mask = np.zeros((rows, cols), dtype=bool)

    if production_prepared is None:
        return production_mask

    valid = ~np.isnan(array)
    for r in range(rows):
        for c in range(cols):
            if not valid[r, c]:
                continue
            point = Point(pixel_center_xy(dem, r, c))
            if boundary_prepared.contains(point) and production_prepared.contains(point):
                production_mask[r, c] = True
    return production_mask


def _snap_anchor_to_eligible_cell(
    dem: dict,
    cost_raster: np.ndarray,
    anchor_lon_lat: tuple[float, float],
) -> Optional[tuple[int, int]]:
    """
    Warps the given (lon, lat) anchor point into the DEM's own UTM CRS
    (same warp_transform pattern used throughout this module) and returns
    the nearest cell where np.isfinite(cost_raster[r, c]) -- routing
    starts from wherever eligible ground is actually closest to the given
    anchor, not from the anchor's own raw grid cell (which might itself be
    off-parcel, in a hard-excluded zone, or simply not a valid DEM cell at
    all).

    The anchor's approximate (row, col) is computed as the direct algebraic
    inverse of raster_grid.pixel_center_xy() (solved for row/col given x/y,
    rather than searched for), then the actual nearest ELIGIBLE cell is
    found by comparing every finite-cost cell's own grid distance to that
    point -- the direct inverse alone can legitimately land on a
    hard-excluded cell, so it's only a starting estimate, not the answer.

    Returns None if cost_raster has no finite-cost cell anywhere at all
    (the whole property is hard-excluded) -- a real, reportable "nothing
    to route from" outcome, matching this module's own least_cost_path()-
    style None-on-failure convention, rather than returning a nonsensical
    cell or raising.
    """
    eligible_rc = np.argwhere(np.isfinite(cost_raster))
    if eligible_rc.size == 0:
        return None

    anchor_xs, anchor_ys = warp_transform("EPSG:4326", dem["crs"], [anchor_lon_lat[0]], [anchor_lon_lat[1]])
    anchor_x, anchor_y = anchor_xs[0], anchor_ys[0]

    px, py = dem["resolution_meters"]
    approx_col = (anchor_x - dem["origin_x"]) / px - 0.5
    approx_row = (dem["origin_y"] - anchor_y) / py - 0.5

    distances_sq = (eligible_rc[:, 0] - approx_row) ** 2 + (eligible_rc[:, 1] - approx_col) ** 2
    nearest = eligible_rc[np.argmin(distances_sq)]
    return (int(nearest[0]), int(nearest[1]))


def _snap_utm_point_to_eligible_cell(
    dem: dict, cost_raster: np.ndarray, x: float, y: float
) -> Optional[tuple[int, int]]:
    """
    Same "nearest finite-cost cell" pattern as _snap_anchor_to_eligible_
    cell() -- deliberately a parallel, standalone implementation rather
    than a shared extraction, since that function is left untouched here
    -- but starting from a point already in the DEM's own UTM CRS (e.g. a
    fan ray's boundary-exit point, see _select_fan_destination_cells())
    instead of a raw (lon, lat) that still needs warping first.

    Returns None if cost_raster has no finite-cost cell anywhere at all,
    same "nothing to snap to" convention as _snap_anchor_to_eligible_cell().
    """
    eligible_rc = np.argwhere(np.isfinite(cost_raster))
    if eligible_rc.size == 0:
        return None

    px, py = dem["resolution_meters"]
    approx_col = (x - dem["origin_x"]) / px - 0.5
    approx_row = (dem["origin_y"] - y) / py - 0.5

    distances_sq = (eligible_rc[:, 0] - approx_row) ** 2 + (eligible_rc[:, 1] - approx_col) ** 2
    nearest = eligible_rc[np.argmin(distances_sq)]
    return (int(nearest[0]), int(nearest[1]))


def _farthest_intersection_point(anchor_point: Point, intersection) -> Optional[Point]:
    """
    Given the (possibly empty, possibly multi-part) result of
    intersecting a fan ray with boundary_polygon_utm's own exterior ring,
    returns whichever resulting point is FARTHEST from anchor_point --
    the ray's LAST crossing of the boundary. A concave parcel can cross a
    long ray more than once (enter/exit/enter/exit...); the farthest
    crossing is the one that actually represents "where this ray exits
    the parcel for good," which is what casting a ray out to a boundary-
    exit destination means here. Returns None if the intersection is
    empty (see _select_fan_destination_cells() for when/why that happens).
    """
    if intersection.is_empty:
        return None

    candidate_points = []
    if intersection.geom_type == "Point":
        candidate_points = [intersection]
    elif intersection.geom_type == "LineString":
        candidate_points = [Point(c) for c in intersection.coords]
    elif hasattr(intersection, "geoms"):
        for geom in intersection.geoms:
            if geom.geom_type == "Point":
                candidate_points.append(geom)
            elif geom.geom_type == "LineString":
                candidate_points.extend(Point(c) for c in geom.coords)

    if not candidate_points:
        return None
    return max(candidate_points, key=lambda p: p.distance(anchor_point))


def _select_fan_destination_cells(
    dem: dict,
    cost_raster: np.ndarray,
    anchor_cell: tuple[int, int],
    boundary_polygon_utm: Polygon,
) -> list[tuple[int, int]]:
    """
    Up to three candidate destination cells, one per "fan" direction
    radiating from the anchor cell: the PRIMARY axis toward
    boundary_polygon_utm's own centroid, plus that same axis rotated
    +FAN_RAY_ANGLE_DEG ("left") and -FAN_RAY_ANGLE_DEG ("right"). This
    deliberately spreads candidate destinations across different REGIONS
    of the property, instead of the single farthest-point destination an
    earlier version of this module used (which only ever explored one
    direction).

    For each direction: casts a ray from the anchor's own UTM position,
    FAN_RAY_LENGTH_DIAGONAL_MULTIPLIER times longer than
    boundary_polygon_utm's own bounding-box diagonal -- long enough to be
    practically guaranteed to cross the boundary's exterior ring
    regardless of parcel shape or exactly where the anchor sits -- and
    takes the FARTHEST intersection with that ring
    (_farthest_intersection_point(), handling a concave parcel's own
    possible multiple crossings), then snaps that boundary-exit point to
    the nearest eligible cell (_snap_utm_point_to_eligible_cell()).

    Defensive-only fallback: if a ray genuinely produces zero boundary
    intersections at all (shouldn't happen given the ray's own length),
    logs which condition triggered it -- the anchor cell falling outside
    boundary_polygon_utm entirely (a real possibility: the anchor's raw
    grid cell is only ever an ESTIMATE snapped to nearby eligible ground,
    see _snap_anchor_to_eligible_cell()'s own docstring, not guaranteed to
    itself sit inside the true boundary polygon) vs. a ray that's
    somehow still too short despite its own length (shouldn't occur at
    all) -- and drops that one fan point rather than forcing one.

    Two (or all three) rays can legitimately snap to the SAME real
    destination cell on a narrow/sliver-shaped parcel -- deduplicated
    here, so the result may hold fewer than 3 cells even when every ray
    itself succeeds. Returns [] only if every ray failed outright (e.g.
    the anchor cell is entirely outside the boundary).
    """
    anchor_x, anchor_y = pixel_center_xy(dem, *anchor_cell)
    anchor_point = Point(anchor_x, anchor_y)
    centroid = boundary_polygon_utm.centroid

    primary_dx, primary_dy = centroid.x - anchor_x, centroid.y - anchor_y
    primary_length = math.hypot(primary_dx, primary_dy)
    if primary_length == 0:
        # The anchor sits exactly on the centroid (a real, if unlikely,
        # possibility) -- pick an arbitrary primary direction (due east)
        # so the ±22.5° rotation is still well-defined; the fan still
        # spreads out normally from there.
        primary_dx, primary_dy, primary_length = 1.0, 0.0, 1.0
    primary_unit_x, primary_unit_y = primary_dx / primary_length, primary_dy / primary_length

    minx, miny, maxx, maxy = boundary_polygon_utm.bounds
    ray_length = math.hypot(maxx - minx, maxy - miny) * FAN_RAY_LENGTH_DIAGONAL_MULTIPLIER
    boundary_exterior = boundary_polygon_utm.exterior
    anchor_inside_boundary = boundary_polygon_utm.contains(anchor_point) or boundary_polygon_utm.touches(anchor_point)

    destination_cells: list[tuple[int, int]] = []
    seen_cells: set[tuple[int, int]] = set()

    for direction_label, angle_deg in (("primary", 0.0), ("left", FAN_RAY_ANGLE_DEG), ("right", -FAN_RAY_ANGLE_DEG)):
        angle_rad = math.radians(angle_deg)
        cos_a, sin_a = math.cos(angle_rad), math.sin(angle_rad)
        ray_dx = primary_unit_x * cos_a - primary_unit_y * sin_a
        ray_dy = primary_unit_x * sin_a + primary_unit_y * cos_a
        ray = LineString([anchor_point, Point(anchor_x + ray_dx * ray_length, anchor_y + ray_dy * ray_length)])

        exit_point = _farthest_intersection_point(anchor_point, ray.intersection(boundary_exterior))
        if exit_point is None:
            if not anchor_inside_boundary:
                print(
                    f"  _select_fan_destination_cells: {direction_label} ray produced no boundary "
                    f"intersection -- the anchor cell itself falls outside boundary_polygon_utm, "
                    f"dropping this fan point rather than forcing one."
                )
            else:
                print(
                    f"  _select_fan_destination_cells: {direction_label} ray produced no boundary "
                    f"intersection despite a length of {ray_length:.0f}m "
                    f"({FAN_RAY_LENGTH_DIAGONAL_MULTIPLIER}x the boundary's own bounding-box diagonal) -- "
                    f"this shouldn't be possible for an anchor genuinely inside the boundary; dropping "
                    f"this fan point rather than forcing one."
                )
            continue

        cell = _snap_utm_point_to_eligible_cell(dem, cost_raster, exit_point.x, exit_point.y)
        if cell is None or cell in seen_cells:
            continue
        seen_cells.add(cell)
        destination_cells.append(cell)

    return destination_cells


def _grade_stats(points_xyz: list[tuple[float, float, float]]) -> tuple[float, float]:
    grades = []
    for (x1, y1, z1), (x2, y2, z2) in zip(points_xyz, points_xyz[1:]):
        distance = math.hypot(x2 - x1, y2 - y1)
        if distance > 0:
            grades.append(abs(z2 - z1) / distance * 100.0)
    if not grades:
        return 0.0, 0.0
    return float(np.mean(grades)), float(np.std(grades))


def find_road_routes(
    dem: dict,
    production_areas: list[dict],
    selected_water_zone: Optional[dict],
    boundary_polygon_utm: Polygon,
    anchor_lon_lat: tuple[float, float],
    hydric_floodplain_union=None,
    min_corridor_length_meters: float = MIN_CORRIDOR_LENGTH_METERS,
) -> list[dict]:
    """
    Pure geometric/scoring core — see module docstring for why this takes
    already-computed inputs (production areas, the single selected water
    zone, floodplain cost-penalty union) rather than fetching or
    delineating anything itself.

    selected_water_zone is water_suitability.fetch_and_select_optimal_
    water_zone()'s own single rank-1 answer (or None if no water zone was
    identified) -- each entry carrying 'render_fill_polygon_utm' (SAME
    optimized/final geometry production_areas below uses, not the raw
    'polygon_utm'), HARD-excluded (buffered). production_areas is
    production_area_ceiling.identify_optimized_production_areas()'s own
    'scored_patches' -- the OPTIMIZED/final, ceiling-trimmed patch shape
    (each entry carrying 'render_fill_polygon_utm') -- ALSO now HARD-
    excluded (see module docstring; an earlier version of this module
    treated production as a soft cost preference instead).
    hydric_floodplain_union is a shapely geometry (or None to skip that
    penalty entirely) already in dem['crs'] -- a SOFT cost penalty now,
    not a hard exclusion.

    anchor_lon_lat is the single (lon, lat) point routing starts from
    (snapped to the nearest eligible cell -- see
    _snap_anchor_to_eligible_cell()); each returned route ends at one of
    up to three fan-direction destinations from that anchor (see
    _select_fan_destination_cells()) -- primary, left, and right, one
    independent least_cost_path() route per surviving destination. There
    is no named-road anchoring or boundary-connector step here at all
    (see module docstring) -- a route IS the anchor-to-fan-destination
    path, not something extended afterward.

    boundary_polygon_utm is the hard limit on which DEM cells routing can
    draw from at all, via _build_exclusion_cell_mask() -- the DEM covers
    ~100m past the drawn boundary on purpose (dem_data.py), but a route's
    own geometry must come from on-parcel cells only. It's also the
    target boundary_polygon_utm.exterior each fan ray is cast against in
    _select_fan_destination_cells().

    Returns a list of routes, ranked by ascending total_cost (cheapest
    first):
        {
            'rank': int,
            'suitability_score': float,      # 0-100
            'avg_grade_pct': float,
            'length_m': float,
            'crosses_floodplain': bool,
            'fan_direction': 'primary' | 'left' | 'right',
            'points_xyz': [(x, y, elevation_m), ...],
            'geometry_wgs84': GeoJSON LineString,
        }

    Returns [] if the anchor snaps to no eligible cell at all, if every
    fan ray fails to produce a usable destination
    (_select_fan_destination_cells() returns []), or if every fan
    direction's own route is dropped by min_corridor_length_meters -- a
    real, reportable "no routes" outcome, not an error.
    """
    slope_pct, _aspect_deg = compute_slope_and_aspect(dem["array"], dem["resolution_meters"])

    pond_union = (
        selected_water_zone["render_fill_polygon_utm"].buffer(POND_ZONE_EXCLUSION_BUFFER_METERS)
        if selected_water_zone is not None
        else None
    )
    hard_exclusion_pieces = [u for u in (pond_union,) if u is not None and not u.is_empty]
    combined_hard_exclusion_union = unary_union(hard_exclusion_pieces) if hard_exclusion_pieces else None
    excluded_prepared = prep(combined_hard_exclusion_union) if combined_hard_exclusion_union is not None else None
    boundary_prepared = prep(boundary_polygon_utm)
    excluded_mask = _build_exclusion_cell_mask(dem, excluded_prepared, boundary_prepared)

    # Production zones are now a HARD exclusion (see module docstring) --
    # _build_production_cell_mask()'s own output (unchanged function) is
    # OR'd directly into excluded_mask here, rather than passed to
    # build_cost_raster() as a separate soft term the way an earlier
    # version of this module did.
    raw_production_union = (
        unary_union([p["render_fill_polygon_utm"] for p in production_areas]) if production_areas else None
    )
    production_prepared = (
        prep(raw_production_union) if raw_production_union is not None and not raw_production_union.is_empty else None
    )
    production_mask = _build_production_cell_mask(dem, production_prepared, boundary_prepared)
    excluded_mask = excluded_mask | production_mask

    # Floodplain/hydric is a SOFT cost penalty under the current design --
    # NOT folded into excluded_mask at all, passed to build_cost_raster()
    # as its own floodplain_mask instead. Reuses _build_production_cell_
    # mask()'s exact "on-parcel cell inside this prepared geometry" test
    # (see that function's own docstring) against a different geometry.
    floodplain_mask = None
    if hydric_floodplain_union is not None and not hydric_floodplain_union.is_empty:
        floodplain_prepared = prep(hydric_floodplain_union)
        floodplain_mask = _build_production_cell_mask(dem, floodplain_prepared, boundary_prepared)

    cost_raster = build_cost_raster(dem, slope_pct, excluded_mask, floodplain_mask=floodplain_mask)

    source_cell = _snap_anchor_to_eligible_cell(dem, cost_raster, anchor_lon_lat)
    if source_cell is None:
        return []

    destination_cells = _select_fan_destination_cells(dem, cost_raster, source_cell, boundary_polygon_utm)
    if not destination_cells:
        return []

    # Direction labels are re-derived from each SURVIVING destination's own
    # bearing (relative to the same anchor->centroid primary axis
    # _select_fan_destination_cells() itself used), not just zipped
    # positionally against destination_cells -- that function can legitimately
    # drop a middle fan ray (e.g. "left" fails but "primary"/"right" both
    # succeed), and positional zipping would then mislabel "right"'s cell as
    # "left".
    anchor_x, anchor_y = pixel_center_xy(dem, *source_cell)
    centroid = boundary_polygon_utm.centroid
    primary_angle = math.atan2(centroid.y - anchor_y, centroid.x - anchor_x)

    routes = []
    for destination_cell in destination_cells:
        result = least_cost_path(dem, cost_raster, [source_cell], [destination_cell])
        if result is None or len(result["cells"]) < 2:
            # source_cell == destination_cell (a degenerate, essentially
            # zero-eligible-ground property) has no length/direction to
            # form a LineString from at all -- dropped here the same way
            # min_corridor_length_meters below drops any other "not a
            # meaningful road" route.
            continue

        points = path_cells_to_points_xyz(dem, result["cells"])
        line = LineString([(p[0], p[1]) for p in points])

        length_m = line.length
        if length_m < min_corridor_length_meters:
            continue

        avg_grade_pct, _grade_stddev_pct = _grade_stats(points)
        crosses_floodplain = hydric_floodplain_union is not None and line.intersects(hydric_floodplain_union)

        dest_x, dest_y = pixel_center_xy(dem, *destination_cell)
        dest_angle = math.atan2(dest_y - anchor_y, dest_x - anchor_x)
        delta_deg = (math.degrees(dest_angle - primary_angle) + 180.0) % 360.0 - 180.0
        if delta_deg > FAN_RAY_ANGLE_DEG / 2.0:
            fan_direction: FanDirection = "left"
        elif delta_deg < -FAN_RAY_ANGLE_DEG / 2.0:
            fan_direction = "right"
        else:
            fan_direction = "primary"

        routes.append(
            {
                "points_xyz": points,
                "line_utm": line,
                "total_cost": result["total_cost"],
                "length_m": length_m,
                "avg_grade_pct": avg_grade_pct,
                "crosses_floodplain": crosses_floodplain,
                "fan_direction": fan_direction,
            }
        )

    if not routes:
        return []

    routes.sort(key=lambda r: r["total_cost"])

    if len(routes) == 1:
        # The degenerate case: with only one surviving route, there's no
        # "most expensive route in this batch" to normalize against --
        # 100 * (1 - total_cost / max_total_cost) would divide total_cost
        # by ITSELF and always score the lone survivor 0/100 (the worst
        # possible score), exactly backwards. The single route IS the
        # best (and only) option available, so it scores 100.0 outright.
        routes[0]["suitability_score"] = 100.0
    else:
        max_total_cost = max(r["total_cost"] for r in routes)
        for route in routes:
            score = 100.0 * (1.0 - route["total_cost"] / max_total_cost) if max_total_cost > 0 else 100.0
            route["suitability_score"] = max(0.0, min(100.0, score))

    for rank, route in enumerate(routes, start=1):
        route["rank"] = rank
        xs = [p[0] for p in route["points_xyz"]]
        ys = [p[1] for p in route["points_xyz"]]
        lons, lats = warp_transform(dem["crs"], "EPSG:4326", xs, ys)
        route["geometry_wgs84"] = {"type": "LineString", "coordinates": list(zip(lons, lats))}

    return routes


def select_optimal_road_corridor(scored_routes: list[dict]) -> Optional[dict]:
    """
    Explicit selection step on top of find_road_routes()'s own ranking:
    returns the single route with rank == 1 (highest suitability_score) --
    no logic beyond that. Same pattern as water_suitability.
    select_optimal_water_zone(); per product decision, this app targets
    small farms only, where one well-suited road route is sufficient --
    no multi-route coexistence logic is needed here.

    Returns None if scored_routes is empty -- a real, reportable "no
    routes at all" outcome, not an error.
    """
    if not scored_routes:
        return None
    return max(scored_routes, key=lambda r: r["suitability_score"])


def _confidence_notes_for_route(
    floodplain_data_is_fallback: bool,
    avg_grade_pct: float,
    crosses_floodplain: bool,
) -> str:
    floodplain_crossing_note = FLOODPLAIN_CROSSING_NOTE if crosses_floodplain else ""

    steep_grade_note = (
        STEEP_GRADE_ENGINEERING_NOTE.format(
            avg_grade_pct=round(avg_grade_pct, 1), threshold_pct=STEEP_GRADE_ENGINEERING_NOTE_THRESHOLD_PCT
        )
        if avg_grade_pct > STEEP_GRADE_ENGINEERING_NOTE_THRESHOLD_PCT
        else ""
    )
    floodplain_fallback_note = (
        "Floodplain/wet-ground cost scoring used a DEM-only fallback (buffered delineated valley "
        "lines), not real NHD/SSURGO data, because that data wasn't available for this run. "
        if floodplain_data_is_fallback
        else ""
    )
    return ROAD_CORRIDOR_CONFIDENCE_NOTES_TEMPLATE.format(
        floodplain_crossing_note=floodplain_crossing_note,
        steep_grade_note=steep_grade_note,
        floodplain_fallback_note=floodplain_fallback_note,
    )


def corridors_to_geojson(
    routes: list[dict],
    floodplain_data_is_fallback: bool = False,
) -> dict:
    """Wraps find_road_routes() output as the schema-conformant GeoJSON
    FeatureCollection this feature delivers (layer="suggested_road_corridor")."""
    features = []
    for route in routes:
        features.append(
            make_feature(
                feature_id=f"road-corridor-{route['rank']}",
                geometry=route["geometry_wgs84"],
                layer="suggested_road_corridor",
                label=f"Suggested road route (rank {route['rank']}, {route['fan_direction']})",
                confidence=CONFIDENCE_LOW,
                confidence_notes=_confidence_notes_for_route(
                    floodplain_data_is_fallback,
                    route["avg_grade_pct"],
                    route["crosses_floodplain"],
                ),
                extra_properties={
                    "rank": route["rank"],
                    "suitability_score": round(route["suitability_score"], 1),
                    "avg_grade_pct": round(route["avg_grade_pct"], 1),
                    "length_ft": round(route["length_m"] / METERS_PER_FOOT, 1),
                    "crosses_floodplain": route["crosses_floodplain"],
                    "fan_direction": route["fan_direction"],
                    # Both genuinely HARD exclusions under the current
                    # design (see module docstring) -- unlike an earlier
                    # version of this module, grade and floodplain are NOT
                    # listed here at all anymore: neither is a real
                    # enforced constraint (both are soft cost penalties a
                    # route may or may not have paid), so claiming either
                    # "satisfied" would be misleading.
                    "constraints_satisfied": ["outside_pond_zone", "outside_production_zone"],
                },
            )
        )

    return make_feature_collection(features)


def _log_fetch_failure(label: str, exc: Exception) -> None:
    """
    Every real-data fetch in this module degrades gracefully on failure
    (see the module docstring), but "gracefully" shouldn't mean "silently
    identical whether the cause was a transient network timeout or a real
    bug in the query itself." A 4xx HTTP status means the server rejected
    the REQUEST as malformed (bad SQL, a column/table that doesn't exist)
    — that will fail exactly the same way on every future run, unlike a
    timeout or connection error, which might not. Anything that isn't
    even a requests error (a KeyError from an unexpected response shape,
    etc.) is just as clearly a real bug, not network flakiness. Print a
    distinct message for each case so this doesn't look like ordinary
    network unavailability in the logs.
    """
    if isinstance(exc, requests.exceptions.RequestException):
        status = getattr(getattr(exc, "response", None), "status_code", None)
        if status is not None and 400 <= status < 500:
            print(
                f"  {label}: request rejected by the server (HTTP {status}) — likely a real "
                f"query/schema bug, not transient network unavailability: {exc}"
            )
        else:
            print(f"  {label}: network request failed ({exc}), continuing without it.")
    else:
        print(f"  {label}: unexpected failure, not a network error ({type(exc).__name__}: {exc}).")


def _fetch_floodplain_hydric_union(
    boundary_coordinates, dem, valleys, boundary_polygon_utm
) -> tuple[Optional[object], bool]:
    """NHD stream/water-body buffers + SSURGO hydric soil polygons,
    unioned; falls back to buffering the already-computed delineated
    valley lines (an elevation-only proxy) only if BOTH real sources are
    unreachable. Returns (union_or_None, is_fallback). This union now
    feeds a SOFT cost penalty (see module docstring), not a hard
    exclusion -- the fetch/clip/buffer logic that builds it is otherwise
    unchanged.

    Each fetched NHD feature is clipped to a generous context region
    around boundary_polygon_utm (FLOODPLAIN_FETCH_CONTEXT_BUFFER_METERS)
    BEFORE being buffered into the union — see that constant's own
    comment for the real bug this fixes: NHD's query returns each
    matching feature's full, un-clipped geometry, so a stream or
    waterbody merely touching the (already-buffered) fetch bounding box
    could come back with geometry extending far past the property,
    ballooning the resulting union to many times the parcel's own size.
    The SSURGO hydric piece needs no equivalent clip here — it already
    comes back clipped to the parcel's own wkt_polygon from
    get_soil_geometries_for_polygon() itself (STIntersection), so it can
    never exceed the parcel's own area in the first place.

    A mukey only contributes its hydric geometry here if its SUMMED hydric
    component percentage meets soil_data.MIN_HYDRIC_COMPONENT_PCT_TO_EXCLUDE
    (soil_data.hydric_disqualifying_mukeys()) — a real, second bug found
    live alongside the NHD-clipping one above: a map unit that's 99%+
    well/moderately-well-drained but has a single 1%-of-composition hydric
    component was previously flagged the SAME as a map unit that's 85%+
    hydric, and its entire (much larger) mapped polygon got included right
    alongside genuinely wet ground.

    Each fetched NHD feature's BUFFERED piece is additionally intersected
    against boundary_polygon_utm.buffer(FLOODPLAIN_FINAL_RELEVANCE_BUFFER_METERS)
    before being added to the union — see that constant's own comment for
    the THIRD bug this fixes: the fetch-context clip above bounds each raw
    stream feature before it's buffered, but nothing previously bounded
    the result AFTER buffering, so the buffer stroke (and however much
    stream length survived the looser fetch-context clip) could still
    produce a final piece extending well past any distance actually
    relevant to this parcel. Confirmed live: an 11.2-acre union of which
    only 0.077 acres (0.6%) actually overlapped the real parcel — a long
    buffered band along Montour Run, entirely on the far side of N Montour
    Rd from the field.
    """
    context_region = boundary_polygon_utm.buffer(FLOODPLAIN_FETCH_CONTEXT_BUFFER_METERS)
    final_relevance_region = boundary_polygon_utm.buffer(FLOODPLAIN_FINAL_RELEVANCE_BUFFER_METERS)
    pieces = []

    try:
        water_features = get_water_features_for_boundary(boundary_coordinates)
        for feature in water_features["streams"] + water_features["water_bodies"]:
            geometry = feature.get("geometry")
            if geometry is None:
                continue
            utm_geometry = shape(transform_geom("EPSG:4326", dem["crs"], geometry))
            clipped_geometry = utm_geometry.intersection(context_region)
            if clipped_geometry.is_empty:
                continue
            buffered_geometry = clipped_geometry.buffer(FLOODPLAIN_STREAM_BUFFER_METERS)
            relevant_geometry = buffered_geometry.intersection(final_relevance_region)
            if relevant_geometry.is_empty:
                continue
            pieces.append(relevant_geometry)
    except Exception as e:
        _log_fetch_failure("NHD stream/water-body fetch", e)

    try:
        wkt_polygon = coordinates_to_wkt_polygon(boundary_coordinates)
        soil_components = get_soil_data_for_polygon(wkt_polygon)
        hydric_mukeys = hydric_disqualifying_mukeys(soil_components)
        if hydric_mukeys:
            geometries_by_mukey = get_soil_geometries_for_polygon(wkt_polygon)
            for mukey in hydric_mukeys:
                geometry = geometries_by_mukey.get(mukey)
                if geometry is not None:
                    pieces.append(shape(transform_geom("EPSG:4326", dem["crs"], geometry)))
    except Exception as e:
        _log_fetch_failure("SSURGO hydric soil fetch", e)

    if pieces:
        return unary_union(pieces), False

    # Fallback: neither NHD nor SSURGO reachable -- use the valley network
    # already computed for pond-zone identification as a coarse,
    # elevation-only "probably wet ground follows drainage lines" proxy.
    fallback_pieces = []
    for valley in valleys:
        for branch in valley["branches_utm"]:
            line = LineString([(p[0], p[1]) for p in branch])
            fallback_pieces.append(line.buffer(FLOODPLAIN_STREAM_BUFFER_METERS))

    return (unary_union(fallback_pieces) if fallback_pieces else None), True


def identify_road_corridor_candidates(
    boundary_coordinates: list[tuple[float, float]],
    dem: Optional[dict] = None,
    anchor_lon_lat: Optional[tuple[float, float]] = None,
    **corridor_kwargs,
) -> dict:
    """
    Full pipeline entry point: fetches/derives everything find_road_
    routes() needs (optimized production areas, the single selected water
    zone, floodplain cost-penalty union) and returns the
    "suggested_road_corridor" GeoJSON FeatureCollection. Every real-data
    fetch degrades independently and gracefully, same pattern as
    water_candidate_zones.py and solar_suitability.py.

    anchor_lon_lat (lon, lat) is the real, chosen access point routing
    starts from (see find_road_routes()) -- kept Optional here (default
    None) purely so every EXISTING caller of this entry point that hasn't
    been updated to supply a real anchor point yet keeps working exactly
    as it did for "no road route available" (the same empty-result shape
    any other not-yet-computable layer in this pipeline already returns)
    rather than a hard TypeError. This is NOT a fabricated fallback anchor
    point -- there is no reasonable one to invent (a real anchor is a
    product decision -- where does this property actually connect to the
    outside world -- not something derivable from the boundary alone), so
    None here simply means no routes can be generated at all yet.

    Returns:
        {
            'zones_geojson': dict,                       # every scored route, ranked
            'all_scored_candidates': list[dict],         # find_road_routes()'s own
                                                            # raw scored list (carries line_utm)
            'selected_road_corridor': Optional[dict],    # select_optimal_road_corridor()'s single
                                                            # rank-1 answer, or None if no routes exist
        }
    """
    if dem is None:
        dem = get_dem_for_boundary(boundary_coordinates)

    if anchor_lon_lat is None:
        return {
            "zones_geojson": corridors_to_geojson([]),
            "all_scored_candidates": [],
            "selected_road_corridor": None,
        }

    boundary_xs, boundary_ys = warp_transform(
        "EPSG:4326",
        dem["crs"],
        [pt[0] for pt in boundary_coordinates],
        [pt[1] for pt in boundary_coordinates],
    )
    boundary_polygon_utm = Polygon(zip(boundary_xs, boundary_ys))

    # Optimized/final production geometry (production_area_ceiling.py's
    # own ceiling-trimmed, clustered/gated result) -- NOT production_area.
    # identify_production_areas()'s raw pre-optimization patches. Each
    # patch is expected to carry 'render_fill_polygon_utm' (production_
    # area.py's own render-only convex-hull field), the same field
    # find_road_routes() hard-excludes against below; fail loudly here
    # rather than let a KeyError surface deep inside that masking code if
    # this pipeline's own patch shape ever changes.
    production_areas = identify_optimized_production_areas(boundary_coordinates, dem=dem)["scored_patches"]
    if production_areas and "render_fill_polygon_utm" not in production_areas[0]:
        raise RuntimeError(
            "identify_optimized_production_areas()'s scored_patches no longer carry "
            "'render_fill_polygon_utm' -- road_corridors.py's production-zone hard exclusion "
            "depends on this field; update find_road_routes() to match the new shape."
        )

    valleys = delineate_valleys(dem)  # reused for the floodplain fallback below

    # The single water zone this property's OWN water-suitability scoring
    # actually selected (rank 1), not every unscored candidate zone
    # water_candidate_zones.py generates -- see module docstring.
    selected_water_zone = fetch_and_select_optimal_water_zone(boundary_coordinates, dem=dem)

    hydric_floodplain_union, floodplain_data_is_fallback = _fetch_floodplain_hydric_union(
        boundary_coordinates, dem, valleys, boundary_polygon_utm
    )

    routes = find_road_routes(
        dem,
        production_areas,
        selected_water_zone,
        boundary_polygon_utm,
        anchor_lon_lat,
        hydric_floodplain_union=hydric_floodplain_union,
        **corridor_kwargs,
    )

    return {
        "zones_geojson": corridors_to_geojson(
            routes,
            floodplain_data_is_fallback=floodplain_data_is_fallback,
        ),
        "all_scored_candidates": routes,
        "selected_road_corridor": select_optimal_road_corridor(routes),
    }


def fetch_and_select_optimal_road_corridor(
    boundary_coordinates: list[tuple[float, float]],
    dem: Optional[dict] = None,
    **corridor_kwargs,
) -> Optional[dict]:
    """
    Convenience wrapper for callers (e.g. render_layout_map.py) that want
    a single best suggested road route rather than the full ranked
    FeatureCollection -- identify_road_corridor_candidates() already
    returns routes rank-ordered best-first (feature 0 = rank 1), so this
    just returns that top GeoJSON Feature (or None if nothing cleared the
    constraint stack, or no anchor_lon_lat was given). Selects nothing
    new -- it picks the #1 entry an existing, unchanged ranking already
    produced.
    """
    result = identify_road_corridor_candidates(boundary_coordinates, dem=dem, **corridor_kwargs)
    features = result["zones_geojson"]["features"]
    return features[0] if features else None


def summarize_road_corridor_candidates(result: dict) -> str:
    features = result["zones_geojson"]["features"]
    if not features:
        return "No road routes identified (no anchor point given, or nothing cleared the constraint stack)."

    lines = [f"Road routes identified: {len(features)}"]
    for feature in features:
        props = feature["properties"]
        crossing = " [crosses floodplain]" if props.get("crosses_floodplain") else ""
        lines.append(
            f"  - Rank {props['rank']} ({props['fan_direction']}): score {props['suitability_score']}/100, "
            f"{props['avg_grade_pct']}% avg grade, {props['length_ft']}ft{crossing}"
        )
    return "\n".join(lines)


if __name__ == "__main__":
    property_boundary = [
        (-79.9838154, 40.6458343),
        (-79.9836701, 40.6428581),
        (-79.9813665, 40.6440549),
        (-79.9804741, 40.6445667),
        (-79.9827466, 40.6458894),
        (-79.9838258, 40.6458343),
    ]
    anchor_lon_lat = (-79.98356157031265, 40.64303511679458)

    print("Identifying suggested road routes for property boundary...\n")

    try:
        result = identify_road_corridor_candidates(property_boundary, anchor_lon_lat=anchor_lon_lat)
        print(summarize_road_corridor_candidates(result))
    except Exception as e:
        print(f"Request failed: {e}")
        print(
            "\nNote: this requires internet access to reach USGS's National "
            "Map services and USDA's Soil Data Access — not a fully "
            "sandboxed environment."
        )
