"""
test_water_suitability.py

Offline (no-network) checks for water_suitability.py's per-factor scoring
and weighted composite ranking. Same "pure logic, independent of real data
fetches" approach as test_production_suitability.py/test_solar_suitability.py:
score_water_zones() is exercised directly against real zones generated by
find_candidate_zones() from a small synthetic DEM (water_candidate_zones.py's
cell-based rearchitecture means zones no longer carry a valley_id to hand-
build a matching fixture around -- see test_water_candidate_zones.py's own
docstring for the same reasoning) plus hand-built valleys/pre-fetched
soil/stream data dicts, with no network calls anywhere in this file except
the final offline wiring check (identify_water_suitability() with
check_soil=False, check_streams=False and a synthetic dem= passed directly,
mirroring test_water_system_candidate_pipeline.py's approach).
"""

import numpy as np
from shapely.geometry import box

import production_area as pa
from feature_schema import validate_feature_collection
from water_candidate_zones import find_candidate_zones
from water_suitability import (
    GRAVITY_FULL_CREDIT_GRADIENT_PCT,
    GRAVITY_LEVEL_GROUND_FACTOR,
    GRAVITY_MAX_DEFICIT_GRADIENT_PCT,
    GRAVITY_MIN_FACTOR,
    GRAVITY_ZERO_DISTANCE_FULL_CREDIT_METERS,
    GRAVITY_ZERO_DISTANCE_MAX_DEFICIT_METERS,
    STREAM_NEUTRAL_FACTOR,
    STREAM_PROXIMITY_REFERENCE_METERS,
    WATER_HOLDING_GOOD_KSAT_UM_PER_S,
    WATER_HOLDING_POOR_KSAT_UM_PER_S,
    WATER_HOLDING_UNAVAILABLE_FACTOR,
    _WEIGHT_SUM,
    _gravity_feed_factor,
    _stream_permanence_factor,
    _topographic_factor,
    _water_holding_factor,
    identify_water_suitability,
    score_water_zones,
    water_suitability_to_geojson,
)

CRS = "EPSG:32617"

assert abs(_WEIGHT_SUM - 1.0) < 1e-6, f"composite weights must sum to 1.0, got {_WEIGHT_SUM}"
print("Composite factor weights sum to 1.0.")


# --- _gravity_feed_factor(): continuous, monotonic, never truly zero ----
# --- (distance_m > 0 case: scores off gradient_pct, the original scale) --

# distance_m is nonzero (100.0) and elevation_differential_m is irrelevant
# in this branch -- only gradient_pct drives the score when distance_m > 0.
assert _gravity_feed_factor(999.0, 100.0, GRAVITY_FULL_CREDIT_GRADIENT_PCT) == 1.0
assert _gravity_feed_factor(999.0, 100.0, GRAVITY_FULL_CREDIT_GRADIENT_PCT * 5) == 1.0, "extra-comfortable gradient still caps at 1.0"
assert _gravity_feed_factor(999.0, 100.0, 0.0) == GRAVITY_LEVEL_GROUND_FACTOR
assert _gravity_feed_factor(999.0, 100.0, GRAVITY_MAX_DEFICIT_GRADIENT_PCT) == GRAVITY_MIN_FACTOR
assert _gravity_feed_factor(999.0, 100.0, GRAVITY_MAX_DEFICIT_GRADIENT_PCT * 5) == GRAVITY_MIN_FACTOR, "extreme deficit floors, doesn't go below GRAVITY_MIN_FACTOR"
assert GRAVITY_MIN_FACTOR > 0.0, "a below-elevation (pump-required) candidate must never score literally 0 on this factor"
mild_above = _gravity_feed_factor(999.0, 100.0, 0.5)
mild_below = _gravity_feed_factor(999.0, 100.0, -1.0)
assert GRAVITY_LEVEL_GROUND_FACTOR < mild_above < 1.0
assert GRAVITY_MIN_FACTOR < mild_below < GRAVITY_LEVEL_GROUND_FACTOR
assert (
    _gravity_feed_factor(999.0, 100.0, 1.0) > _gravity_feed_factor(999.0, 100.0, 0.0)
    > _gravity_feed_factor(999.0, 100.0, -1.0) > _gravity_feed_factor(999.0, 100.0, -5.0)
)
print("_gravity_feed_factor() is continuous/monotonic and never zero (distance_m > 0, gradient_pct-driven case).")


# --- _gravity_feed_factor(): distance_m == 0 case -- real bug, fixed ----
#
# Live-confirmed bug: with distance_m == 0 (a zone sitting inside/touching
# a production area — a real, common case since MIN_SERVICE_DISTANCE_METERS
# no longer rejects it), water_candidate_zones.py reports gradient_pct as a
# 0.0 div-by-zero placeholder, NOT a real 0% grade. Scoring directly off
# that placeholder collapsed every distance-0 zone to the same
# GRAVITY_LEVEL_GROUND_FACTOR (0.6), regardless of real elevation_differential_m
# -- on the real property, a +7.01m (strong gravity-feed), a +0.63m (barely
# above), and a -8.68m (pump-required) zone all scored identically. Fixed:
# distance_m == 0 must score off elevation_differential_m directly, not
# gradient_pct.

real_property_valley4 = _gravity_feed_factor(7.01, 0.0, 0.0)   # strong gravity-feed
real_property_valley2 = _gravity_feed_factor(0.63, 0.0, 0.0)   # barely above
real_property_valley11 = _gravity_feed_factor(-8.68, 0.0, 0.0)  # pump-required

assert real_property_valley4 > real_property_valley2 > real_property_valley11, (
    f"real, differentiated elevation differentials at distance_m==0 must score in the correct rank order -- got "
    f"valley4={real_property_valley4}, valley2={real_property_valley2}, valley11={real_property_valley11}"
)
assert real_property_valley11 > 0.0, "even the pump-required zone must never score literally 0 on this factor"
print(
    f"REGRESSION (real property scenario, all distance_m==0): gravity_feed_factor correctly differentiates "
    f"by elevation_differential_m alone -- valley4 (+7.01m)={real_property_valley4} > "
    f"valley2 (+0.63m)={real_property_valley2} > valley11 (-8.68m)={real_property_valley11}."
)

assert _gravity_feed_factor(GRAVITY_ZERO_DISTANCE_FULL_CREDIT_METERS, 0.0, 0.0) == 1.0
assert _gravity_feed_factor(0.0, 0.0, 0.0) == GRAVITY_LEVEL_GROUND_FACTOR
assert _gravity_feed_factor(GRAVITY_ZERO_DISTANCE_MAX_DEFICIT_METERS, 0.0, 0.0) == GRAVITY_MIN_FACTOR
assert _gravity_feed_factor(GRAVITY_ZERO_DISTANCE_MAX_DEFICIT_METERS * 5, 0.0, 0.0) == GRAVITY_MIN_FACTOR
print("_gravity_feed_factor() at distance_m==0 hits the same real reference breakpoints (full credit / level / max deficit).")

# A gradient_pct of 0.0 alongside a nonzero distance_m must still be
# treated as a genuine, real 0% grade (level ground), NOT collapsed to the
# distance==0 meters-based path -- confirms the dispatch is keyed strictly
# off distance_m, not off gradient_pct happening to read 0.0.
assert _gravity_feed_factor(7.01, 50.0, 0.0) == GRAVITY_LEVEL_GROUND_FACTOR
print("A real, nonzero distance with a genuine 0% gradient still scores as level ground, not the distance==0 path.")


# --- _water_holding_factor(): log-scale, real NRCS breakpoints ----------

assert _water_holding_factor(WATER_HOLDING_GOOD_KSAT_UM_PER_S) == 1.0
assert _water_holding_factor(WATER_HOLDING_GOOD_KSAT_UM_PER_S / 10) == 1.0, "even better (lower) than the good reference still caps at 1.0"
assert _water_holding_factor(WATER_HOLDING_POOR_KSAT_UM_PER_S) == 0.0
assert _water_holding_factor(WATER_HOLDING_POOR_KSAT_UM_PER_S * 10) == 0.0
assert _water_holding_factor(None) == WATER_HOLDING_UNAVAILABLE_FACTOR
mid_ksat = (WATER_HOLDING_GOOD_KSAT_UM_PER_S * WATER_HOLDING_POOR_KSAT_UM_PER_S) ** 0.5  # geometric midpoint
mid_score = _water_holding_factor(mid_ksat)
assert 0.4 < mid_score < 0.6, f"log-scale geometric midpoint should score near 0.5, got {mid_score}"
assert _water_holding_factor(1.0) > _water_holding_factor(10.0) > _water_holding_factor(50.0)
print("_water_holding_factor() scores real ksat_r on a log scale between the documented NRCS breakpoints, unavailable defaults neutral.")


# --- _stream_permanence_factor(): real permanence classes, real proximity ---

perennial_close = {"name": "Real Creek", "fcode": 46006, "distance_m": 0.0}
intermittent_close = {"name": "Seasonal Run", "fcode": 46003, "distance_m": 0.0}
ephemeral_close = {"name": "Draw", "fcode": 46007, "distance_m": 0.0}
unknown_close = {"name": "General Stream", "fcode": 46000, "distance_m": 0.0}

perennial_factor, perennial_label = _stream_permanence_factor(perennial_close)
intermittent_factor, intermittent_label = _stream_permanence_factor(intermittent_close)
ephemeral_factor, ephemeral_label = _stream_permanence_factor(ephemeral_close)
unknown_factor, unknown_label = _stream_permanence_factor(unknown_close)

assert perennial_label == "perennial" and intermittent_label == "intermittent" and ephemeral_label == "ephemeral" and unknown_label == "unknown"
assert perennial_factor > intermittent_factor > ephemeral_factor, (
    f"perennial ({perennial_factor}) must outscore intermittent ({intermittent_factor}) "
    f"must outscore ephemeral ({ephemeral_factor}) at equal proximity"
)
assert intermittent_factor > STREAM_NEUTRAL_FACTOR > ephemeral_factor or ephemeral_factor >= STREAM_NEUTRAL_FACTOR
assert perennial_factor == 1.0, "right at a perennial stream (distance=0) should reach the ceiling"
print(f"Stream permanence ordering confirmed at equal proximity: perennial={perennial_factor} > intermittent={intermittent_factor} > ephemeral={ephemeral_factor}, unknown={unknown_factor}.")

far_perennial = {"name": "Real Creek", "fcode": 46006, "distance_m": STREAM_PROXIMITY_REFERENCE_METERS * 2}
far_factor, far_label = _stream_permanence_factor(far_perennial)
assert far_factor == STREAM_NEUTRAL_FACTOR and far_label is None, "a stream beyond the proximity reference contributes no real credit -- same as no stream at all"

none_factor, none_label = _stream_permanence_factor(None)
assert none_factor == STREAM_NEUTRAL_FACTOR and none_label is None
print("A stream beyond the proximity reference, or no stream at all, both correctly fall back to the neutral baseline.")


# --- _topographic_factor(): sweet-spot gradient + contributing area -----

flat_factor, flat_grad_score, _ = _topographic_factor(0.1, 5.0)
sweet_factor, sweet_grad_score, _ = _topographic_factor(8.0, 5.0)
steep_factor, steep_grad_score, _ = _topographic_factor(40.0, 5.0)
assert sweet_grad_score == 1.0
assert flat_grad_score == 0.0 and steep_grad_score == 0.0
assert sweet_factor > flat_factor and sweet_factor > steep_factor
_, _, small_area_score = _topographic_factor(8.0, 1.0)
_, _, big_area_score = _topographic_factor(8.0, 50.0)
assert big_area_score > small_area_score
print("_topographic_factor() correctly scores a moderate valley gradient highest and rewards larger contributing area.")


# --- score_water_zones(): full composite, using REAL zones generated by ---
# --- find_candidate_zones() from a small synthetic DEM (cell-based       ---
# --- rearchitecture: no more valley_id to hand-build a matching zone     ---
# --- fixture around -- see test_water_candidate_zones.py)                ---
#
# Two parallel drainage columns (col=8 and col=32 of a 40x40 grid, 5m
# resolution) far enough apart that their eligible cells never touch --
# same fixture shape test_water_candidate_zones.py's own fragmentation
# test uses -- served by one production area sitting between them, so
# find_candidate_zones() returns exactly 2 real zones (ids 0 and 1).
BOUNDARY = box(500000.0, 4499800.0, 500200.0, 4500000.0)
_size = 40
_array = np.zeros((_size, _size), dtype=np.float32)
for _row in range(_size):
    for _col in range(_size):
        _array[_row, _col] = min(abs(_col - 8), abs(_col - 32)) * 2.0 + _row * 0.5

WATER_SUITABILITY_DEM = {
    "array": _array,
    "resolution_meters": (5.0, 5.0),
    "origin_x": 500000.0,
    "origin_y": 4500000.0,
    "crs": CRS,
}
PRODUCTION_AREAS = [
    {"id": 0, "representative_elevation_m": -5.0, "polygon_utm": box(500080.0, 4499750.0, 500120.0, 4499800.0)}
]

zones = find_candidate_zones(WATER_SUITABILITY_DEM, PRODUCTION_AREAS, BOUNDARY)
zone_ids = {z["id"] for z in zones}
assert zone_ids == {0, 1}, f"expected exactly 2 zones (one per disconnected drainage column), got {zone_ids}"

zone0 = next(z for z in zones if z["id"] == 0)  # column at x~[500030, 500055]
zone1 = next(z for z in zones if z["id"] == 1)  # column at x~[500150, 500175]

# A real valley (valley_delineation.delineate_valleys()'s own output shape)
# whose branch points sit spatially inside zone0's own footprint (bounds
# confirmed directly: (500030.0, 4499905.0, 500055.0, 4499985.0)) -- the
# NEW spatial-overlap matching _valley_topographic_inputs_for_zone() uses
# instead of a zone['valley_id'] == valley['id'] join. zone1 deliberately
# has NO overlapping valley at all, to exercise the "no traced valley
# overlaps this real drainage-cell zone" degradation path (a real,
# expected outcome now -- valley_delineation.py's own traced-valley
# threshold is separate from, and higher than, water_candidate_zones.py's
# own per-cell drainage threshold).
VALLEY_OVERLAPPING_ZONE0 = {
    "id": 0,
    "max_contributing_area_acres": 5.0,
    "branches_utm": [[(500042.5, 4499970.0, 120.0), (500042.5, 4499920.0, 100.0)]],
}
VALLEYS = [VALLEY_OVERLAPPING_ZONE0]

GOOD_SOIL = {"ksat_r_um_per_s": 0.05, "coverage_fraction": 0.9}
POOR_SOIL = {"ksat_r_um_per_s": 300.0, "coverage_fraction": 0.9}

GOOD_STREAM = {"name": "Real Creek", "fcode": 46006, "distance_m": 5.0}

# Best case: zone 0 (real overlapping valley -- real gradient/contributing
# area feed the topographic factor) + good soil + close perennial stream
# should clearly outscore zone 1 (no overlapping valley -- topographic
# factor degrades to neutral) with poor soil and no stream.
best_case_scored = score_water_zones(
    [zone0, zone1],
    VALLEYS,
    WATER_SUITABILITY_DEM,
    soil_data_by_zone_id={0: GOOD_SOIL, 1: POOR_SOIL},
    stream_data_by_zone_id={0: GOOD_STREAM, 1: None},
)
scored_by_id = {z["id"]: z for z in best_case_scored}
assert scored_by_id[0]["gradient_steepness_pct"] is not None, "zone 0's overlapping valley must feed a real gradient"
assert scored_by_id[0]["valley_contributing_area_acres"] == 5.0
assert scored_by_id[1]["gradient_steepness_pct"] is None, "zone 1 has no overlapping valley -- must degrade to None, not crash or fabricate a value"
assert scored_by_id[1]["valley_contributing_area_acres"] is None
assert scored_by_id[0]["suitability_score"] > scored_by_id[1]["suitability_score"]
print(
    f"Zone 0 (real overlapping valley, good soil, near-perennial-stream, score={scored_by_id[0]['suitability_score']}) "
    f"correctly outscores zone 1 (no overlapping valley, poor soil, no stream, score={scored_by_id[1]['suitability_score']})."
)
print(
    "The new spatial-overlap valley matching correctly feeds zone 0's real gradient/contributing area into "
    "topographic_factor, and correctly degrades zone 1 (no overlapping valley) to None/None rather than "
    "crashing or reusing a stale valley_id join."
)

# Every zone find_candidate_zones() returns must still be a REAL,
# scoreable, non-zero candidate, even with no overlapping valley at all.
assert scored_by_id[1]["suitability_score"] > 0.0, "a zone with no overlapping valley must still score > 0, never be zeroed out"
print(f"A zone with no overlapping valley remains a real, scoreable, non-zero candidate: score={scored_by_id[1]['suitability_score']}/100.")

# rank is assigned over ALL returned zones, best-first, no exclusion.
assert len(best_case_scored) == 2
assert {z["rank"] for z in best_case_scored} == {1, 2}
assert next(z for z in best_case_scored if z["rank"] == 1)["id"] == 0
print("rank is assigned over all returned zones (no MIN_SUITABILITY_SCORE-style exclusion).")


# --- confidence differentiation: same zone, different data availability ---

both_available = score_water_zones([zone0], VALLEYS, WATER_SUITABILITY_DEM, {0: GOOD_SOIL}, {0: GOOD_STREAM})[0]
one_available = score_water_zones([zone0], VALLEYS, WATER_SUITABILITY_DEM, {0: GOOD_SOIL}, {})[0]
none_available = score_water_zones([zone0], VALLEYS, WATER_SUITABILITY_DEM, {}, {})[0]

assert both_available["confidence"] == "high"
assert one_available["confidence"] == "medium"
assert none_available["confidence"] == "low"
assert both_available["confidence"] != one_available["confidence"] != none_available["confidence"]
print(
    f"Confidence genuinely differentiates by real data availability for the SAME zone: "
    f"both-available={both_available['confidence']}, one-available={one_available['confidence']}, "
    f"none-available={none_available['confidence']} -- no longer a flat 'low' across the board."
)

# Confidence also differs ACROSS zones within one scoring call when their
# real data genuinely differs -- the actual scenario the live property run
# needs to demonstrate.
mixed_scored = score_water_zones(
    [zone0, zone1], VALLEYS, WATER_SUITABILITY_DEM,
    soil_data_by_zone_id={0: GOOD_SOIL},  # zone 1 absent -- never checked
    stream_data_by_zone_id={0: GOOD_STREAM, 1: None},  # zone 1 checked, none found
)
mixed_by_id = {z["id"]: z for z in mixed_scored}
assert mixed_by_id[0]["confidence"] == "high"
assert mixed_by_id[1]["confidence"] == "low"
assert mixed_by_id[0]["confidence"] != mixed_by_id[1]["confidence"]
print(f"Confidence differs across candidates in the SAME run: zone 0={mixed_by_id[0]['confidence']}, zone 1={mixed_by_id[1]['confidence']}.")


# --- gravity confidence_notes framing: plain tradeoff, not an apology ---
#
# A dedicated below-elevation (pump-required) scenario: the same two
# drainage columns, but served by a HIGH-elevation production area so
# both zones sit below it.
BELOW_PRODUCTION_AREAS = [
    {"id": 0, "representative_elevation_m": 100.0, "polygon_utm": box(500080.0, 4499750.0, 500120.0, 4499800.0)}
]
below_zones = find_candidate_zones(WATER_SUITABILITY_DEM, BELOW_PRODUCTION_AREAS, BOUNDARY)
below_zone = next(z for z in below_zones if z["id"] == 0)
below_scored = score_water_zones([below_zone], [], WATER_SUITABILITY_DEM)[0]
assert below_scored["primary_production_area_relationship"]["above_production_area"] is False
assert below_scored["suitability_score"] > 0.0, "a below-elevation (pump-required) candidate must still score > 0, never be zeroed out"
print(f"Below-elevation (pump-required) candidate remains a real, scoreable, non-zero candidate: score={below_scored['suitability_score']}/100.")

below_notes = below_scored["confidence_notes"].lower()
assert "pump" in below_notes
assert "cost/maintenance tradeoff" in below_notes or "tradeoff" in below_notes
apology_phrases = ["unfortunately", "sadly", "poor choice", "bad site", "should be avoided"]
assert not any(phrase in below_notes for phrase in apology_phrases), (
    "below-elevation confidence_notes must state the pump tradeoff plainly, not apologize for it"
)
print("Below-elevation candidate's confidence_notes states the pump tradeoff plainly, without apologizing for it.")

nhd_offset_zone = scored_by_id[0]  # has a real, close, in-range stream
assert "100-300m" in nhd_offset_zone["confidence_notes"], "NHD offset limitation must be stated when stream proximity meaningfully affects score"
print("NHD 100-300m DEM-offset limitation is stated in confidence_notes when stream proximity meaningfully affects the score.")


# --- output is a schema-valid FeatureCollection on the required layer ---

geojson = water_suitability_to_geojson(best_case_scored)
validate_feature_collection(geojson)
confidences_seen = {f["properties"]["confidence"] for f in geojson["features"]}
for feature in geojson["features"]:
    assert feature["properties"]["layer"] == "water_system_candidate"
    assert "suitability_score" in feature["properties"]
    assert "gravity_feed_factor" in feature["properties"]
    assert "soil_water_holding_factor" in feature["properties"]
    assert "stream_permanence_factor" in feature["properties"]
    assert "topographic_factor" in feature["properties"]
print(f"water_suitability_to_geojson() output is schema-valid, layer='water_system_candidate', confidences observed: {confidences_seen}.")


# --- offline full-pipeline wiring check (synthetic DEM, no network) ----

import numpy as np
from rasterio.warp import transform as warp_transform

from dem_data import _utm_epsg_for_lonlat

CENTER_LON, CENTER_LAT = -79.98, 40.64
EPSG = _utm_epsg_for_lonlat(CENTER_LON, CENTER_LAT)
DST_CRS = f"EPSG:{EPSG}"
center_x, center_y = warp_transform("EPSG:4326", DST_CRS, [CENTER_LON], [CENTER_LAT])
center_x, center_y = center_x[0], center_y[0]

RESOLUTION = 5.0
SIZE = 40
HALF_EXTENT = SIZE * RESOLUTION / 2
origin_x = center_x - HALF_EXTENT
origin_y = center_y + HALF_EXTENT

utm_corners_x = [origin_x, origin_x + SIZE * RESOLUTION, origin_x + SIZE * RESOLUTION, origin_x, origin_x]
utm_corners_y = [origin_y, origin_y, origin_y - SIZE * RESOLUTION, origin_y - SIZE * RESOLUTION, origin_y]
lons, lats = warp_transform(DST_CRS, "EPSG:4326", utm_corners_x, utm_corners_y)
boundary_coordinates = list(zip(lons, lats))

array = np.zeros((SIZE, SIZE), dtype=np.float32)
for row in range(SIZE):
    for col in range(SIZE):
        if row >= SIZE - 8:
            array[row, col] = 100.0
        else:
            distance_from_center_col = abs(col - SIZE // 2)
            array[row, col] = 100.0 + (SIZE - 8 - row) * 3.0 + distance_from_center_col * 1.5

synthetic_dem = {
    "array": array,
    "resolution_meters": (RESOLUTION, RESOLUTION),
    "origin_x": origin_x,
    "origin_y": origin_y,
    "crs": DST_CRS,
}

# identify_water_suitability() calls production_area.identify_production_areas()
# internally with no check_soil/check_canopy passthrough of its own (water_suitability.py
# is unchanged by the canopy-gate work) -- and that gate is now mandatory, with a fetch
# failure raising rather than degrading. Patched here (production_area's own module-level
# name, which is what identify_production_areas() actually looks up) to a fixed offline
# stub so this wiring check stays fully offline; the gate's own hard-failure behavior has
# its own dedicated tests in test_canopy_height_data.py.
def _fake_clean_canopy(boundary_coordinates, dem):
    return {
        "array": np.full(dem["array"].shape, 1.0, dtype=np.float32),  # below threshold everywhere -- no trees
        "resolution_meters": dem["resolution_meters"],
        "origin_x": dem["origin_x"],
        "origin_y": dem["origin_y"],
        "crs": dem["crs"],
        "source_item_id": "offline-test-stub",
    }


pa.get_canopy_height_for_boundary = _fake_clean_canopy

# The existing-road exclusion gate is optional (degrades gracefully, unlike canopy) but
# still defaults to check_roads=True and attempts a real fetch otherwise -- stubbed the
# same way, to "no roads found nearby" (None), so this wiring check stays fully offline.
pa.get_road_exclusion_union_utm = lambda boundary_coordinates, dem: None

pipeline_result = identify_water_suitability(
    boundary_coordinates, dem=synthetic_dem, check_soil=False, check_streams=False,
    zone_kwargs={"min_boundary_setback_meters": 5.0},
)
validate_feature_collection(pipeline_result["zones_geojson"])
assert len(pipeline_result["scored_zones"]) >= 1, "expected at least one scored water system candidate zone"
for zone in pipeline_result["scored_zones"]:
    assert zone["confidence"] == "low", "with both soil and stream checks disabled, confidence must fall back to low"
    assert zone["soil_data_available"] is False
    assert zone["stream_data_available"] is False
print(f"identify_water_suitability() full pipeline wiring works end-to-end offline: {len(pipeline_result['scored_zones'])} scored zone(s), check_soil/check_streams=False correctly yields confidence='low'.")

print("\nAll water_suitability checks passed.")
