"""
test_water_suitability.py

Offline (no-network) checks for water_suitability.py's per-factor scoring
and weighted composite ranking. Same "pure logic, independent of real data
fetches" approach as test_production_suitability.py/test_solar_suitability.py:
score_water_zones() is exercised directly against real zones generated by
find_candidate_zones() from a small synthetic DEM (water_candidate_zones.py's
cell-based rearchitecture means zones no longer carry a valley_id to hand-
build a matching fixture around -- see test_water_candidate_zones.py's own
docstring for the same reasoning) plus hand-built pre-fetched soil dicts,
with no network calls anywhere in this file except the final offline wiring
check (identify_water_suitability() with check_soil=False and a synthetic
dem= passed directly, mirroring test_water_system_candidate_pipeline.py's
approach).

THE FACTOR SET IS THREE NOW: gravity, soil, basin shape. The stream-
permanence and topographic factors were DELETED (see water_suitability.py's
own docstring for why each), and this file asserts their absence by name --
a deleted factor that leaves a stale constant or a stale output field
behind is a factor that can be accidentally revived.

The basin-shape units below are hand-computed against synthetic
measurement sets rather than real generated zones: the factor reads only
the abutment results and the cross-section station table, so a minimal
dict IS the whole input, and a hand value is checkable by a reader in a
way a number derived from a real DEM run is not.

The "--- boundary_polygon_utm/valleys/production_areas overrides ---"
section near the end covers identify_water_suitability()'s own
dem/boundary_polygon_utm/valleys/production_areas override plumbing
(mirroring water_candidate_zones.identify_water_system_candidate_zones()'s
own override tests) AND the real behavior change this branch makes: the
production_areas self-compute fallback now sources production_area_
ceiling.identify_optimized_production_areas()'s scored_patches, not
production_area.identify_production_areas()'s raw patches -- see
water_suitability.py's own module docstring for why. Same mock_patch.object
usage against the module's own imported bindings (patch where it's looked
up, not where it's defined) as test_pipeline_context.py already
establishes.
"""

import json
import os
import tempfile
from unittest.mock import patch as mock_patch

import numpy as np
from shapely.geometry import Point as _ValleyPoint
from shapely.geometry import box, shape as _shape

import production_area as pa
import water_candidate_zones as wcz
import water_suitability as ws
from feature_schema import validate_feature_collection
from raster_grid import pixel_center_xy as _pxy
from valley_delineation import (
    compute_flow_direction as _compute_flow_direction,
    fill_depressions as _fill_depressions,
)
from water_candidate_zones import find_candidate_zones
from valley_level_pool import ABUTMENT_SEARCH_HALF_WIDTH_METERS
from water_suitability import (
    BASIN_SHAPE_SCORE_WEIGHT,
    GRAVITY_FEED_SCORE_WEIGHT,
    GRAVITY_FULL_CREDIT_GRADIENT_PCT,
    GRAVITY_LEVEL_GROUND_FACTOR,
    GRAVITY_MAX_DEFICIT_GRADIENT_PCT,
    GRAVITY_MIN_FACTOR,
    GRAVITY_ZERO_DISTANCE_FULL_CREDIT_METERS,
    GRAVITY_ZERO_DISTANCE_MAX_DEFICIT_METERS,
    MIN_MEASURED_STATIONS_FOR_PERSISTENCE,
    PERSISTENCE_REFERENCE_RATIO,
    SOIL_WATER_HOLDING_SCORE_WEIGHT,
    WATER_HOLDING_GOOD_KSAT_UM_PER_S,
    WATER_HOLDING_POOR_KSAT_UM_PER_S,
    WATER_HOLDING_UNAVAILABLE_FACTOR,
    WATER_ZONE_PRESENTATION_TOP_N,
    _WEIGHT_SUM,
    _basin_shape_factor,
    _gravity_feed_factor,
    _production_overlap_pct,
    _water_holding_factor,
    build_narrative_data,
    fetch_and_select_optimal_water_zone,
    identify_water_suitability,
    score_water_zones,
    select_optimal_water_zone,
    water_suitability_to_geojson,
)

CRS = "EPSG:32617"

assert abs(_WEIGHT_SUM - 1.0) < 1e-6, f"composite weights must sum to 1.0, got {_WEIGHT_SUM}"
assert (GRAVITY_FEED_SCORE_WEIGHT, SOIL_WATER_HOLDING_SCORE_WEIGHT, BASIN_SHAPE_SCORE_WEIGHT) == (
    0.35, 0.30, 0.35
), "the decided weights are 0.35 / 0.30 / 0.35 -- delivery, holding, geometry"
assert WATER_ZONE_PRESENTATION_TOP_N == 3
print(
    f"Composite factor weights sum to 1.0 over THREE factors: gravity {GRAVITY_FEED_SCORE_WEIGHT}, "
    f"soil {SOIL_WATER_HOLDING_SCORE_WEIGHT}, basin shape {BASIN_SHAPE_SCORE_WEIGHT}."
)


# --- _gravity_feed_factor(): continuous, monotonic, never truly zero ----
# --- (distance_m > 0 case: scores off gradient_pct, the original scale) --

# distance_m is nonzero (100.0) and elevation_differential_m is irrelevant
# in this branch -- only gradient_pct drives the score when distance_m > 0.
assert _gravity_feed_factor(999.0, 100.0, GRAVITY_FULL_CREDIT_GRADIENT_PCT) == 1.0
assert _gravity_feed_factor(999.0, 100.0, GRAVITY_FULL_CREDIT_GRADIENT_PCT * 5) == 1.0, "extra-comfortable gradient still caps at 1.0"
assert _gravity_feed_factor(999.0, 100.0, 0.0) == GRAVITY_LEVEL_GROUND_FACTOR
assert _gravity_feed_factor(999.0, 100.0, GRAVITY_MAX_DEFICIT_GRADIENT_PCT) == GRAVITY_MIN_FACTOR
assert _gravity_feed_factor(999.0, 100.0, GRAVITY_MAX_DEFICIT_GRADIENT_PCT * 5) == GRAVITY_MIN_FACTOR, "extreme deficit floors, doesn't go below GRAVITY_MIN_FACTOR"
assert GRAVITY_MIN_FACTOR > 0.0, "a below-elevation (pump-required) candidate must never score literally 0 on this factor"
mild_above = _gravity_feed_factor(999.0, 100.0, 0.5)
mild_below = _gravity_feed_factor(999.0, 100.0, -1.0)
assert GRAVITY_LEVEL_GROUND_FACTOR < mild_above < 1.0
assert GRAVITY_MIN_FACTOR < mild_below < GRAVITY_LEVEL_GROUND_FACTOR
assert (
    _gravity_feed_factor(999.0, 100.0, 1.0) > _gravity_feed_factor(999.0, 100.0, 0.0)
    > _gravity_feed_factor(999.0, 100.0, -1.0) > _gravity_feed_factor(999.0, 100.0, -5.0)
)
print("_gravity_feed_factor() is continuous/monotonic and never zero (distance_m > 0, gradient_pct-driven case).")


# --- _gravity_feed_factor(): distance_m == 0 case -- real bug, fixed ----
#
# Live-confirmed bug: with distance_m == 0 (a zone sitting inside/touching
# a production area — a real, common case that water-zone eligibility does
# not reject, applying no minimum-service-distance gate), water_candidate_
# zones.py reports gradient_pct as a
# 0.0 div-by-zero placeholder, NOT a real 0% grade. Scoring directly off
# that placeholder collapsed every distance-0 zone to the same
# GRAVITY_LEVEL_GROUND_FACTOR (0.6), regardless of real elevation_differential_m
# -- on the real property, a +7.01m (strong gravity-feed), a +0.63m (barely
# above), and a -8.68m (pump-required) zone all scored identically. Fixed:
# distance_m == 0 must score off elevation_differential_m directly, not
# gradient_pct.

real_property_valley4 = _gravity_feed_factor(7.01, 0.0, 0.0)   # strong gravity-feed
real_property_valley2 = _gravity_feed_factor(0.63, 0.0, 0.0)   # barely above
real_property_valley11 = _gravity_feed_factor(-8.68, 0.0, 0.0)  # pump-required

assert real_property_valley4 > real_property_valley2 > real_property_valley11, (
    f"real, differentiated elevation differentials at distance_m==0 must score in the correct rank order -- got "
    f"valley4={real_property_valley4}, valley2={real_property_valley2}, valley11={real_property_valley11}"
)
assert real_property_valley11 > 0.0, "even the pump-required zone must never score literally 0 on this factor"
print(
    f"REGRESSION (real property scenario, all distance_m==0): gravity_feed_factor correctly differentiates "
    f"by elevation_differential_m alone -- valley4 (+7.01m)={real_property_valley4} > "
    f"valley2 (+0.63m)={real_property_valley2} > valley11 (-8.68m)={real_property_valley11}."
)

assert _gravity_feed_factor(GRAVITY_ZERO_DISTANCE_FULL_CREDIT_METERS, 0.0, 0.0) == 1.0
assert _gravity_feed_factor(0.0, 0.0, 0.0) == GRAVITY_LEVEL_GROUND_FACTOR
assert _gravity_feed_factor(GRAVITY_ZERO_DISTANCE_MAX_DEFICIT_METERS, 0.0, 0.0) == GRAVITY_MIN_FACTOR
assert _gravity_feed_factor(GRAVITY_ZERO_DISTANCE_MAX_DEFICIT_METERS * 5, 0.0, 0.0) == GRAVITY_MIN_FACTOR
print("_gravity_feed_factor() at distance_m==0 hits the same real reference breakpoints (full credit / level / max deficit).")

# A gradient_pct of 0.0 alongside a nonzero distance_m must still be
# treated as a genuine, real 0% grade (level ground), NOT collapsed to the
# distance==0 meters-based path -- confirms the dispatch is keyed strictly
# off distance_m, not off gradient_pct happening to read 0.0.
assert _gravity_feed_factor(7.01, 50.0, 0.0) == GRAVITY_LEVEL_GROUND_FACTOR
print("A real, nonzero distance with a genuine 0% gradient still scores as level ground, not the distance==0 path.")


# --- _water_holding_factor(): log-scale, real NRCS breakpoints ----------

assert _water_holding_factor(WATER_HOLDING_GOOD_KSAT_UM_PER_S) == 1.0
assert _water_holding_factor(WATER_HOLDING_GOOD_KSAT_UM_PER_S / 10) == 1.0, "even better (lower) than the good reference still caps at 1.0"
assert _water_holding_factor(WATER_HOLDING_POOR_KSAT_UM_PER_S) == 0.0
assert _water_holding_factor(WATER_HOLDING_POOR_KSAT_UM_PER_S * 10) == 0.0
assert _water_holding_factor(None) == WATER_HOLDING_UNAVAILABLE_FACTOR
mid_ksat = (WATER_HOLDING_GOOD_KSAT_UM_PER_S * WATER_HOLDING_POOR_KSAT_UM_PER_S) ** 0.5  # geometric midpoint
mid_score = _water_holding_factor(mid_ksat)
assert 0.4 < mid_score < 0.6, f"log-scale geometric midpoint should score near 0.5, got {mid_score}"
assert _water_holding_factor(1.0) > _water_holding_factor(10.0) > _water_holding_factor(50.0)
print("_water_holding_factor() scores real ksat_r on a log scale between the documented NRCS breakpoints, unavailable defaults neutral.")


# =====================================================================
# TEST 1 -- BASIN SHAPE UNITS, every subcomponent hand-computed.
#
# The factor reads exactly four things off a zone: the two abutment
# results, the two crosses-major-drainage flags, and the station table. A
# minimal dict IS the whole input, so every expectation below is checkable
# by hand against the constants.
# =====================================================================
_WINDOW_M = 2.0 * ABUTMENT_SEARCH_HALF_WIDTH_METERS   # 150.0 m at the module default


def _station(index, area, width, status="measured", offset=None):
    """One entry in valley_level_pool.py's own station table shape. An
    unreachable station carries None for BOTH width and area -- that is
    the status contract, and the whole point of the exclusion below."""
    return {
        "station_index": index,
        "offset_upstream_m": 25.0 * index if offset is None else offset,
        "status": status,
        "flooded_width_m": width,
        "flooded_cross_section_area_m2": area,
    }


def _basin_zone(stations, left=True, right=True, crosses_left=False, crosses_right=False):
    return {
        "abutment_found_left": left,
        "abutment_found_right": right,
        "dam_band_crosses_major_drainage_left": crosses_left,
        "dam_band_crosses_major_drainage_right": crosses_right,
        "level_pool": {"stations": stations, "stem_direction_degenerate": False},
    }


# --- enclosure: both / one / neither ---
_FLAT_STATIONS = [_station(0, 10.0, 50.0), _station(1, 5.0, 30.0), _station(2, 5.0, 30.0)]

_both = _basin_shape_factor(_basin_zone(_FLAT_STATIONS, left=True, right=True))
_one = _basin_shape_factor(_basin_zone(_FLAT_STATIONS, left=True, right=False))
_none = _basin_shape_factor(_basin_zone(_FLAT_STATIONS, left=False, right=False))
assert _both["enclosure_score"] == 1.0
assert _one["enclosure_score"] == 0.5
assert _none["enclosure_score"] == 0.0
assert _both["basin_shape_factor"] > _one["basin_shape_factor"] > _none["basin_shape_factor"]

# A side that CROSSES A MAJOR DRAINAGE counts as NOT FOUND, even though
# the abutment search itself reported found. A second creek is not a
# shoulder -- damming across it is a different, larger structure.
_crossed = _basin_shape_factor(_basin_zone(_FLAT_STATIONS, left=True, right=True, crosses_right=True))
assert _crossed["enclosure_score"] == 0.5, (
    "a found-but-crossing side must score as NOT found -- otherwise the finding that most "
    "disqualifies a site is counted as the one that most qualifies it"
)
_both_crossed = _basin_shape_factor(
    _basin_zone(_FLAT_STATIONS, left=True, right=True, crosses_left=True, crosses_right=True)
)
assert _both_crossed["enclosure_score"] == 0.0

# --- persistence: the reference-run ratio as a literal ---
# Areas 41.0 / 6.0 / 3.0 -> total 50.0, upstream share (6+3)/50 = 0.18 --
# the reference property's confluence candidate, pasted as a literal so a
# retune of PERSISTENCE_REFERENCE_RATIO shows up here as a changed score
# against an UNCHANGED measurement.
_REFERENCE_RUN_STATIONS = [_station(0, 41.0, 150.0), _station(1, 6.0, 40.0), _station(2, 3.0, 30.0)]
_reference = _basin_shape_factor(_basin_zone(_REFERENCE_RUN_STATIONS))
assert abs(_reference["persistence_ratio"] - 0.18) < 1e-9, _reference["persistence_ratio"]
assert abs(_reference["persistence_score"] - 0.18 / PERSISTENCE_REFERENCE_RATIO) < 1e-9
assert abs(_reference["persistence_score"] - 0.72) < 1e-9, (
    "r = 0.18 against a 0.25 reference is 0.72 -- stated here as the literal it is"
)

# A swale: everything against the dam line, bone dry 25 m upstream.
_SWALE_STATIONS = [_station(0, 30.0, 150.0), _station(1, 0.0, 0.0), _station(2, 0.0, 0.0)]
_swale = _basin_shape_factor(_basin_zone(_SWALE_STATIONS))
assert _swale["persistence_ratio"] == 0.0 and _swale["persistence_score"] == 0.0

# At and above the reference ratio the component saturates at 1.0.
_SATURATED = [_station(0, 10.0, 50.0), _station(1, 10.0, 50.0), _station(2, 10.0, 50.0)]
assert _basin_shape_factor(_basin_zone(_SATURATED))["persistence_score"] == 1.0

# --- wall economy: clamp at the full window ---
_FULL_WINDOW = [_station(0, 40.0, _WINDOW_M), _station(1, 5.0, 20.0), _station(2, 5.0, 20.0)]
_full = _basin_shape_factor(_basin_zone(_FULL_WINDOW))
assert _full["wall_economy_score"] == 0.0, (
    "water filling the whole sampling window at the dam line means a full-width wall -- 0.0, and "
    "honestly so even on a genuinely good basin"
)
_OVERFLOW = [_station(0, 40.0, _WINDOW_M * 3), _station(1, 5.0, 20.0), _station(2, 5.0, 20.0)]
assert _basin_shape_factor(_basin_zone(_OVERFLOW))["wall_economy_score"] == 0.0, "clamped, never negative"
_NARROW = [_station(0, 10.0, _WINDOW_M / 3), _station(1, 5.0, 20.0), _station(2, 5.0, 20.0)]
assert abs(_basin_shape_factor(_basin_zone(_NARROW))["wall_economy_score"] - (1.0 - 1.0 / 3.0)) < 1e-9

# --- unreachable stations are EXCLUDED, and the subweights renormalize ---
#
# Two stations unreachable leaves ONE measured, below
# MIN_MEASURED_STATIONS_FOR_PERSISTENCE, so persistence is not computable:
# dropped, not zeroed. The surviving two thirds renormalize to halves, so
# the factor is the plain mean of enclosure and wall economy.
_UNREACHABLE = [
    _station(0, 20.0, _WINDOW_M / 2),
    _station(1, None, None, status="unreachable_stem_end"),
    _station(2, None, None, status="unreachable_stem_end"),
]
_short = _basin_shape_factor(_basin_zone(_UNREACHABLE, left=True, right=False))
assert _short["persistence_score"] is None and _short["persistence_ratio"] is None
assert _short["persistence_available"] is False
_expected_wall = 1.0 - 0.5
assert abs(_short["basin_shape_factor"] - (0.5 + _expected_wall) / 2.0) < 1e-9, (
    "with persistence dropped, the remaining two equal subweights renormalize to halves"
)
# The renormalized factor still spans 0-1 -- a short stem is neither
# rewarded nor punished for the reading nobody could take.
_short_perfect = _basin_shape_factor(
    _basin_zone(
        [_station(0, 20.0, 0.0)] + [_station(i, None, None, status="unreachable_stem_end") for i in (1, 2)]
    )
)
assert abs(_short_perfect["basin_shape_factor"] - 1.0) < 1e-9

# Zeroing an unreachable station instead of excluding it would give a
# DIFFERENT, WRONG answer -- asserted as the contrast, not assumed.
_ZEROED_INSTEAD = [_station(0, 20.0, _WINDOW_M / 2), _station(1, 0.0, 0.0), _station(2, 0.0, 0.0)]
_zeroed = _basin_shape_factor(_basin_zone(_ZEROED_INSTEAD, left=True, right=False))
assert _zeroed["persistence_score"] == 0.0
assert _zeroed["basin_shape_factor"] < _short["basin_shape_factor"], (
    "treating an ABSENT measurement as a DRY one would penalize a candidate for ground nobody looked "
    "at -- the exclusion exists precisely so it does not"
)

# Exactly MIN_MEASURED_STATIONS_FOR_PERSISTENCE measured is enough.
_TWO_MEASURED = [
    _station(0, 10.0, 50.0), _station(1, 10.0, 50.0),
    _station(2, None, None, status="unreachable_stem_end"),
]
assert _basin_shape_factor(_basin_zone(_TWO_MEASURED))["persistence_score"] is not None
assert MIN_MEASURED_STATIONS_FOR_PERSISTENCE == 2

# All-zero measured area is an absence of anything to take a ratio OF,
# not a ratio of zero.
_ALL_DRY = [_station(0, 0.0, 0.0), _station(1, 0.0, 0.0), _station(2, 0.0, 0.0)]
assert _basin_shape_factor(_basin_zone(_ALL_DRY))["persistence_score"] is None

print(
    f"Test 1 -- basin shape units: enclosure both/one/neither = 1.0/0.5/0.0 with a crossing side "
    f"counted as NOT found; the reference run's r=0.18 scores {round(_reference['persistence_score'], 3)} "
    f"against the {PERSISTENCE_REFERENCE_RATIO} reference while a swale scores 0.0; wall economy clamps "
    f"to 0.0 at the full {_WINDOW_M}m window; unreachable stations are EXCLUDED and the subweights "
    "renormalize, which scores strictly higher than zeroing them would."
)


# --- score_water_zones(): full composite, using REAL zones generated by ---
# --- find_candidate_zones() from a small synthetic DEM (cell-based       ---
# --- rearchitecture: no more valley_id to hand-build a matching zone     ---
# --- fixture around -- see test_water_candidate_zones.py)                ---
#
# find_candidate_zones() returns every surviving candidate now -- there is
# no generation cap at all. To get the two distinct real zone dicts these
# scoring tests need, we run it on two SEPARATE single-drainage-column DEMs
# (channel at col=8 and at col=32 of a 40x40 grid, 5m), sharing one UTM
# frame, with the family-2 seed budget pinned to 1 and no keypoints
# supplied, so each run yields exactly one zone; their ids are then
# relabelled 0/1.
BOUNDARY = box(500000.0, 4499800.0, 500200.0, 4500000.0)
_size = 40
_FRAME = {"resolution_meters": (5.0, 5.0), "origin_x": 500000.0, "origin_y": 4500000.0, "crs": CRS}


def _single_column_dem(mid_col):
    arr = np.zeros((_size, _size), dtype=np.float32)
    for r in range(_size):
        for c in range(_size):
            arr[r, c] = abs(c - mid_col) * 2.0 + r * 0.5
    return {"array": arr, **_FRAME}


# A two-column DEM retained as the `dem` argument for the scoring calls
# below (score_water_zones() reads geometry from the zone dicts, not per-
# cell from this dem) and for the below-elevation run further down.
_array = np.zeros((_size, _size), dtype=np.float32)
for _row in range(_size):
    for _col in range(_size):
        _array[_row, _col] = min(abs(_col - 8), abs(_col - 32)) * 2.0 + _row * 0.5
WATER_SUITABILITY_DEM = {"array": _array, **_FRAME}

PRODUCTION_AREAS = [
    {
        "id": 0,
        "representative_elevation_m": -5.0,
        "polygon_utm": box(500080.0, 4499750.0, 500120.0, 4499800.0),
        "render_fill_polygon_utm": box(500080.0, 4499750.0, 500120.0, 4499800.0),
    }
]

_DEM_COL8 = _single_column_dem(8)
_DEM_COL32 = _single_column_dem(32)
_zones8 = find_candidate_zones(
    _DEM_COL8, PRODUCTION_AREAS, BOUNDARY, keypoints=[], accumulation_seed_budget=1
)
_zones32 = find_candidate_zones(
    _DEM_COL32, PRODUCTION_AREAS, BOUNDARY, keypoints=[], accumulation_seed_budget=1
)
assert len(_zones8) == 1 and len(_zones32) == 1, (
    f"each single-column DEM must yield exactly one zone at a family-2 budget of 1 with no keypoints, "
    f"got {len(_zones8)}/{len(_zones32)}"
)
zone_col8 = {**_zones8[0], "id": 0}
zone_col32 = {**_zones32[0], "id": 1}
assert zone_col8["polygon_utm"].bounds[0] < 500100.0 <= zone_col32["polygon_utm"].bounds[0], (
    "test setup: zone_col8 (channel at col=8) should sit west of zone_col32 (channel at col=32)"
)
ZONE_A_ID = zone_col8["id"]   # 0
ZONE_B_ID = zone_col32["id"]  # 1

GOOD_SOIL = {"ksat_r_um_per_s": 0.05, "coverage_fraction": 0.9}
POOR_SOIL = {"ksat_r_um_per_s": 300.0, "coverage_fraction": 0.9}

best_case_scored = score_water_zones(
    [zone_col8, zone_col32],
    WATER_SUITABILITY_DEM,
    soil_data_by_zone_id={ZONE_A_ID: GOOD_SOIL, ZONE_B_ID: POOR_SOIL},
)
scored_by_id = {z["id"]: z for z in best_case_scored}
assert scored_by_id[ZONE_A_ID]["suitability_score"] > scored_by_id[ZONE_B_ID]["suitability_score"], (
    "identical landform, better soil -- the soil factor must be what separates them"
)
assert len(best_case_scored) == 2 and {z["rank"] for z in best_case_scored} == {1, 2}
assert next(z for z in best_case_scored if z["rank"] == 1)["id"] == ZONE_A_ID
assert scored_by_id[ZONE_B_ID]["suitability_score"] > 0.0, "a low-scoring candidate is never zeroed out"
print(
    f"rank is assigned over all returned zones with no cutoff: good soil {scored_by_id[ZONE_A_ID]['suitability_score']}"
    f"/100 outranks poor soil {scored_by_id[ZONE_B_ID]['suitability_score']}/100 on otherwise identical landform."
)


# =====================================================================
# TEST 2 -- RANKING INTEGRATION: a confluence-like site outranks a swale.
#
# The two candidates differ ONLY in their level-pool measurements -- same
# gravity relationship, same soil, same footprint. So the ordering below
# is the basin factor doing its job and nothing else, which is the whole
# claim this factor was added to make.
#
# CONFLUENCE-LIKE: both shoulders found, section area persisting upstream
# (r = 0.18, the reference-run literal), but water filling the full window
# at the dam line -> wall economy 0.0. Basin = (1.0 + 0.72 + 0.0)/3 = 0.573.
# SWALE-LIKE: no shoulders, everything against the wall, dry upstream ->
# (0.0 + 0.0 + wall economy)/3.
# =====================================================================
def _with_measurements(zone, stations, left, right):
    patched = dict(zone)
    patched["level_pool"] = {**zone["level_pool"], "stations": stations, "stem_direction_degenerate": False}
    patched["abutment_found_left"] = left
    patched["abutment_found_right"] = right
    patched["dam_band_crosses_major_drainage_left"] = False
    patched["dam_band_crosses_major_drainage_right"] = False
    return patched


_CONFLUENCE = _with_measurements({**zone_col8, "id": 0}, _REFERENCE_RUN_STATIONS, True, True)
# Same station-0 width as the confluence, so wall economy is IDENTICAL on
# both and cannot be what separates them.
_SWALE = _with_measurements(
    {**zone_col32, "id": 1},
    [_station(0, 30.0, 150.0), _station(1, 0.0, 0.0), _station(2, 0.0, 0.0)],
    False,
    False,
)
_rank_scored = score_water_zones([_CONFLUENCE, _SWALE], WATER_SUITABILITY_DEM)
_rank_by_id = {z["id"]: z for z in _rank_scored}
_c, _sw = _rank_by_id[0], _rank_by_id[1]
assert _c["gravity_feed_factor"] == _sw["gravity_feed_factor"], "test setup: gravity must not separate them"
assert _c["soil_water_holding_factor"] == _sw["soil_water_holding_factor"], "test setup: nor soil"
assert _c["basin_wall_economy_score"] == _sw["basin_wall_economy_score"] == 0.0, (
    "test setup: both flood the full window, so wall economy is identical AND zero on both"
)
assert _c["rank"] == 1 and _sw["rank"] == 2
assert _c["basin_shape_factor"] > _sw["basin_shape_factor"]
assert abs(_c["basin_shape_factor"] - (1.0 + 0.72 + 0.0) / 3.0) < 1e-3, _c["basin_shape_factor"]
assert _sw["basin_shape_factor"] == 0.0
print(
    f"Test 2 -- ranking integration: a confluence-like measurement set (both shoulders, r=0.18 "
    f"persisting) ranks 1 at {_c['suitability_score']}/100 over an otherwise-identical swale at "
    f"{_sw['suitability_score']}/100, basin {_c['basin_shape_factor']} vs {_sw['basin_shape_factor']}. "
    "Gravity, soil and wall economy are equal across the pair, so basin shape is provably what "
    "separated them -- including on a site whose own wall economy is an honest 0.0."
)


# =====================================================================
# TEST 3 -- NO-RELATIONSHIP CANDIDATES SURVIVE.
#
# A production area ~1 km away leaves every candidate with no service
# relationship. Generation no longer drops them (the temporary guard is
# gone); scoring gives gravity 0.0, a plain note and the informational
# flag, and they appear in the ranked output like anything else.
# =====================================================================
_FAR_PRODUCTION = [
    {
        "id": 9,
        "representative_elevation_m": -5.0,
        "polygon_utm": box(501200.0, 4499850.0, 501230.0, 4499900.0),
        "render_fill_polygon_utm": box(501200.0, 4499850.0, 501230.0, 4499900.0),
    }
]
_no_rel_zones = find_candidate_zones(
    _DEM_COL8, _FAR_PRODUCTION, BOUNDARY, keypoints=[], accumulation_seed_budget=1
)
assert _no_rel_zones, "generation must no longer drop a candidate for having nothing to serve"
_no_rel = score_water_zones(_no_rel_zones, WATER_SUITABILITY_DEM)
assert len(_no_rel) == len(_no_rel_zones), "every one of them must reach the ranked output"
for _z in _no_rel:
    assert _z["primary_production_area_relationship"] is None
    assert _z["gravity_feed_factor"] == 0.0, "no production area in range scores 0.0, honestly"
    assert _z["has_service_relationship"] is False
    assert wcz.FLAG_NO_SERVICE_RELATIONSHIP in _z["flags"]
    assert _z["rank"] >= 1
    assert _z["suitability_score"] > 0.0, "the site's own landform still scores"
    _notes = _z["confidence_notes"].lower()
    assert "no production area lies within this survey's service range" in _notes, _z["confidence_notes"]
    assert "distribution infrastructure this survey does not evaluate" in _notes
print(
    f"Test 3 -- no-relationship survival: {len(_no_rel)} candidate(s) with no production area in range "
    f"score gravity 0.0, carry the '{wcz.FLAG_NO_SERVICE_RELATIONSHIP}' flag and a plain note, and are "
    f"ranked (top score {max(z['suitability_score'] for z in _no_rel)}/100) rather than dropped."
)


# =====================================================================
# TEST 4 -- CONFIDENCE under the NEW signal pair: soil + measurement
# completeness. The stream signal is gone.
# =====================================================================
_COMPLETE = [_station(0, 20.0, 50.0), _station(1, 10.0, 30.0), _station(2, 5.0, 20.0)]
_INCOMPLETE = [_station(0, 20.0, 50.0), _station(1, None, None, status="unreachable_stem_end"),
               _station(2, None, None, status="unreachable_stem_end")]

_conf_complete = _with_measurements({**zone_col8, "id": 0}, _COMPLETE, True, True)
_conf_incomplete = _with_measurements({**zone_col8, "id": 0}, _INCOMPLETE, True, True)

_two_signals = score_water_zones([_conf_complete], WATER_SUITABILITY_DEM, {0: GOOD_SOIL})[0]
_one_soil_only = score_water_zones([_conf_incomplete], WATER_SUITABILITY_DEM, {0: GOOD_SOIL})[0]
_one_measurement_only = score_water_zones([_conf_complete], WATER_SUITABILITY_DEM, {})[0]
_zero_signals = score_water_zones([_conf_incomplete], WATER_SUITABILITY_DEM, {})[0]

assert _two_signals["confidence"] == "high"
assert _one_soil_only["confidence"] == "medium"
assert _one_measurement_only["confidence"] == "medium"
assert _zero_signals["confidence"] == "low"
assert _two_signals["measurement_complete"] is True and _one_soil_only["measurement_complete"] is False

# A thin soil sample is not a soil signal, even though the fetch succeeded.
_THIN_SOIL = {"ksat_r_um_per_s": 0.05, "coverage_fraction": 0.02}
assert score_water_zones([_conf_complete], WATER_SUITABILITY_DEM, {0: _THIN_SOIL})[0]["confidence"] == "medium"

# A degenerate stem direction breaks the measurement signal even when
# every station reported measured: the abutment walk went out along a
# fallback bearing, so neither side describes this valley's shoulders.
_degenerate = _with_measurements({**zone_col8, "id": 0}, _COMPLETE, True, True)
_degenerate["level_pool"] = {**_degenerate["level_pool"], "stem_direction_degenerate": True}
assert score_water_zones([_degenerate], WATER_SUITABILITY_DEM, {0: GOOD_SOIL})[0]["confidence"] == "medium"

# Neither abutment found is also not a completed measurement.
_no_abutments = _with_measurements({**zone_col8, "id": 0}, _COMPLETE, False, False)
assert score_water_zones([_no_abutments], WATER_SUITABILITY_DEM, {0: GOOD_SOIL})[0]["confidence"] == "medium"

# INCOMPLETENESS DENTS CONFIDENCE, NOT THE SCORE -- the renormalized basin
# factor is what makes that true, asserted rather than assumed.
_incomplete_basin = _one_soil_only["basin_shape_factor"]
assert _one_soil_only["basin_persistence_score"] is None
assert _incomplete_basin > 0.0, "a dropped persistence reading must not drag the factor toward zero"
print(
    "Test 4 -- confidence: soil coverage + measurement completeness are the two signals now (the "
    "stream signal is deleted). 2 -> high, 1 -> medium (either way round), 0 -> low; a 2% soil sample "
    "and a degenerate stem direction each fail their signal; and an incomplete measurement dents "
    f"confidence while leaving the basin factor at {round(_incomplete_basin, 3)} rather than zeroing it."
)


# =====================================================================
# TEST 5 -- PRODUCTION OVERLAP: reported, never scored, with the same
# None-vs-0.0 sentinels canopy and road already use.
# =====================================================================
_overlap_zone = {**zone_col8, "id": 0}
_OVERLAPPING_PRODUCTION = [
    {
        "id": 0,
        "representative_elevation_m": -5.0,
        "polygon_utm": _overlap_zone["polygon_utm"],
        "render_fill_polygon_utm": _overlap_zone["polygon_utm"],
    }
]
_unchecked = score_water_zones([_overlap_zone], WATER_SUITABILITY_DEM)[0]
_checked_clear = score_water_zones(
    [_overlap_zone], WATER_SUITABILITY_DEM, production_areas=_FAR_PRODUCTION
)[0]
_checked_full = score_water_zones(
    [_overlap_zone], WATER_SUITABILITY_DEM, production_areas=_OVERLAPPING_PRODUCTION
)[0]
_checked_empty_list = score_water_zones([_overlap_zone], WATER_SUITABILITY_DEM, production_areas=[])[0]

assert _unchecked["production_overlap_pct"] is None, "no production geometry supplied = NEVER CHECKED"
assert _checked_clear["production_overlap_pct"] == 0.0, "checked, genuinely none -- a real 0.0, not None"
assert _checked_empty_list["production_overlap_pct"] == 0.0
assert _checked_full["production_overlap_pct"] == 100.0
# Half-overlap, hand-checkable against the zone's own bounds.
_minx, _miny, _maxx, _maxy = _overlap_zone["polygon_utm"].bounds
_HALF = [
    {
        "id": 0,
        "representative_elevation_m": -5.0,
        "polygon_utm": box(_minx, _miny, _maxx, (_miny + _maxy) / 2),
        "render_fill_polygon_utm": box(_minx, _miny, _maxx, (_miny + _maxy) / 2),
    }
]
_checked_half = score_water_zones([_overlap_zone], WATER_SUITABILITY_DEM, production_areas=_HALF)[0]
assert 0.0 < _checked_half["production_overlap_pct"] < 100.0

# NOT SCORED: the score is byte-identical across all four overlap states.
_scores = {
    _unchecked["suitability_score"], _checked_clear["suitability_score"],
    _checked_full["suitability_score"], _checked_half["suitability_score"],
}
assert len(_scores) == 1, (
    f"production overlap must not move the score by one point -- it is a land-use tradeoff the "
    f"farmer weighs, not a defect in the ground. Saw {_scores}"
)
# Measured against render_fill_polygon_utm, the geometry the map draws.
assert _production_overlap_pct(_overlap_zone["polygon_utm"], None) is None
assert _production_overlap_pct(_overlap_zone["polygon_utm"], _OVERLAPPING_PRODUCTION) == 100.0
_notes = _checked_full["confidence_notes"]
assert "Reported, NOT scored" in _notes and "selected production ground 100.0%" in _notes
print(
    "Test 5 -- production overlap: None when unchecked, a real 0.0 when checked and clear, 100.0% on a "
    f"full overlap and {_checked_half['production_overlap_pct']}% on a half one -- and the suitability "
    f"score is IDENTICAL ({_unchecked['suitability_score']}) across all four, because it is reported, "
    "never scored."
)


# =====================================================================
# TEST 6 -- PRESENTATION TOP_N, and rank-1 selection unchanged.
# =====================================================================
_topn_zones = [
    _with_measurements(
        {**zone_col8, "id": i},
        [_station(0, 30.0 - i, 50.0 + i), _station(1, 10.0, 30.0), _station(2, 5.0, 20.0)],
        True,
        True,
    )
    for i in range(WATER_ZONE_PRESENTATION_TOP_N + 3)
]
_topn_scored = score_water_zones(_topn_zones, WATER_SUITABILITY_DEM)
assert len(_topn_scored) == WATER_ZONE_PRESENTATION_TOP_N + 3
_nd = build_narrative_data(_topn_scored)
assert _nd["candidate_count"] == len(_topn_scored), "the TOTAL is stated, so the trim is visible"
assert _nd["presented_count"] == WATER_ZONE_PRESENTATION_TOP_N
assert len(_nd["zones"]) == WATER_ZONE_PRESENTATION_TOP_N
assert [z["rank"] for z in _nd["zones"]] == list(range(1, WATER_ZONE_PRESENTATION_TOP_N + 1)), (
    "the N described are the top N BY RANK, in rank order"
)
assert json.loads(json.dumps(_nd)) == _nd, "narrative_data must survive a plain json round trip"
for _z in _nd["zones"]:
    assert set(_z["factors"]) == {"gravity_feed", "soil_water_holding", "basin_shape"}
    assert set(_z["overlaps"]) == {"canopy_pct", "road_pct", "production_pct"}
    assert "wall_offset_downstream_ft" in _z["provenance"] and "nominated_by" in _z["provenance"]

# RANK-1 SELECTION IS UNCHANGED: the same zone as the full-list max, and
# the trim never touches it.
_selected = select_optimal_water_zone(_topn_scored)
_brute_max = max(_topn_scored, key=lambda z: z["suitability_score"])
assert _selected is _brute_max, "select_optimal_water_zone() must still be the plain full-list max"
assert _selected["rank"] == 1
assert _selected["id"] == _nd["zones"][0]["id"]
# ...and it is unchanged by the presence of a narrative at all.
assert select_optimal_water_zone(score_water_zones(_topn_zones, WATER_SUITABILITY_DEM))["id"] == _selected["id"]
assert build_narrative_data([])["zone_found"] is False
print(
    f"Test 6 -- presentation TOP_N: {len(_topn_scored)} survivors, narrative describes exactly "
    f"{_nd['presented_count']} (ranks {[z['rank'] for z in _nd['zones']]}) and states the total "
    f"{_nd['candidate_count']}; rank-1 selection is the same object as the full-list max, untouched by "
    "the trim."
)


# =====================================================================
# TEST 7 -- GREP-ABSENCE: every deleted stream/topographic name is gone
# from the module, not merely unreferenced.
# =====================================================================
_DELETED_NAMES = [
    "_stream_permanence_factor", "_stream_permanence_label", "_nearest_stream_for_zone",
    "_reproject_streams_to_utm", "STREAM_PERMANENCE_WEIGHTS", "STREAM_NEUTRAL_FACTOR",
    "STREAM_PROXIMITY_REFERENCE_METERS", "NHD_OFFSET_LIMITATION_NOTE",
    "STREAM_PERMANENCE_SCORE_WEIGHT", "_stream_note",
    "_topographic_factor", "_gradient_steepness_score", "_contributing_area_score",
    "_valley_topographic_inputs_for_zone", "GRADIENT_FLOOR_PCT", "GRADIENT_SWEET_SPOT_LOW_PCT",
    "GRADIENT_SWEET_SPOT_HIGH_PCT", "GRADIENT_CEILING_PCT",
    "CONTRIBUTING_AREA_SCORE_REFERENCE_ACRES", "GRADIENT_STEEPNESS_SUBWEIGHT",
    "CONTRIBUTING_AREA_SUBWEIGHT", "TOPOGRAPHIC_SCORE_WEIGHT", "_topographic_note",
    "NHD_PERENNIAL_FCODES", "NHD_INTERMITTENT_FCODES", "NHD_EPHEMERAL_FCODES",
]
for _name in _DELETED_NAMES:
    assert not hasattr(ws, _name), f"{_name} must be DELETED, not merely unreferenced"

_ws_source = open(ws.__file__).read()
# Token-precise source checks: the machinery itself must be gone, not just
# its public names. "stream" survives only in the docstring passage that
# explains the deletion, which is deliberate.
for _token in ("get_water_features_for_boundary", "fcode", "MultiLineString", "sweet_spot"):
    assert _token not in _ws_source, f"deleted machinery must not survive in source: {_token!r}"

# ...and no scored zone may still carry a deleted output field.
_contract_zone = score_water_zones([zone_col8], WATER_SUITABILITY_DEM, {0: GOOD_SOIL})[0]
for _field in (
    "stream_permanence_factor", "topographic_factor", "gradient_steepness_score",
    "contributing_area_score", "nearest_stream_name", "nearest_stream_permanence",
    "nearest_stream_distance_m", "stream_data_available", "gradient_steepness_pct",
    "valley_contributing_area_acres",
):
    assert _field not in _contract_zone, f"deleted output field still on the scored zone: {_field}"
_geojson_props = water_suitability_to_geojson([_contract_zone])["features"][0]["properties"]
for _field in ("stream_permanence_factor", "topographic_factor", "nearest_stream_name"):
    assert _field not in _geojson_props, f"deleted field still in the GeoJSON properties: {_field}"
# The zone's own generation-side aggregates REMAIN -- what left is this
# module's scoring use of them, not the measurements themselves.
assert "contributing_area_cells" in _contract_zone and "slope_pct" in _contract_zone
print(
    f"Test 7 -- grep-absence: all {len(_DELETED_NAMES)} deleted stream/topographic names are gone from "
    "the module, the NHD fetch and the eigen-free gradient machinery with them, and no scored zone or "
    "GeoJSON feature carries a deleted output field. The zone's own generation-side "
    "contributing_area_cells/slope_pct aggregates are untouched."
)


# =====================================================================
# TEST 8 -- THE GEOJSON EXPORT validates and carries what a reviewer
# needs on every survivor.
# =====================================================================
import diagnose_water_zone_mask as _diag  # noqa: E402

_EXPORT_DEM = _DEM_COL8
_export_diag: dict = {}
_export_kps = [
    {
        "id": 0, "valley_id": 0, "rowcol": (5, 8),
        "point_utm": _ValleyPoint(*_pxy(_EXPORT_DEM, 5, 8)),
        "contributing_acres": 4.0, "on_parcel": True, "distance_outside_boundary_m": 0.0,
    }
]
_export_zones = find_candidate_zones(
    _EXPORT_DEM, PRODUCTION_AREAS, BOUNDARY, keypoints=_export_kps,
    accumulation_seed_budget=1, diagnostics=_export_diag,
)
_export_scored = score_water_zones(_export_zones, _EXPORT_DEM, production_areas=PRODUCTION_AREAS)
_export_ftr, _export_ftc = _export_flow_arrays = _compute_flow_direction(
    _fill_depressions(_EXPORT_DEM["array"]), _EXPORT_DEM["resolution_meters"]
)
_export_path = os.path.join(tempfile.mkdtemp(), "water_candidates.geojson")
_export = _diag._export_candidate_geojson(
    _EXPORT_DEM, _export_scored, _export_diag, _export_kps, _export_ftr, _export_ftc, path=_export_path
)

with open(_export_path, encoding="utf-8") as _handle:
    _collection = json.load(_handle)
validate_feature_collection(_collection)
assert _collection["features"], "the export must not be empty on a run that produced candidates"
for _feature in _collection["features"]:
    _shape(_feature["geometry"])  # every geometry must parse under shapely
    assert _feature["properties"]["status"] in ("nominated", "dropped"), _feature["id"]

_by_layer_status: dict = {}
for _feature in _collection["features"]:
    _key = (_feature["properties"]["layer"], _feature["properties"]["status"])
    _by_layer_status[_key] = _by_layer_status.get(_key, 0) + 1
assert _by_layer_status == _export["by_layer_status"], "the returned summary must match the written file"

_survivors = [f for f in _collection["features"] if f["properties"]["layer"] == "water_candidate_zone"]
assert len(_survivors) == len(_export_scored), "one polygon feature per surviving candidate"
_REQUIRED_SURVIVOR_PROPS = {
    "rank", "suitability_score", "gravity_feed_factor", "soil_water_holding_factor",
    "basin_shape_factor", "basin_enclosure_score", "basin_persistence_score",
    "basin_wall_economy_score", "confidence", "zone_id", "nominated_by", "keypoint_id",
    "valley_id", "area_acres", "flags", "abutment_found_left", "abutment_found_right",
    "canopy_overlap_pct", "road_overlap_pct", "production_overlap_pct",
    "wall_offset_downstream_m", "stations",
}
for _feature in _survivors:
    _missing = _REQUIRED_SURVIVOR_PROPS - set(_feature["properties"])
    assert not _missing, f"{_feature['id']} is missing export properties: {sorted(_missing)}"
    assert _feature["properties"]["status"] == "nominated"
    for _st in _feature["properties"]["stations"]:
        assert set(_st) == {
            "station_index", "offset_upstream_m", "status", "flooded_width_m",
            "flooded_cross_section_area_m2",
        }
assert {f["properties"]["rank"] for f in _survivors} == set(range(1, len(_export_scored) + 1))

# Every keypoint gets a marker whether or not it produced a candidate,
# and its wall walk gets an anchor plus a traced stem line.
_kp_features = [f for f in _collection["features"] if f["properties"]["layer"] == "water_keypoint"]
assert len(_kp_features) == len(_export_kps), "every detected keypoint gets a marker, survivor or not"
_wall_features = [f for f in _collection["features"] if f["properties"]["layer"] == "water_wall_anchor"]
for _feature in _wall_features:
    assert set(_feature["properties"]) >= {
        "wall_offset_downstream_m", "wall_drop_m", "wall_walk_end_reason", "wall_site_found"
    }
_stem_features = [f for f in _collection["features"] if f["properties"]["layer"] == "water_stem_walk"]
for _feature in _stem_features:
    assert _feature["geometry"]["type"] == "LineString"
    assert len(_feature["geometry"]["coordinates"]) >= 2

# A DROPPED candidate is exported as a point, with the limitation stated
# on the feature rather than left for a reader to discover.
_dropped = [f for f in _collection["features"] if f["properties"]["layer"] == "water_candidate_dropped"]
for _feature in _dropped:
    assert _feature["geometry"]["type"] == "Point"
    assert _feature["properties"]["geometry_is_anchor_point_only"] is True
    assert "GEOMETRY NOT RETAINED" in _feature["properties"]["confidence_notes"]
    assert _feature["properties"]["outcome"], "a dropped feature must name the reason code that stopped it"
print(
    f"Test 8 -- export: {_export['feature_count']} feature(s) validate against feature_schema, every "
    f"geometry parses under shapely, all {len(_survivors)} survivor(s) carry rank/score/basin sub-scores/"
    f"overlaps/station table, and layer+status counts match the written file: "
    f"{sorted((f'{k[0]}[{k[1]}]', v) for k, v in _by_layer_status.items())}."
)


# --- offline full-pipeline wiring check (synthetic DEM, no network) ----

import numpy as np
from rasterio.warp import transform as warp_transform

from dem_data import _utm_epsg_for_lonlat

CENTER_LON, CENTER_LAT = -79.98, 40.64
EPSG = _utm_epsg_for_lonlat(CENTER_LON, CENTER_LAT)
DST_CRS = f"EPSG:{EPSG}"
center_x, center_y = warp_transform("EPSG:4326", DST_CRS, [CENTER_LON], [CENTER_LAT])
center_x, center_y = center_x[0], center_y[0]

RESOLUTION = 5.0
SIZE = 40
HALF_EXTENT = SIZE * RESOLUTION / 2
origin_x = center_x - HALF_EXTENT
origin_y = center_y + HALF_EXTENT

utm_corners_x = [origin_x, origin_x + SIZE * RESOLUTION, origin_x + SIZE * RESOLUTION, origin_x, origin_x]
utm_corners_y = [origin_y, origin_y, origin_y - SIZE * RESOLUTION, origin_y - SIZE * RESOLUTION, origin_y]
lons, lats = warp_transform(DST_CRS, "EPSG:4326", utm_corners_x, utm_corners_y)
boundary_coordinates = list(zip(lons, lats))

array = np.zeros((SIZE, SIZE), dtype=np.float32)
for row in range(SIZE):
    for col in range(SIZE):
        if row >= SIZE - 8:
            array[row, col] = 100.0  # flat southern bench (production area)
        else:
            distance_from_center_col = abs(col - SIZE // 2)
            array[row, col] = 100.0 + (SIZE - 8 - row) * 3.0 + distance_from_center_col * 1.5

synthetic_dem = {
    "array": array,
    "resolution_meters": (RESOLUTION, RESOLUTION),
    "origin_x": origin_x,
    "origin_y": origin_y,
    "crs": DST_CRS,
}

# identify_water_suitability() calls production_area.identify_production_areas()
# internally with no check_soil/check_canopy passthrough of its own (water_suitability.py
# is unchanged by the canopy-gate work) -- and that gate is now mandatory, with a fetch
# failure raising rather than degrading. Patched here (production_area's own module-level
# name, which is what identify_production_areas() actually looks up) to a fixed offline
# stub so this wiring check stays fully offline; the gate's own hard-failure behavior has
# its own dedicated tests in test_canopy_height_data.py.
def _fake_clean_canopy(boundary_coordinates, dem):
    return {
        "array": np.full(dem["array"].shape, 1.0, dtype=np.float32),  # below threshold everywhere -- no trees
        "resolution_meters": dem["resolution_meters"],
        "origin_x": dem["origin_x"],
        "origin_y": dem["origin_y"],
        "crs": dem["crs"],
        "source_item_id": "offline-test-stub",
    }


pa.get_canopy_height_for_boundary = _fake_clean_canopy

# The existing-road exclusion gate is optional (degrades gracefully, unlike canopy) but
# still defaults to check_roads=True and attempts a real fetch otherwise -- stubbed the
# same way, to "no roads found nearby" (None), so this wiring check stays fully offline.
pa.get_road_exclusion_union_utm = lambda boundary_coordinates, dem, buffer_meters=None: None

pipeline_result = identify_water_suitability(
    boundary_coordinates, dem=synthetic_dem, check_soil=False,
    zone_kwargs={"min_boundary_setback_meters": 5.0},
)
validate_feature_collection(pipeline_result["zones_geojson"])
assert len(pipeline_result["scored_zones"]) >= 1, "expected at least one scored water system candidate zone"
for zone in pipeline_result["scored_zones"]:
    assert zone["soil_data_available"] is False
    # With the soil check disabled, the soil SIGNAL is gone. Confidence is
    # then decided entirely by the measurement-completeness signal, which
    # is a real per-zone property of this DEM rather than a constant --
    # so this asserts the RELATIONSHIP, not a flat value.
    assert zone["confidence"] == ("medium" if zone["measurement_complete"] else "low"), zone["confidence"]
    assert "production_overlap_pct" in zone
# narrative_data rides on the same result, and it is json-clean.
_pipeline_nd = pipeline_result["narrative_data"]
assert _pipeline_nd["candidate_count"] == len(pipeline_result["scored_zones"])
assert len(_pipeline_nd["zones"]) <= WATER_ZONE_PRESENTATION_TOP_N
assert json.loads(json.dumps(_pipeline_nd)) == _pipeline_nd
print(f"identify_water_suitability() full pipeline wiring works end-to-end offline: {len(pipeline_result['scored_zones'])} scored zone(s), check_soil=False correctly yields the lower confidence.")


# --- boundary_polygon_utm/valleys/production_areas overrides ------------
#
# Real baseline production areas for this same synthetic_dem/boundary_coordinates,
# via the SAME production_area_ceiling.identify_optimized_production_areas() call
# identify_water_suitability()'s own self-compute fallback now makes -- computed
# once here (real, offline via the already-applied pa.get_canopy_height_for_boundary/
# pa.get_road_exclusion_union_utm stubs above) and reused below as both the
# "what the default/self-computed path produces" reference and a ready-made,
# realistic override value.
baseline_optimized_result = ws.identify_optimized_production_areas(boundary_coordinates, dem=synthetic_dem)
BASELINE_PRODUCTION_AREAS = baseline_optimized_result["scored_patches"]
assert BASELINE_PRODUCTION_AREAS, "test setup: expected at least one real production area on this synthetic DEM"

# --- 1. regression: with no overrides, production_areas comes from -----
# --- identify_optimized_production_areas(), NOT identify_production_areas() ---

with mock_patch.object(
    ws, "identify_optimized_production_areas", return_value=baseline_optimized_result
) as mock_optimized, mock_patch.object(ws, "identify_production_areas") as mock_raw:
    default_result = identify_water_suitability(
        boundary_coordinates, dem=synthetic_dem, check_soil=False,
        zone_kwargs={"min_boundary_setback_meters": 5.0},
    )

assert mock_optimized.call_count == 1, "identify_optimized_production_areas() must be called exactly once when production_areas isn't supplied"
optimized_call = mock_optimized.call_args
assert optimized_call.args[0] == boundary_coordinates
assert optimized_call.kwargs["dem"] is synthetic_dem
assert mock_raw.call_count == 0, "identify_production_areas() (the RAW, un-ceiling-trimmed source) must NOT be called for production_areas anymore"
assert len(default_result["scored_zones"]) >= 1, "expected at least one scored water system candidate zone from the real baseline production areas"
print(
    "REGRESSION: with no production_areas override, identify_water_suitability() sources it from "
    "identify_optimized_production_areas() exactly once, and never calls the raw identify_production_areas()."
)


# --- 2. override behavior: all three new overrides supplied -> the ------
# --- corresponding self-compute fallbacks are never called --------------

from rasterio.warp import transform as _override_warp_transform  # noqa: E402

override_boundary_xs, override_boundary_ys = _override_warp_transform(
    "EPSG:4326", synthetic_dem["crs"],
    [pt[0] for pt in boundary_coordinates], [pt[1] for pt in boundary_coordinates],
)
from shapely.geometry import Polygon as _OverridePolygon  # noqa: E402
OVERRIDE_BOUNDARY_POLYGON_UTM = _OverridePolygon(zip(override_boundary_xs, override_boundary_ys))

with mock_patch.object(ws, "delineate_valleys") as mock_delineate_override, mock_patch.object(
    ws, "identify_optimized_production_areas"
) as mock_optimized_override:
    override_result = identify_water_suitability(
        boundary_coordinates,
        dem=synthetic_dem,
        boundary_polygon_utm=OVERRIDE_BOUNDARY_POLYGON_UTM,
        valleys=[],
        production_areas=BASELINE_PRODUCTION_AREAS,
        check_soil=False,
        zone_kwargs={"min_boundary_setback_meters": 5.0},
    )

assert mock_delineate_override.call_count == 0, "delineate_valleys() must NOT be called when valleys was supplied as an override"
assert mock_optimized_override.call_count == 0, "identify_optimized_production_areas() must NOT be called when production_areas was supplied as an override"
assert len(override_result["scored_zones"]) >= 1
print(
    "Supplying boundary_polygon_utm=/valleys=/production_areas= all three as overrides correctly skips "
    "both delineate_valleys() and identify_optimized_production_areas() -- zero self-compute fallback calls."
)


# --- 2b. THE DEFERRED FIX, INSTRUMENTED: delineate_valleys() runs -------
# --- EXACTLY ONCE on the standalone path (valleys NOT supplied) ---------
#
# identify_water_suitability() delineates valleys itself when they are not
# supplied, and now FORWARDS them into find_candidate_zones(), whose
# keypoint self-compute path hands them to detect_keypoints(). Without
# that forward, detect_keypoints() delineates the same valleys off the
# same DEM a second time. Both lookup sites are patched -- the name in
# THIS module and the name keypoint_detection.py looks up -- because a
# forward that fixes only one of them fixes nothing.
import keypoint_detection as _kd  # noqa: E402

_real_delineate = ws.delineate_valleys
_valley_call_count = {"n": 0}


def _counting_delineate(dem):
    _valley_call_count["n"] += 1
    return _real_delineate(dem)


with mock_patch.object(ws, "delineate_valleys", side_effect=_counting_delineate), mock_patch.object(
    _kd, "delineate_valleys", side_effect=_counting_delineate
), mock_patch.object(ws, "identify_optimized_production_areas", return_value=baseline_optimized_result):
    _standalone_result = identify_water_suitability(
        boundary_coordinates,
        dem=synthetic_dem,
        boundary_polygon_utm=OVERRIDE_BOUNDARY_POLYGON_UTM,
        check_soil=False,
        zone_kwargs={"min_boundary_setback_meters": 5.0},
    )

assert _valley_call_count["n"] == 1, (
    f"delineate_valleys() must run EXACTLY ONCE on the standalone path -- once here, then FORWARDED "
    f"into find_candidate_zones() rather than re-derived by detect_keypoints(). Saw "
    f"{_valley_call_count['n']} call(s), which means the forward is missing or reaches only one of the "
    "two lookup sites."
)
assert _standalone_result["scored_zones"], "the instrumented run must still produce real candidates"
print(
    f"THE DEFERRED FIX IS CLOSED, INSTRUMENTED: with valleys left to self-compute, delineate_valleys() "
    f"runs exactly {_valley_call_count['n']} time across identify_water_suitability() -> "
    "find_candidate_zones() -> detect_keypoints(), counted across BOTH module lookup sites."
)


# --- 3. scoring output genuinely reflects the overridden production_areas ---
# --- (not silently falling back to the self-computed default) -----------
#
# Same override_result run above (BASELINE_PRODUCTION_AREAS) vs. a second run using
# a copy of those same patches with every representative_elevation_m shifted sharply
# UP (simulating a much higher production area) -- if production_areas were silently
# ignored, both runs would score identically; they must not.

RAISED_PRODUCTION_AREAS = [
    {**patch, "representative_elevation_m": patch["representative_elevation_m"] + 500.0}
    for patch in BASELINE_PRODUCTION_AREAS
]

with mock_patch.object(ws, "delineate_valleys") as _mock_delineate_raised, mock_patch.object(
    ws, "identify_optimized_production_areas"
) as _mock_optimized_raised:
    raised_result = identify_water_suitability(
        boundary_coordinates,
        dem=synthetic_dem,
        boundary_polygon_utm=OVERRIDE_BOUNDARY_POLYGON_UTM,
        valleys=[],
        production_areas=RAISED_PRODUCTION_AREAS,
        check_soil=False,
        zone_kwargs={"min_boundary_setback_meters": 5.0},
    )

assert _mock_delineate_raised.call_count == 0 and _mock_optimized_raised.call_count == 0

override_by_id = {z["id"]: z for z in override_result["scored_zones"]}
raised_by_id = {z["id"]: z for z in raised_result["scored_zones"]}
common_ids = set(override_by_id) & set(raised_by_id)
assert common_ids, "expected at least one zone id in common between the baseline-elevation and raised-elevation runs to compare"

differed = False
for zone_id in common_ids:
    baseline_gravity = override_by_id[zone_id]["gravity_feed_factor"]
    raised_gravity = raised_by_id[zone_id]["gravity_feed_factor"]
    if baseline_gravity != raised_gravity:
        differed = True
    # a candidate zone sits at a roughly fixed real elevation -- pushing its served
    # production area's representative_elevation_m up by 500m must never make its
    # gravity relationship MORE favorable, only equal or worse (it can never make the
    # candidate more "above" a production area that just got raised further above it).
    assert raised_gravity <= baseline_gravity, (
        f"zone {zone_id}: raising the served production area's elevation by 500m must not improve "
        f"gravity_feed_factor (baseline={baseline_gravity}, raised={raised_gravity})"
    )
assert differed, "raising every overridden production area's representative_elevation_m by 500m must change at least one zone's gravity_feed_factor -- production_areas is being silently ignored otherwise"
print(
    "Scoring output genuinely reflects the overridden production_areas: raising every overridden patch's "
    "representative_elevation_m by 500m correctly lowers (never improves) the served zone(s)' "
    "gravity_feed_factor, proving the override isn't silently falling back to self-computed patches."
)


# --- 4. fetch_and_select_optimal_water_zone() forwards new overrides ----
# --- through **suitability_kwargs -----------------------------------------

_fake_selected_zone = {"id": 999, "suitability_score": 42.0}
_fake_identify_result = {
    "zones_geojson": {"type": "FeatureCollection", "features": []},
    "scored_zones": [],
    "all_scored_zones": [],
    "selected_water_zone": _fake_selected_zone,
}
with mock_patch.object(ws, "identify_water_suitability", return_value=_fake_identify_result) as mock_identify:
    wrapper_result = fetch_and_select_optimal_water_zone(
        boundary_coordinates,
        dem=synthetic_dem,
        production_areas=BASELINE_PRODUCTION_AREAS,
        valleys=[],
    )

assert wrapper_result == _fake_selected_zone, "fetch_and_select_optimal_water_zone() must return identify_water_suitability()'s own selected_water_zone"
assert mock_identify.call_count == 1
identify_call = mock_identify.call_args
assert identify_call.args[0] == boundary_coordinates
assert identify_call.kwargs["dem"] is synthetic_dem
assert identify_call.kwargs["production_areas"] is BASELINE_PRODUCTION_AREAS, "production_areas= must reach identify_water_suitability() via **suitability_kwargs"
assert identify_call.kwargs["valleys"] == [], "valleys= must also reach identify_water_suitability() via **suitability_kwargs"
print(
    "fetch_and_select_optimal_water_zone() correctly forwards production_areas=/valleys= (and, by the same "
    "**suitability_kwargs mechanism, boundary_polygon_utm=) straight through to identify_water_suitability(), "
    "with no signature change needed on the wrapper itself."
)


# --- canopy_height override forwarding ---
#
# identify_water_suitability() reaches canopy on TWO independent paths when
# production_areas is left to self-compute: its default identify_optimized_
# production_areas() fetch AND its own mandatory get_required_tree_root_
# zone_mask_utm() gate. A supplied canopy_height override must reach BOTH,
# so neither re-fetches from the network. Shared-core behavior is proven in
# test_canopy_mask_override.py; this proves this entry point forwards the
# override down every canopy path. Reuses the fully-offline synthetic_dem/
# boundary fixture the end-to-end wiring check above already uses.
from _canopy_override_probe import CanopyOverrideProbe, clean_canopy_for  # noqa: E402

_ov_override = clean_canopy_for(synthetic_dem)
with CanopyOverrideProbe() as _ov_probe:
    identify_water_suitability(
        boundary_coordinates, dem=synthetic_dem, check_soil=False,
        zone_kwargs={"min_boundary_setback_meters": 5.0}, canopy_height=_ov_override,
    )
_ov_probe.assert_override_used(_ov_override, "identify_water_suitability()")
assert len(_ov_probe.mask_arrays) >= 2, (
    "identify_water_suitability(): with production_areas self-computed, the override must reach BOTH "
    f"canopy paths (internal identify_optimized_production_areas + own gate), saw {len(_ov_probe.mask_arrays)}"
)
print(
    "identify_water_suitability(): a supplied canopy_height override reaches BOTH internal canopy paths "
    f"({len(_ov_probe.mask_arrays)} gates) -- 0 canopy fetches, exact override array used throughout."
)


print("\nAll water_suitability checks passed.")
