"""
test_water_suitability.py

Offline (no-network) checks for water_suitability.py's per-factor scoring
and weighted composite ranking. Same "pure logic, independent of real data
fetches" approach as test_production_suitability.py/test_solar_suitability.py:
score_water_zones() is exercised directly against real zones generated by
find_candidate_zones() from a small synthetic DEM (water_candidate_zones.py's
cell-based rearchitecture means zones no longer carry a valley_id to hand-
build a matching fixture around -- see test_water_candidate_zones.py's own
docstring for the same reasoning) plus hand-built valleys/pre-fetched
soil/stream data dicts, with no network calls anywhere in this file except
the final offline wiring check (identify_water_suitability() with
check_soil=False, check_streams=False and a synthetic dem= passed directly,
mirroring test_water_system_candidate_pipeline.py's approach).

The "--- boundary_polygon_utm/valleys/production_areas overrides ---"
section near the end covers identify_water_suitability()'s own
dem/boundary_polygon_utm/valleys/production_areas override plumbing
(mirroring water_candidate_zones.identify_water_system_candidate_zones()'s
own override tests) AND the real behavior change this branch makes: the
production_areas self-compute fallback now sources production_area_
ceiling.identify_optimized_production_areas()'s scored_patches, not
production_area.identify_production_areas()'s raw patches -- see
water_suitability.py's own module docstring for why. Same mock_patch.object
usage against the module's own imported bindings (patch where it's looked
up, not where it's defined) as test_pipeline_context.py already
establishes.
"""

from unittest.mock import patch as mock_patch

import numpy as np
from shapely.geometry import box

import production_area as pa
import water_suitability as ws
from feature_schema import validate_feature_collection
from water_candidate_zones import find_candidate_zones
from water_suitability import (
    GRAVITY_FULL_CREDIT_GRADIENT_PCT,
    GRAVITY_LEVEL_GROUND_FACTOR,
    GRAVITY_MAX_DEFICIT_GRADIENT_PCT,
    GRAVITY_MIN_FACTOR,
    GRAVITY_ZERO_DISTANCE_FULL_CREDIT_METERS,
    GRAVITY_ZERO_DISTANCE_MAX_DEFICIT_METERS,
    STREAM_NEUTRAL_FACTOR,
    STREAM_PROXIMITY_REFERENCE_METERS,
    WATER_HOLDING_GOOD_KSAT_UM_PER_S,
    WATER_HOLDING_POOR_KSAT_UM_PER_S,
    WATER_HOLDING_UNAVAILABLE_FACTOR,
    _WEIGHT_SUM,
    _gravity_feed_factor,
    _stream_permanence_factor,
    _topographic_factor,
    _water_holding_factor,
    fetch_and_select_optimal_water_zone,
    identify_water_suitability,
    score_water_zones,
    water_suitability_to_geojson,
)

CRS = "EPSG:32617"

assert abs(_WEIGHT_SUM - 1.0) < 1e-6, f"composite weights must sum to 1.0, got {_WEIGHT_SUM}"
print("Composite factor weights sum to 1.0.")


# --- _gravity_feed_factor(): continuous, monotonic, never truly zero ----
# --- (distance_m > 0 case: scores off gradient_pct, the original scale) --

# distance_m is nonzero (100.0) and elevation_differential_m is irrelevant
# in this branch -- only gradient_pct drives the score when distance_m > 0.
assert _gravity_feed_factor(999.0, 100.0, GRAVITY_FULL_CREDIT_GRADIENT_PCT) == 1.0
assert _gravity_feed_factor(999.0, 100.0, GRAVITY_FULL_CREDIT_GRADIENT_PCT * 5) == 1.0, "extra-comfortable gradient still caps at 1.0"
assert _gravity_feed_factor(999.0, 100.0, 0.0) == GRAVITY_LEVEL_GROUND_FACTOR
assert _gravity_feed_factor(999.0, 100.0, GRAVITY_MAX_DEFICIT_GRADIENT_PCT) == GRAVITY_MIN_FACTOR
assert _gravity_feed_factor(999.0, 100.0, GRAVITY_MAX_DEFICIT_GRADIENT_PCT * 5) == GRAVITY_MIN_FACTOR, "extreme deficit floors, doesn't go below GRAVITY_MIN_FACTOR"
assert GRAVITY_MIN_FACTOR > 0.0, "a below-elevation (pump-required) candidate must never score literally 0 on this factor"
mild_above = _gravity_feed_factor(999.0, 100.0, 0.5)
mild_below = _gravity_feed_factor(999.0, 100.0, -1.0)
assert GRAVITY_LEVEL_GROUND_FACTOR < mild_above < 1.0
assert GRAVITY_MIN_FACTOR < mild_below < GRAVITY_LEVEL_GROUND_FACTOR
assert (
    _gravity_feed_factor(999.0, 100.0, 1.0) > _gravity_feed_factor(999.0, 100.0, 0.0)
    > _gravity_feed_factor(999.0, 100.0, -1.0) > _gravity_feed_factor(999.0, 100.0, -5.0)
)
print("_gravity_feed_factor() is continuous/monotonic and never zero (distance_m > 0, gradient_pct-driven case).")


# --- _gravity_feed_factor(): distance_m == 0 case -- real bug, fixed ----
#
# Live-confirmed bug: with distance_m == 0 (a zone sitting inside/touching
# a production area — a real, common case that water-zone eligibility does
# not reject, applying no minimum-service-distance gate), water_candidate_
# zones.py reports gradient_pct as a
# 0.0 div-by-zero placeholder, NOT a real 0% grade. Scoring directly off
# that placeholder collapsed every distance-0 zone to the same
# GRAVITY_LEVEL_GROUND_FACTOR (0.6), regardless of real elevation_differential_m
# -- on the real property, a +7.01m (strong gravity-feed), a +0.63m (barely
# above), and a -8.68m (pump-required) zone all scored identically. Fixed:
# distance_m == 0 must score off elevation_differential_m directly, not
# gradient_pct.

real_property_valley4 = _gravity_feed_factor(7.01, 0.0, 0.0)   # strong gravity-feed
real_property_valley2 = _gravity_feed_factor(0.63, 0.0, 0.0)   # barely above
real_property_valley11 = _gravity_feed_factor(-8.68, 0.0, 0.0)  # pump-required

assert real_property_valley4 > real_property_valley2 > real_property_valley11, (
    f"real, differentiated elevation differentials at distance_m==0 must score in the correct rank order -- got "
    f"valley4={real_property_valley4}, valley2={real_property_valley2}, valley11={real_property_valley11}"
)
assert real_property_valley11 > 0.0, "even the pump-required zone must never score literally 0 on this factor"
print(
    f"REGRESSION (real property scenario, all distance_m==0): gravity_feed_factor correctly differentiates "
    f"by elevation_differential_m alone -- valley4 (+7.01m)={real_property_valley4} > "
    f"valley2 (+0.63m)={real_property_valley2} > valley11 (-8.68m)={real_property_valley11}."
)

assert _gravity_feed_factor(GRAVITY_ZERO_DISTANCE_FULL_CREDIT_METERS, 0.0, 0.0) == 1.0
assert _gravity_feed_factor(0.0, 0.0, 0.0) == GRAVITY_LEVEL_GROUND_FACTOR
assert _gravity_feed_factor(GRAVITY_ZERO_DISTANCE_MAX_DEFICIT_METERS, 0.0, 0.0) == GRAVITY_MIN_FACTOR
assert _gravity_feed_factor(GRAVITY_ZERO_DISTANCE_MAX_DEFICIT_METERS * 5, 0.0, 0.0) == GRAVITY_MIN_FACTOR
print("_gravity_feed_factor() at distance_m==0 hits the same real reference breakpoints (full credit / level / max deficit).")

# A gradient_pct of 0.0 alongside a nonzero distance_m must still be
# treated as a genuine, real 0% grade (level ground), NOT collapsed to the
# distance==0 meters-based path -- confirms the dispatch is keyed strictly
# off distance_m, not off gradient_pct happening to read 0.0.
assert _gravity_feed_factor(7.01, 50.0, 0.0) == GRAVITY_LEVEL_GROUND_FACTOR
print("A real, nonzero distance with a genuine 0% gradient still scores as level ground, not the distance==0 path.")


# --- _water_holding_factor(): log-scale, real NRCS breakpoints ----------

assert _water_holding_factor(WATER_HOLDING_GOOD_KSAT_UM_PER_S) == 1.0
assert _water_holding_factor(WATER_HOLDING_GOOD_KSAT_UM_PER_S / 10) == 1.0, "even better (lower) than the good reference still caps at 1.0"
assert _water_holding_factor(WATER_HOLDING_POOR_KSAT_UM_PER_S) == 0.0
assert _water_holding_factor(WATER_HOLDING_POOR_KSAT_UM_PER_S * 10) == 0.0
assert _water_holding_factor(None) == WATER_HOLDING_UNAVAILABLE_FACTOR
mid_ksat = (WATER_HOLDING_GOOD_KSAT_UM_PER_S * WATER_HOLDING_POOR_KSAT_UM_PER_S) ** 0.5  # geometric midpoint
mid_score = _water_holding_factor(mid_ksat)
assert 0.4 < mid_score < 0.6, f"log-scale geometric midpoint should score near 0.5, got {mid_score}"
assert _water_holding_factor(1.0) > _water_holding_factor(10.0) > _water_holding_factor(50.0)
print("_water_holding_factor() scores real ksat_r on a log scale between the documented NRCS breakpoints, unavailable defaults neutral.")


# --- _stream_permanence_factor(): real permanence classes, real proximity ---

perennial_close = {"name": "Real Creek", "fcode": 46006, "distance_m": 0.0}
intermittent_close = {"name": "Seasonal Run", "fcode": 46003, "distance_m": 0.0}
ephemeral_close = {"name": "Draw", "fcode": 46007, "distance_m": 0.0}
unknown_close = {"name": "General Stream", "fcode": 46000, "distance_m": 0.0}

perennial_factor, perennial_label = _stream_permanence_factor(perennial_close)
intermittent_factor, intermittent_label = _stream_permanence_factor(intermittent_close)
ephemeral_factor, ephemeral_label = _stream_permanence_factor(ephemeral_close)
unknown_factor, unknown_label = _stream_permanence_factor(unknown_close)

assert perennial_label == "perennial" and intermittent_label == "intermittent" and ephemeral_label == "ephemeral" and unknown_label == "unknown"
assert perennial_factor > intermittent_factor > ephemeral_factor, (
    f"perennial ({perennial_factor}) must outscore intermittent ({intermittent_factor}) "
    f"must outscore ephemeral ({ephemeral_factor}) at equal proximity"
)
assert intermittent_factor > STREAM_NEUTRAL_FACTOR > ephemeral_factor or ephemeral_factor >= STREAM_NEUTRAL_FACTOR
assert perennial_factor == 1.0, "right at a perennial stream (distance=0) should reach the ceiling"
print(f"Stream permanence ordering confirmed at equal proximity: perennial={perennial_factor} > intermittent={intermittent_factor} > ephemeral={ephemeral_factor}, unknown={unknown_factor}.")

far_perennial = {"name": "Real Creek", "fcode": 46006, "distance_m": STREAM_PROXIMITY_REFERENCE_METERS * 2}
far_factor, far_label = _stream_permanence_factor(far_perennial)
assert far_factor == STREAM_NEUTRAL_FACTOR and far_label is None, "a stream beyond the proximity reference contributes no real credit -- same as no stream at all"

none_factor, none_label = _stream_permanence_factor(None)
assert none_factor == STREAM_NEUTRAL_FACTOR and none_label is None
print("A stream beyond the proximity reference, or no stream at all, both correctly fall back to the neutral baseline.")


# --- _topographic_factor(): sweet-spot gradient + contributing area -----

flat_factor, flat_grad_score, _ = _topographic_factor(0.1, 5.0)
sweet_factor, sweet_grad_score, _ = _topographic_factor(8.0, 5.0)
steep_factor, steep_grad_score, _ = _topographic_factor(40.0, 5.0)
assert sweet_grad_score == 1.0
assert flat_grad_score == 0.0 and steep_grad_score == 0.0
assert sweet_factor > flat_factor and sweet_factor > steep_factor
_, _, small_area_score = _topographic_factor(8.0, 1.0)
_, _, big_area_score = _topographic_factor(8.0, 50.0)
assert big_area_score > small_area_score
print("_topographic_factor() correctly scores a moderate valley gradient highest and rewards larger contributing area.")


# --- score_water_zones(): full composite, using REAL zones generated by ---
# --- find_candidate_zones() from a small synthetic DEM (cell-based       ---
# --- rearchitecture: no more valley_id to hand-build a matching zone     ---
# --- fixture around -- see test_water_candidate_zones.py)                ---
#
# find_candidate_zones() returns up to MAX_WATER_ZONE_CANDIDATES zones per
# call now. To get the two distinct real zone dicts these scoring tests
# need, we run it on two SEPARATE single-drainage-column DEMs (channel at
# col=8 and at col=32 of a 40x40 grid, 5m), sharing one UTM frame, with the
# candidate cap pinned to 1 so each run yields exactly one zone, and
# relabel their ids 0/1. Each zone is a real level-pool footprint -- the
# scoring logic under test is unchanged; only how we obtain two zones is.
from raster_grid import pixel_center_xy as _pxy  # noqa: E402
from shapely.geometry import Point as _ValleyPoint  # noqa: E402

BOUNDARY = box(500000.0, 4499800.0, 500200.0, 4500000.0)
_size = 40
_FRAME = {"resolution_meters": (5.0, 5.0), "origin_x": 500000.0, "origin_y": 4500000.0, "crs": CRS}


def _single_column_dem(mid_col):
    arr = np.zeros((_size, _size), dtype=np.float32)
    for r in range(_size):
        for c in range(_size):
            arr[r, c] = abs(c - mid_col) * 2.0 + r * 0.5
    return {"array": arr, **_FRAME}


# A two-column DEM retained as the `dem` argument for the scoring calls
# below (score_water_zones() reads geometry from the zone dicts, not per-
# cell from this dem, so its exact content is immaterial there) and for the
# below-elevation find_candidate_zones() run further down.
_array = np.zeros((_size, _size), dtype=np.float32)
for _row in range(_size):
    for _col in range(_size):
        _array[_row, _col] = min(abs(_col - 8), abs(_col - 32)) * 2.0 + _row * 0.5
WATER_SUITABILITY_DEM = {"array": _array, **_FRAME}

PRODUCTION_AREAS = [
    {
        "id": 0,
        "representative_elevation_m": -5.0,
        "polygon_utm": box(500080.0, 4499750.0, 500120.0, 4499800.0),
        "render_fill_polygon_utm": box(500080.0, 4499750.0, 500120.0, 4499800.0),
    }
]

_DEM_COL8 = _single_column_dem(8)
_DEM_COL32 = _single_column_dem(32)
_zones8 = find_candidate_zones(_DEM_COL8, PRODUCTION_AREAS, BOUNDARY, max_water_zone_candidates=1)
_zones32 = find_candidate_zones(_DEM_COL32, PRODUCTION_AREAS, BOUNDARY, max_water_zone_candidates=1)
assert len(_zones8) == 1 and len(_zones32) == 1, (
    f"each single-column DEM must yield exactly one zone at a candidate cap of 1, got "
    f"{len(_zones8)}/{len(_zones32)}"
)
zone_col8 = {**_zones8[0], "id": 0}
zone_col32 = {**_zones32[0], "id": 1}
assert zone_col8["polygon_utm"].bounds[0] < 500100.0 <= zone_col32["polygon_utm"].bounds[0], (
    "test setup: zone_col8 (channel at col=8) should sit west of zone_col32 (channel at col=32)"
)
VALLEY_ZONE_ID = zone_col8["id"]      # 0
NO_VALLEY_ZONE_ID = zone_col32["id"]  # 1

# A real valley (valley_delineation.delineate_valleys()'s own output shape)
# whose branch points sit spatially inside zone_col8's own real (trimmed)
# footprint -- derived directly from two of the zone's OWN member cell
# centers, so containment is guaranteed by construction (the NEW spatial-
# overlap matching _valley_topographic_inputs_for_zone() uses instead of a
# zone['valley_id'] == valley['id'] join). The two points' z-values are set
# so the branch's grade over its own planar length is a moderate ~8% (in
# _topographic_factor()'s sweet spot), matching the old fixture's intent.
# zone_col32 deliberately has NO overlapping valley at all, exercising the
# "no traced valley overlaps this real drainage-cell zone" degradation path.
_zone8_cells = zone_col8["cells"]
assert len(_zone8_cells) >= 2, "zone_col8 must have at least two cells to seed two valley branch points"
_p_a_r, _p_a_c = _zone8_cells[0]
_p_b_r, _p_b_c = _zone8_cells[-1]
_ax, _ay = _pxy(_DEM_COL8, _p_a_r, _p_a_c)
_bx, _by = _pxy(_DEM_COL8, _p_b_r, _p_b_c)
assert (_ax, _ay) != (_bx, _by), "test setup: the two seed cells must have distinct centers for a nonzero grade"
_branch_len_m = _ValleyPoint(_ax, _ay).distance(_ValleyPoint(_bx, _by))
_TARGET_GRADIENT_PCT = 8.0
_valley_point_a = (_ax, _ay, 120.0)
_valley_point_b = (_bx, _by, 120.0 - _TARGET_GRADIENT_PCT * _branch_len_m / 100.0)
assert zone_col8["polygon_utm"].contains(_ValleyPoint(_ax, _ay)), (
    "test setup: valley branch point A must fall inside zone_col8's real footprint"
)
assert zone_col8["polygon_utm"].contains(_ValleyPoint(_bx, _by)), (
    "test setup: valley branch point B must fall inside zone_col8's real footprint"
)
assert not zone_col32["polygon_utm"].contains(_ValleyPoint(_ax, _ay)) and not zone_col32[
    "polygon_utm"
].contains(_ValleyPoint(_bx, _by)), "test setup: zone_col32 must NOT overlap the valley branch"
VALLEY_OVERLAPPING_ZONE = {
    "id": 0,
    "max_contributing_area_acres": 5.0,
    "branches_utm": [[_valley_point_a, _valley_point_b]],
}
VALLEYS = [VALLEY_OVERLAPPING_ZONE]

GOOD_SOIL = {"ksat_r_um_per_s": 0.05, "coverage_fraction": 0.9}
POOR_SOIL = {"ksat_r_um_per_s": 300.0, "coverage_fraction": 0.9}

GOOD_STREAM = {"name": "Real Creek", "fcode": 46006, "distance_m": 5.0}

# Best case: zone_col8 (real overlapping valley -- real gradient/
# contributing area feed the topographic factor) + good soil + close
# perennial stream should clearly outscore zone_col32 (no overlapping
# valley -- topographic factor degrades to neutral) with poor soil and no
# stream.
best_case_scored = score_water_zones(
    [zone_col8, zone_col32],
    VALLEYS,
    WATER_SUITABILITY_DEM,
    soil_data_by_zone_id={VALLEY_ZONE_ID: GOOD_SOIL, NO_VALLEY_ZONE_ID: POOR_SOIL},
    stream_data_by_zone_id={VALLEY_ZONE_ID: GOOD_STREAM, NO_VALLEY_ZONE_ID: None},
)
scored_by_id = {z["id"]: z for z in best_case_scored}
assert scored_by_id[VALLEY_ZONE_ID]["gradient_steepness_pct"] is not None, "zone_col8's overlapping valley must feed a real gradient"
assert scored_by_id[VALLEY_ZONE_ID]["valley_contributing_area_acres"] == 5.0
assert scored_by_id[NO_VALLEY_ZONE_ID]["gradient_steepness_pct"] is None, "zone_col32 has no overlapping valley -- must degrade to None, not crash or fabricate a value"
assert scored_by_id[NO_VALLEY_ZONE_ID]["valley_contributing_area_acres"] is None
assert scored_by_id[VALLEY_ZONE_ID]["suitability_score"] > scored_by_id[NO_VALLEY_ZONE_ID]["suitability_score"]
print(
    f"Zone {VALLEY_ZONE_ID} (real overlapping valley, good soil, near-perennial-stream, "
    f"score={scored_by_id[VALLEY_ZONE_ID]['suitability_score']}) correctly outscores zone {NO_VALLEY_ZONE_ID} "
    f"(no overlapping valley, poor soil, no stream, score={scored_by_id[NO_VALLEY_ZONE_ID]['suitability_score']})."
)
print(
    "The new spatial-overlap valley matching correctly feeds the overlapping zone's real gradient/contributing "
    "area into topographic_factor, and correctly degrades the non-overlapping zone to None/None rather than "
    "crashing or reusing a stale valley_id join."
)

# Every zone find_candidate_zones() returns must still be a REAL,
# scoreable, non-zero candidate, even with no overlapping valley at all.
assert scored_by_id[NO_VALLEY_ZONE_ID]["suitability_score"] > 0.0, "a zone with no overlapping valley must still score > 0, never be zeroed out"
print(f"A zone with no overlapping valley remains a real, scoreable, non-zero candidate: score={scored_by_id[NO_VALLEY_ZONE_ID]['suitability_score']}/100.")

# rank is assigned over ALL returned zones, best-first, no exclusion.
assert len(best_case_scored) == 2
assert {z["rank"] for z in best_case_scored} == {1, 2}
assert next(z for z in best_case_scored if z["rank"] == 1)["id"] == VALLEY_ZONE_ID
print("rank is assigned over all returned zones (no MIN_SUITABILITY_SCORE-style exclusion).")


# --- confidence differentiation: same zone, different data availability ---

both_available = score_water_zones(
    [zone_col8], VALLEYS, WATER_SUITABILITY_DEM, {VALLEY_ZONE_ID: GOOD_SOIL}, {VALLEY_ZONE_ID: GOOD_STREAM}
)[0]
one_available = score_water_zones([zone_col8], VALLEYS, WATER_SUITABILITY_DEM, {VALLEY_ZONE_ID: GOOD_SOIL}, {})[0]
none_available = score_water_zones([zone_col8], VALLEYS, WATER_SUITABILITY_DEM, {}, {})[0]

assert both_available["confidence"] == "high"
assert one_available["confidence"] == "medium"
assert none_available["confidence"] == "low"
assert both_available["confidence"] != one_available["confidence"] != none_available["confidence"]
print(
    f"Confidence genuinely differentiates by real data availability for the SAME zone: "
    f"both-available={both_available['confidence']}, one-available={one_available['confidence']}, "
    f"none-available={none_available['confidence']} -- no longer a flat 'low' across the board."
)

# Confidence also differs ACROSS zones within one scoring call when their
# real data genuinely differs -- the actual scenario the live property run
# needs to demonstrate.
mixed_scored = score_water_zones(
    [zone_col8, zone_col32], VALLEYS, WATER_SUITABILITY_DEM,
    soil_data_by_zone_id={VALLEY_ZONE_ID: GOOD_SOIL},  # the other zone absent -- never checked
    stream_data_by_zone_id={VALLEY_ZONE_ID: GOOD_STREAM, NO_VALLEY_ZONE_ID: None},  # checked, none found
)
mixed_by_id = {z["id"]: z for z in mixed_scored}
assert mixed_by_id[VALLEY_ZONE_ID]["confidence"] == "high"
assert mixed_by_id[NO_VALLEY_ZONE_ID]["confidence"] == "low"
assert mixed_by_id[VALLEY_ZONE_ID]["confidence"] != mixed_by_id[NO_VALLEY_ZONE_ID]["confidence"]
print(
    f"Confidence differs across candidates in the SAME run: zone {VALLEY_ZONE_ID}="
    f"{mixed_by_id[VALLEY_ZONE_ID]['confidence']}, zone {NO_VALLEY_ZONE_ID}={mixed_by_id[NO_VALLEY_ZONE_ID]['confidence']}."
)


# --- gravity confidence_notes framing: plain tradeoff, not an apology ---
#
# A dedicated below-elevation (pump-required) scenario: the same two
# drainage columns, but served by a HIGH-elevation production area so
# both zones sit below it.
BELOW_PRODUCTION_AREAS = [
    {
        "id": 0,
        "representative_elevation_m": 100.0,
        "polygon_utm": box(500080.0, 4499750.0, 500120.0, 4499800.0),
        "render_fill_polygon_utm": box(500080.0, 4499750.0, 500120.0, 4499800.0),
    }
]
below_zones = find_candidate_zones(WATER_SUITABILITY_DEM, BELOW_PRODUCTION_AREAS, BOUNDARY)
below_zone = next(z for z in below_zones if z["id"] == 0)
below_scored = score_water_zones([below_zone], [], WATER_SUITABILITY_DEM)[0]
assert below_scored["primary_production_area_relationship"]["above_production_area"] is False
assert below_scored["suitability_score"] > 0.0, "a below-elevation (pump-required) candidate must still score > 0, never be zeroed out"
print(f"Below-elevation (pump-required) candidate remains a real, scoreable, non-zero candidate: score={below_scored['suitability_score']}/100.")

below_notes = below_scored["confidence_notes"].lower()
assert "pump" in below_notes
assert "cost/maintenance tradeoff" in below_notes or "tradeoff" in below_notes
apology_phrases = ["unfortunately", "sadly", "poor choice", "bad site", "should be avoided"]
assert not any(phrase in below_notes for phrase in apology_phrases), (
    "below-elevation confidence_notes must state the pump tradeoff plainly, not apologize for it"
)
print("Below-elevation candidate's confidence_notes states the pump tradeoff plainly, without apologizing for it.")

nhd_offset_zone = scored_by_id[VALLEY_ZONE_ID]  # has a real, close, in-range stream
assert "100-300m" in nhd_offset_zone["confidence_notes"], "NHD offset limitation must be stated when stream proximity meaningfully affects score"
print("NHD 100-300m DEM-offset limitation is stated in confidence_notes when stream proximity meaningfully affects the score.")


# --- output is a schema-valid FeatureCollection on the required layer ---

geojson = water_suitability_to_geojson(best_case_scored)
validate_feature_collection(geojson)
confidences_seen = {f["properties"]["confidence"] for f in geojson["features"]}
for feature in geojson["features"]:
    assert feature["properties"]["layer"] == "water_system_candidate"
    assert "suitability_score" in feature["properties"]
    assert "gravity_feed_factor" in feature["properties"]
    assert "soil_water_holding_factor" in feature["properties"]
    assert "stream_permanence_factor" in feature["properties"]
    assert "topographic_factor" in feature["properties"]
print(f"water_suitability_to_geojson() output is schema-valid, layer='water_system_candidate', confidences observed: {confidences_seen}.")


# --- offline full-pipeline wiring check (synthetic DEM, no network) ----

import numpy as np
from rasterio.warp import transform as warp_transform

from dem_data import _utm_epsg_for_lonlat

CENTER_LON, CENTER_LAT = -79.98, 40.64
EPSG = _utm_epsg_for_lonlat(CENTER_LON, CENTER_LAT)
DST_CRS = f"EPSG:{EPSG}"
center_x, center_y = warp_transform("EPSG:4326", DST_CRS, [CENTER_LON], [CENTER_LAT])
center_x, center_y = center_x[0], center_y[0]

RESOLUTION = 5.0
SIZE = 40
HALF_EXTENT = SIZE * RESOLUTION / 2
origin_x = center_x - HALF_EXTENT
origin_y = center_y + HALF_EXTENT

utm_corners_x = [origin_x, origin_x + SIZE * RESOLUTION, origin_x + SIZE * RESOLUTION, origin_x, origin_x]
utm_corners_y = [origin_y, origin_y, origin_y - SIZE * RESOLUTION, origin_y - SIZE * RESOLUTION, origin_y]
lons, lats = warp_transform(DST_CRS, "EPSG:4326", utm_corners_x, utm_corners_y)
boundary_coordinates = list(zip(lons, lats))

array = np.zeros((SIZE, SIZE), dtype=np.float32)
for row in range(SIZE):
    for col in range(SIZE):
        if row >= SIZE - 8:
            array[row, col] = 100.0  # flat southern bench (production area)
        else:
            distance_from_center_col = abs(col - SIZE // 2)
            array[row, col] = 100.0 + (SIZE - 8 - row) * 3.0 + distance_from_center_col * 1.5

synthetic_dem = {
    "array": array,
    "resolution_meters": (RESOLUTION, RESOLUTION),
    "origin_x": origin_x,
    "origin_y": origin_y,
    "crs": DST_CRS,
}

# identify_water_suitability() calls production_area.identify_production_areas()
# internally with no check_soil/check_canopy passthrough of its own (water_suitability.py
# is unchanged by the canopy-gate work) -- and that gate is now mandatory, with a fetch
# failure raising rather than degrading. Patched here (production_area's own module-level
# name, which is what identify_production_areas() actually looks up) to a fixed offline
# stub so this wiring check stays fully offline; the gate's own hard-failure behavior has
# its own dedicated tests in test_canopy_height_data.py.
def _fake_clean_canopy(boundary_coordinates, dem):
    return {
        "array": np.full(dem["array"].shape, 1.0, dtype=np.float32),  # below threshold everywhere -- no trees
        "resolution_meters": dem["resolution_meters"],
        "origin_x": dem["origin_x"],
        "origin_y": dem["origin_y"],
        "crs": dem["crs"],
        "source_item_id": "offline-test-stub",
    }


pa.get_canopy_height_for_boundary = _fake_clean_canopy

# The existing-road exclusion gate is optional (degrades gracefully, unlike canopy) but
# still defaults to check_roads=True and attempts a real fetch otherwise -- stubbed the
# same way, to "no roads found nearby" (None), so this wiring check stays fully offline.
pa.get_road_exclusion_union_utm = lambda boundary_coordinates, dem, buffer_meters=None: None

pipeline_result = identify_water_suitability(
    boundary_coordinates, dem=synthetic_dem, check_soil=False, check_streams=False,
    zone_kwargs={"min_boundary_setback_meters": 5.0},
)
validate_feature_collection(pipeline_result["zones_geojson"])
assert len(pipeline_result["scored_zones"]) >= 1, "expected at least one scored water system candidate zone"
for zone in pipeline_result["scored_zones"]:
    assert zone["confidence"] == "low", "with both soil and stream checks disabled, confidence must fall back to low"
    assert zone["soil_data_available"] is False
    assert zone["stream_data_available"] is False
print(f"identify_water_suitability() full pipeline wiring works end-to-end offline: {len(pipeline_result['scored_zones'])} scored zone(s), check_soil/check_streams=False correctly yields confidence='low'.")


# --- boundary_polygon_utm/valleys/production_areas overrides ------------
#
# Real baseline production areas for this same synthetic_dem/boundary_coordinates,
# via the SAME production_area_ceiling.identify_optimized_production_areas() call
# identify_water_suitability()'s own self-compute fallback now makes -- computed
# once here (real, offline via the already-applied pa.get_canopy_height_for_boundary/
# pa.get_road_exclusion_union_utm stubs above) and reused below as both the
# "what the default/self-computed path produces" reference and a ready-made,
# realistic override value.
baseline_optimized_result = ws.identify_optimized_production_areas(boundary_coordinates, dem=synthetic_dem)
BASELINE_PRODUCTION_AREAS = baseline_optimized_result["scored_patches"]
assert BASELINE_PRODUCTION_AREAS, "test setup: expected at least one real production area on this synthetic DEM"

# --- 1. regression: with no overrides, production_areas comes from -----
# --- identify_optimized_production_areas(), NOT identify_production_areas() ---

with mock_patch.object(
    ws, "identify_optimized_production_areas", return_value=baseline_optimized_result
) as mock_optimized, mock_patch.object(ws, "identify_production_areas") as mock_raw:
    default_result = identify_water_suitability(
        boundary_coordinates, dem=synthetic_dem, check_soil=False, check_streams=False,
        zone_kwargs={"min_boundary_setback_meters": 5.0},
    )

assert mock_optimized.call_count == 1, "identify_optimized_production_areas() must be called exactly once when production_areas isn't supplied"
optimized_call = mock_optimized.call_args
assert optimized_call.args[0] == boundary_coordinates
assert optimized_call.kwargs["dem"] is synthetic_dem
assert mock_raw.call_count == 0, "identify_production_areas() (the RAW, un-ceiling-trimmed source) must NOT be called for production_areas anymore"
assert len(default_result["scored_zones"]) >= 1, "expected at least one scored water system candidate zone from the real baseline production areas"
print(
    "REGRESSION: with no production_areas override, identify_water_suitability() sources it from "
    "identify_optimized_production_areas() exactly once, and never calls the raw identify_production_areas()."
)


# --- 2. override behavior: all three new overrides supplied -> the ------
# --- corresponding self-compute fallbacks are never called --------------

from rasterio.warp import transform as _override_warp_transform  # noqa: E402

override_boundary_xs, override_boundary_ys = _override_warp_transform(
    "EPSG:4326", synthetic_dem["crs"],
    [pt[0] for pt in boundary_coordinates], [pt[1] for pt in boundary_coordinates],
)
from shapely.geometry import Polygon as _OverridePolygon  # noqa: E402
OVERRIDE_BOUNDARY_POLYGON_UTM = _OverridePolygon(zip(override_boundary_xs, override_boundary_ys))

with mock_patch.object(ws, "delineate_valleys") as mock_delineate_override, mock_patch.object(
    ws, "identify_optimized_production_areas"
) as mock_optimized_override:
    override_result = identify_water_suitability(
        boundary_coordinates,
        dem=synthetic_dem,
        boundary_polygon_utm=OVERRIDE_BOUNDARY_POLYGON_UTM,
        valleys=[],
        production_areas=BASELINE_PRODUCTION_AREAS,
        check_soil=False,
        check_streams=False,
        zone_kwargs={"min_boundary_setback_meters": 5.0},
    )

assert mock_delineate_override.call_count == 0, "delineate_valleys() must NOT be called when valleys was supplied as an override"
assert mock_optimized_override.call_count == 0, "identify_optimized_production_areas() must NOT be called when production_areas was supplied as an override"
assert len(override_result["scored_zones"]) >= 1
print(
    "Supplying boundary_polygon_utm=/valleys=/production_areas= all three as overrides correctly skips "
    "both delineate_valleys() and identify_optimized_production_areas() -- zero self-compute fallback calls."
)


# --- 3. scoring output genuinely reflects the overridden production_areas ---
# --- (not silently falling back to the self-computed default) -----------
#
# Same override_result run above (BASELINE_PRODUCTION_AREAS) vs. a second run using
# a copy of those same patches with every representative_elevation_m shifted sharply
# UP (simulating a much higher production area) -- if production_areas were silently
# ignored, both runs would score identically; they must not.

RAISED_PRODUCTION_AREAS = [
    {**patch, "representative_elevation_m": patch["representative_elevation_m"] + 500.0}
    for patch in BASELINE_PRODUCTION_AREAS
]

with mock_patch.object(ws, "delineate_valleys") as _mock_delineate_raised, mock_patch.object(
    ws, "identify_optimized_production_areas"
) as _mock_optimized_raised:
    raised_result = identify_water_suitability(
        boundary_coordinates,
        dem=synthetic_dem,
        boundary_polygon_utm=OVERRIDE_BOUNDARY_POLYGON_UTM,
        valleys=[],
        production_areas=RAISED_PRODUCTION_AREAS,
        check_soil=False,
        check_streams=False,
        zone_kwargs={"min_boundary_setback_meters": 5.0},
    )

assert _mock_delineate_raised.call_count == 0 and _mock_optimized_raised.call_count == 0

override_by_id = {z["id"]: z for z in override_result["scored_zones"]}
raised_by_id = {z["id"]: z for z in raised_result["scored_zones"]}
common_ids = set(override_by_id) & set(raised_by_id)
assert common_ids, "expected at least one zone id in common between the baseline-elevation and raised-elevation runs to compare"

differed = False
for zone_id in common_ids:
    baseline_gravity = override_by_id[zone_id]["gravity_feed_factor"]
    raised_gravity = raised_by_id[zone_id]["gravity_feed_factor"]
    if baseline_gravity != raised_gravity:
        differed = True
    # a candidate zone sits at a roughly fixed real elevation -- pushing its served
    # production area's representative_elevation_m up by 500m must never make its
    # gravity relationship MORE favorable, only equal or worse (it can never make the
    # candidate more "above" a production area that just got raised further above it).
    assert raised_gravity <= baseline_gravity, (
        f"zone {zone_id}: raising the served production area's elevation by 500m must not improve "
        f"gravity_feed_factor (baseline={baseline_gravity}, raised={raised_gravity})"
    )
assert differed, "raising every overridden production area's representative_elevation_m by 500m must change at least one zone's gravity_feed_factor -- production_areas is being silently ignored otherwise"
print(
    "Scoring output genuinely reflects the overridden production_areas: raising every overridden patch's "
    "representative_elevation_m by 500m correctly lowers (never improves) the served zone(s)' "
    "gravity_feed_factor, proving the override isn't silently falling back to self-computed patches."
)


# --- 4. fetch_and_select_optimal_water_zone() forwards new overrides ----
# --- through **suitability_kwargs -----------------------------------------

_fake_selected_zone = {"id": 999, "suitability_score": 42.0}
_fake_identify_result = {
    "zones_geojson": {"type": "FeatureCollection", "features": []},
    "scored_zones": [],
    "all_scored_zones": [],
    "selected_water_zone": _fake_selected_zone,
}
with mock_patch.object(ws, "identify_water_suitability", return_value=_fake_identify_result) as mock_identify:
    wrapper_result = fetch_and_select_optimal_water_zone(
        boundary_coordinates,
        dem=synthetic_dem,
        production_areas=BASELINE_PRODUCTION_AREAS,
        valleys=[],
    )

assert wrapper_result == _fake_selected_zone, "fetch_and_select_optimal_water_zone() must return identify_water_suitability()'s own selected_water_zone"
assert mock_identify.call_count == 1
identify_call = mock_identify.call_args
assert identify_call.args[0] == boundary_coordinates
assert identify_call.kwargs["dem"] is synthetic_dem
assert identify_call.kwargs["production_areas"] is BASELINE_PRODUCTION_AREAS, "production_areas= must reach identify_water_suitability() via **suitability_kwargs"
assert identify_call.kwargs["valleys"] == [], "valleys= must also reach identify_water_suitability() via **suitability_kwargs"
print(
    "fetch_and_select_optimal_water_zone() correctly forwards production_areas=/valleys= (and, by the same "
    "**suitability_kwargs mechanism, boundary_polygon_utm=) straight through to identify_water_suitability(), "
    "with no signature change needed on the wrapper itself."
)


# --- canopy_height override forwarding ---
#
# identify_water_suitability() reaches canopy on TWO independent paths when
# production_areas is left to self-compute: its default identify_optimized_
# production_areas() fetch AND its own mandatory get_required_tree_root_
# zone_mask_utm() gate. A supplied canopy_height override must reach BOTH,
# so neither re-fetches from the network. Shared-core behavior is proven in
# test_canopy_mask_override.py; this proves this entry point forwards the
# override down every canopy path. Reuses the fully-offline synthetic_dem/
# boundary fixture the end-to-end wiring check above already uses.
from _canopy_override_probe import CanopyOverrideProbe, clean_canopy_for  # noqa: E402

_ov_override = clean_canopy_for(synthetic_dem)
with CanopyOverrideProbe() as _ov_probe:
    identify_water_suitability(
        boundary_coordinates, dem=synthetic_dem, check_soil=False, check_streams=False,
        zone_kwargs={"min_boundary_setback_meters": 5.0}, canopy_height=_ov_override,
    )
_ov_probe.assert_override_used(_ov_override, "identify_water_suitability()")
assert len(_ov_probe.mask_arrays) >= 2, (
    "identify_water_suitability(): with production_areas self-computed, the override must reach BOTH "
    f"canopy paths (internal identify_optimized_production_areas + own gate), saw {len(_ov_probe.mask_arrays)}"
)
print(
    "identify_water_suitability(): a supplied canopy_height override reaches BOTH internal canopy paths "
    f"({len(_ov_probe.mask_arrays)} gates) -- 0 canopy fetches, exact override array used throughout."
)


print("\nAll water_suitability checks passed.")
